- pymongo/common.py
- pymongo/mongo_client.py
- test/test_client.py
reopening #309 after rebasing onto 34dev branch
> [PYTHON-1123] Cannot customize some properties of MongoClient.codec_options

- doc/contributors.rst
- doc/examples/authentication.rst
Reference to the ticket https://jira.mongodb.org/browse/PYTHON-1388.
> PYTHON-1388 fix docs example.

- doc/contributors.rst
Sorry. forgot to add my name to contributer's list.
> Contributer name addition

- doc/contributors.rst
- doc/examples/geo.rst
1. Added documentation to use GEOSPHERE when working with latitudes and longitudes.
2. Added notes when inserting location in GEOSPHERE.
3. Added warning of deprecated geoNear command.
> Clarification on geospatial indexing.

- test/test_examples.py
Closes [PYTHON-1623](https://jira.mongodb.org/browse/PYTHON-1623).
> DOC: add manual example for causal consistency

- test/test_examples.py
Closes [PYTHON-1623](https://jira.mongodb.org/browse/PYTHON-1623)
> PYTHON-1623 Explicitly state read & write concern in causal consistency manual examples

- pymongo/mongo_client.py
- test/test_client.py
Jira: https://jira.mongodb.org/browse/PYTHON-1704
Fixes: https://github.com/mongodb/motor/pull/44
> PYTHON-1704 Close periodic task thread when client is closed

- test/test_uri_spec.py
- test/uri_options/compression-options.json
The failure was likely the result of an incorrect spec-test.
> Fix compression URI options test failure

- test/__init__.py
- test/test_database.py
- test/test_legacy_api.py
Jira: https://jira.mongodb.org/browse/PYTHON-1719 and https://jira.mongodb.org/browse/PYTHON-1734
I plan to merge this into master and 42dev.
> PYTHON-1719/PYTHON-1734 Fix test failures on MongoDB 4.1+

- test/transactions/abort.json
- test/transactions/error-labels.json
Jira: https://jira.mongodb.org/browse/PYTHON-1751
Merging once the tests pass.
> PYTHON-1751 Resync transaction spec tests for bulk write error reporting change

- doc/changelog.rst
Copy/pasted from the 3.7.2 release tag.
> Add changelog for 3.7.2

- doc/changelog.rst
- pymongo/client_session.py
- test/test_transactions.py
- test/transactions-convenient-api/callback-aborts.json
- test/transactions-convenient-api/callback-commits.json
- test/transactions-convenient-api/callback-retry.json
- test/transactions-convenient-api/commit-retry.json
- test/transactions-convenient-api/commit-transienttransactionerror-4.2.json
- test/transactions-convenient-api/commit-transienttransactionerror.json
- test/transactions-convenient-api/commit-writeconcernerror.json
- test/transactions-convenient-api/commit.json
- test/transactions-convenient-api/transaction-options.json
- test/utils.py
Jira: https://jira.mongodb.org/browse/PYTHON-1671
> PYTHON-1671 Add ClientSession.with_transaction API

- test/test_transactions.py
Jira: https://jira.mongodb.org/browse/PYTHON-1772
I think the current tests are flakey because the session uses monotonic time in other places besides `with_transaction`. I've replaced the monotonic time patching with just patching the global timeout which is way simpler.
> PYTHON-1772 Fix flakey mock timeout tests for with_transaction

- pymongo/pool.py
Jira: https://jira.mongodb.org/browse/PYTHON-2297
This fixes the `ResourceWarning: unclosed <socket.socket ...` when auth fails while checking out a connection.
CC: @juliusgeo
> PYTHON-2297 Close connection to avoid resource warning when auth fails

- pymongo/monitor.py
- pymongo/monitoring.py
- test/test_monitoring.py
- test/test_streaming_protocol.py
Jira: https://jira.mongodb.org/browse/PYTHON-2299
> PYTHON-2299 Add the "awaited" field to heartbeat events

- .evergreen/build-manylinux.sh
- .evergreen/config.yml
Tested here: https://evergreen.mongodb.com/version/5f35d25dd6d80a0c926f8db0
> PYTHON-2339 Build manylinux2014_aarch64/ppc64le/s390x releases

- test/sdam_monitoring/discovered_standalone.json
- test/sdam_monitoring/standalone_suppress_equal_description_changes.json
Jira: https://jira.mongodb.org/browse/PYTHON-2351
> PYTHON-2351 Update sdam monitoring tests with directConnection uri option

- doc/_templates/layout.html
> DOP-1671: update GTM code

- .evergreen/config.yml
- .evergreen/utils.sh
Fixes https://jira.mongodb.org/browse/PYTHON-2507.
> PYTHON-2507 Future proof pip version upgrade for test suite

- .evergreen/run-tests.sh
Tested here: https://spruce.mongodb.com/version/6008a8549ccd4e67026a6d85/tasks
> PYTHON-2516 Fix coverage task and C extension check

- .evergreen/config.yml
Tested here: https://evergreen.mongodb.com/version/6011be3f57e85a32cbe17946
> PYTHON-2445 PYTHON-2530 Fix MONGODB-AWS auth tests

- .evergreen/perf.yml
- .evergreen/run-perf-tests.sh
- test/performance/perf_test.py
Tested here: https://spruce.mongodb.com/version/601aeb54d1fe0705740e9e26
Depends on: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/139
> PYTHON-2537 Fix benchmark when using Python 3

- pymongo/encryption.py
Note that cert_reqs=None and cert_reqs=CERT_REQUIRED are identical
so this does not change any behavior.
> PYTHON-2578 Improve clarity of TLS settings for KMS requests

- pymongo/encryption.py
`Algorithm.Random` to `Algorithm.AEAD_AES_256_CBC_HMAC_SHA_512_Random`
> PYTHON-2628L Fix 'encryption::create_data_key` docstring to use existing algorithm

- test/test_server_selection_in_window.py
Tested here: https://evergreen.mongodb.com/version/607a1187d1fe0724ae3b6f3c
[no ci]
> PYTHON-2584 Use large localThresholdMS to fix test_load_balancing

- doc/changelog.rst
- pymongo/__init__.py
- pymongo/database.py
- test/test_database.py
Patch: https://spruce.mongodb.com/version/6099cc480305b97fd5038662/
> Deprecate profiler helpers

- pymongo/message.py
- pymongo/pool.py
- test/test_versioned_api.py
- test/unified_format.py
- test/versioned-api/crud-api-version-1-strict.json
- test/versioned-api/crud-api-version-1.json
- test/versioned-api/runcommand-helper-no-api-version-declared.json
- test/versioned-api/test-commands-strict-mode.json
- test/versioned-api/transaction-handling.json
An implementation of https://github.com/mongodb/specifications/pull/984.
> PYTHON-2684 Send Versioned API options with getMore+txn commands

- pymongo/change_stream.py
- pymongo/client_session.py
- pymongo/collection.py
- pymongo/command_cursor.py
- pymongo/database.py
- pymongo/mongo_client.py
- pymongo/pool.py
- pymongo/server.py
- test/load_balancer/unified/wait-queue-timeouts.json
- test/pymongo_mocks.py
- test/test_cmap.py
- test/test_pooling.py
- test/test_read_preferences.py
- test/utils.py
See https://github.com/mongodb/specifications/blob/master/source/load-balancers/load-balancers.rst#connection-tracking
> PYTHON-2677 Better wait queue timeout errors for load balanced clusters

- doc/changelog.rst
- pymongo/change_stream.py
- pymongo/errors.py
- pymongo/helpers.py
- pymongo/message.py
- pymongo/mongo_client.py
- pymongo/monitor.py
- pymongo/network.py
- pymongo/pool.py
- pymongo/server.py
- pymongo/topology.py
- test/test_connections_survive_primary_stepdown_spec.py
- test/test_discovery_and_monitoring.py
- test/test_errors.py
- test/test_monitoring.py
- test/test_sdam_monitoring_spec.py
- test/unified_format.py
(cherry picked from commit ff6ca53328bfa62f35cb169d6440c2a642b853d2)
> [Backport] PYTHON-2572 Introduce NotPrimaryError and deprecate NotMasterError

- test/__init__.py
- test/sessions/unified/snapshot-sessions-not-supported-server-error.json
See: https://github.com/mongodb/specifications/pull/1030
> PYTHON-2779 Fix topologies field in snapshot reads test

- pymongo/collection.py
- pymongo/message.py
- test/test_cursor.py
- test/test_session.py
~~ @ShaneHarvey what am I missing here? More tests? Edge cases? ~~
> PYTHON-2389 Add session support to find_raw_batches and aggregate_raw_batches

- test/unified-test-format/valid-pass/observeSensitiveCommands.json
- test/unified_format.py
Depends on https://github.com/mongodb/specifications/pull/1043
> PYTHON-2842 Integration tests for observeSensitiveCommands field

- test/cmap/pool-checkout-no-idle.json
- test/cmap/pool-checkout-no-stale.json
- test/cmap/pool-clear-min-size.json
- test/cmap/pool-create-min-size-error.json
- test/cmap/wait-queue-timeout.json
- test/test_cmap.py
See https://github.com/mongodb/specifications/commit/ff282c752dc73ae49622df4ac87a68a9e9dbe95c
> PYTHON-2697 Fix races in various CMAP spec tests

- doc/changelog.rst
- pymongo/__init__.py
- setup.py
Please review the new changelog entry: https://pymongo--810.org.readthedocs.build/en/810/changelog.html
> BUMP 3.12.3

- .evergreen/config.yml
https://spruce.mongodb.com/version/61f1de7d3627e057e11e35bc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-1596 Test on RHEL7 FIPS

- .evergreen/config.yml
https://spruce.mongodb.com/version/62029dc8d6d80a605ebd65d1/tasks
> PYTHON-3043 Test mod_wsgi with Python 3.10

- .evergreen/config.yml
- pymongo/pool.py
- test/__init__.py
PYTHON-3088 Update load balancer tests to support dedicated load balancer port (#866)
(cherry picked from commit 341d489f38ad51620fab50bfc7c3f8c1227fefee)
> PYTHON-3088 [v4.0] Update load balancer tests to support dedicated load balancer port

- bson/binary.py
- doc/atlas.rst
- doc/changelog.rst
- doc/conf.py
- doc/developer/periodic_executor.rst
- doc/examples/high_availability.rst
- doc/examples/mod_wsgi.rst
- doc/examples/tailable.rst
- doc/examples/tls.rst
- doc/faq.rst
- doc/index.rst
- doc/tools.rst
- pymongo/change_stream.py
- pymongo/collection.py
- pymongo/database.py
- pymongo/mongo_client.py
- pymongo/operations.py
(cherry picked from commit 087950d869096cf44a797f6c402985a73ffec16e)
> PYTHON-3164 [v3.13] Outdated link from PyMongo docs to community forum

- .evergreen/run-perf-tests.sh
- .evergreen/run-tests.sh
patch: https://spruce.mongodb.com/version/623a349d2a60ed2bb7690aa4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-3180 Use server v3 toolchain in perf tests

- pymongo/uri_parser.py
- test/test_client.py
https://jira.mongodb.org/browse/PYTHON-3198
> PYTHON-3198 Fix NameError: name sys is not defined

- .evergreen/resync-specs.sh
- test/client-side-encryption/spec/badQueries.json
- test/client-side-encryption/spec/types.json
- test/test_encryption.py
Fixes failing FLE tests on latest.
https://jira.mongodb.org/browse/PYTHON-3221
> PYTHON-3221 Resync CSFLE spec tests

- .evergreen/config.yml
https://jira.mongodb.org/browse/PYTHON-3230
> PYTHON-3230 Migrate to newer zSeries, POWER8, and ARM platforms

- test/test_server_selection_in_window.py
Implements https://jira.mongodb.org/browse/PYTHON-2924
> PYTHON-2924 Improve test_load_balancing

- doc/changelog.rst
- pymongo/collection.py
- pymongo/database.py
- pymongo/encryption.py
- pymongo/encryption_options.py
https://jira.mongodb.org/browse/PYTHON-3293
> PYTHON-3293 Document Queryable Encryption API is in beta

- pymongo/_csot.py
- pymongo/collection.py
- pymongo/database.py
- pymongo/mongo_client.py
- test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-3289
Depends on https://github.com/mongodb/mongo-python-driver/pull/1009
> PYTHON-3289 Apply client timeoutMS to every operation

- test/test_examples.py
https://jira.mongodb.org/browse/PYTHON-3284
> PYTHON-3284 Fix test_snapshot_query by waiting for documents to be committed to the snapshot

- test/transactions/unified/do-not-retry-read-in-transaction.json
POC for https://github.com/mongodb/specifications/pull/1277
> PYTHON-3368 Add test that reads are not retried in a transaction

- bson/codec_options.py
Added short docstrings to each of the `DatetimeConversionOpts`.
> PYTHON-3375 Added docstrings to DatetimeConversionOpts

- test/__init__.py
- test/csot/gridfs-advanced.json
- test/csot/gridfs-delete.json
- test/csot/gridfs-download.json
- test/csot/gridfs-find.json
- test/csot/gridfs-upload.json
- test/test_change_stream.py
- test/test_csot.py
- test/test_custom_types.py
- test/test_examples.py
Fix: https://jira.mongodb.org/browse/PYTHON-3391
> PYTHON-3391 Skip unsupported CSOT tests on serverless

- test/test_retryable_writes.py
- test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-3409
> PYTHON-3409 Retry flakey CSOT tests twice

- .evergreen/build-mac.sh
- .evergreen/config.yml
- tools/fail_if_no_c.py
(cherry picked from commit 1019c91bf67fbed09f6ce26df16614092676ab54)
> PYTHON-3424 PyMongo Universal Wheels Are Improperly Compiled

- .evergreen/build-manylinux-internal.sh
- .evergreen/build-manylinux.sh
- .evergreen/build-windows.sh
- .evergreen/config.yml
- bson/codec_options.py
- setup.py
- test/test_client.py
(cherry picked from commit df77653ccc6b1bbfa18f8fca41cd4a1bfecc25c6)
> PYTHON-3475 Add Python 3.11 Support to PyMongo 3

- .evergreen/config.yml
(cherry picked from commit ff1efd1ab28c56e70a101768bd285055b5e4fd9a)
Addresses build failure ticket https://jira.mongodb.org/browse/PYTHON-3482
> PYTHON-2986 Update serverless testing for load balancer fronting single proxy (#997)

- .evergreen/config.yml
- test/test_srv_polling.py
(cherry picked from commit 24a343b830e7382576691712873893902159ee4f)
> PYTHON-3468 [v3.13] Test failures in test_srv_polling.TestSrvPolling (#1073)

- .evergreen/utils.sh
(cherry picked from commit b6982e85f5264daf5ba766a8d1678b1f966d0d2a)
> PYTHON-3498 Error installing virtual environment on zseries hosts (#1101)

- test/retryable_reads/unified/handshakeError.json
- test/retryable_writes/unified/handshakeError.json
Tests for https://github.com/mongodb/specifications/pull/1346
> PYTHON-3500 Properly skip createChangeStream tests on serverless

- .evergreen/perf.yml
See https://jira.mongodb.org/browse/PYTHON-3541
> PYTHON-3541 Use bash instead of sh in perf testing

- test/test_gridfs.py
- test/test_gridfs_bucket.py
- test/test_threads.py
- test/utils_spec_runner.py
https://jira.mongodb.org/browse/PYTHON-3609
setDaemon is the only deprecated api we're using.
> PYTHON-3609 Stop using deprecated setDaemon api in test suite

- .evergreen/run-atlas-tests.sh
- test/atlas/test_connection.py
Fixes: https://jira.mongodb.org/browse/PYTHON-3629
> PYTHON-3629 Use env with dnspython installed for Atlas tests

- doc/examples/authentication.rst
https://jira.mongodb.org/browse/PYTHON-3643
> PYTHON-3643 Use mongodb+srv in MONGODB-AWS auth examples

- test/__init__.py
https://jira.mongodb.org/browse/PYTHON-3671
> PYTHON-3671 Use default server selection timeout in test setup

- pymongo/collection.py
- pymongo/operations.py
https://jira.mongodb.org/browse/PYTHON-3700
> PYTHON-3700 Clean up docs for create_index/drop_indexes

- .pre-commit-config.yaml
- bson/__init__.py
- bson/_cbsonmodule.c
- bson/objectid.py
- bson/time64.c
- doc/changelog.rst
- doc/contributors.rst
- doc/examples/bulk.rst
- doc/examples/type_hints.rst
- gridfs/grid_file.py
- pymongo/collection.py
- pymongo/common.py
- pymongo/message.py
- pymongo/ocsp_support.py
- pymongo/results.py
- pymongo/uri_parser.py
- test/client-side-encryption/spec/legacy/fle2v2-MissingKey.json
- test/csot/deprecated-options.json
- test/mod_wsgi_test/mod_wsgi_test.conf
- test/mypy_fails/raw_bson_document.py
- test/mypy_fails/typedict_client.py
- test/test_read_write_concern_spec.py
- test/test_typing.py
https://jira.mongodb.org/browse/PYTHON-3703
> PYTHON-3703 Fix typos and add codespell pre-commit hook 

- doc/examples/encryption.rst
- pymongo/encryption.py
- pymongo/encryption_options.py
- pymongo/errors.py
https://jira.mongodb.org/browse/PYTHON-3709
> PYTHON-3709 Remove "beta" from Queryable Encryption Equality API

- test/client-side-encryption/spec/legacy/fle2v2-CreateCollection.json
- test/utils_spec_runner.py
https://jira.mongodb.org/browse/PYTHON-3724
> PYTHON-3724 Remove null values from `command_started_event` in fle2v2-CreateCollection.yml

- .evergreen/config.yml
https://jira.mongodb.org/browse/PYTHON-3721
> PYTHON-3721 Stop Testing on AWS Linux 2018

- test/test_change_stream.py
https://jira.mongodb.org/browse/PYTHON-3699
Implemented to review: https://github.com/mongodb/specifications/pull/1425
> PYTHON-3699 Add prose test for change stream splitting

- .github/CODEOWNERS
https://jira.mongodb.org/browse/PYTHON-3736
> PYTHON-3736 Add Noah to code owners for PyMongo, Motor, and PyMongoArrow

- pymongo/cursor.py
- pymongo/helpers.py
- pymongo/operations.py
https://jira.mongodb.org/browse/PYTHON-3740
> PYTHON-3740 add types to helpers.py

- pymongo/aggregation.py
- pymongo/change_stream.py
- pymongo/mongo_client.py
https://jira.mongodb.org/browse/PYTHON-3755
> PYTHON-3755 add types to aggregation.py

- pymongo/auth_aws.py
https://jira.mongodb.org/browse/PYTHON-3769
> PYTHON-3769 add types to auth_aws.py

- pymongo/ocsp_support.py
https://jira.mongodb.org/browse/PYTHON-3767
> PYTHON-3767 add types to ocsp_support.py

- pymongo/change_stream.py
https://jira.mongodb.org/browse/PYTHON-3772
> PYTHON-3772 add types to change_stream.py

- pymongo/settings.py
- test/test_topology.py
https://jira.mongodb.org/browse/PYTHON-3764
> PYTHON-3764 add types to settings.py

- pymongo/bulk.py
- pymongo/operations.py
https://jira.mongodb.org/browse/PYTHON-3752
> PYTHON-3752 add types to bulk.py

- pymongo/daemon.py
https://jira.mongodb.org/browse/PYTHON-3784
> PYTHON-3784 add types to daemon.py

- pymongo/compression_support.py
https://jira.mongodb.org/browse/PYTHON-3783
> PYTHON-3783 add types to compression_support.py

- pymongo/lock.py
https://jira.mongodb.org/browse/PYTHON-3782
> PYTHON-3782 add types to lock.py

- pymongo/max_staleness_selectors.py
https://jira.mongodb.org/browse/PYTHON-3787
> PYTHON-3787 add types to max_staleness_selectors.py

- pymongo/response.py
https://jira.mongodb.org/browse/PYTHON-3785
> PYTHON-3785 add types to response.py

- pymongo/server_selectors.py
https://jira.mongodb.org/browse/PYTHON-3788
> PYTHON-3788 add types to server_selectors.py

- pymongo/srv_resolver.py
https://jira.mongodb.org/browse/PYTHON-3786
> PYTHON-3786 add types to srv_resolver.py

- pymongo/client_session.py
https://jira.mongodb.org/browse/PYTHON-3773
> PYTHON-3773 add types to client_session.py

- pymongo/auth_oidc.py
- pymongo/pool.py
https://jira.mongodb.org/browse/PYTHON-3770
> PYTHON-3770 add types to auth_oidc.py

- doc/examples/encryption.rst
https://jira.mongodb.org/browse/PYTHON-3796
> PYTHON-3796 Fix typo in docs and reformat using blacken-docs

- bson/_cbsonmodule.c
- pymongo/_cmessagemodule.c
https://jira.mongodb.org/browse/PYTHON-3729
> PYTHON-3729 use PyObject_GetAddr instead of PyObject_GetAddrString

- pymongo/command_cursor.py
- pymongo/message.py
https://jira.mongodb.org/browse/PYTHON-3777
> PYTHON-3777 add types to command_cursor.py

- pymongo/aggregation.py
- pymongo/collection.py
- pymongo/common.py
- pymongo/cursor.py
https://jira.mongodb.org/browse/PYTHON-3778
> PYTHON-3778 add types to common.py

- bson/_cbsonmodule.c
https://jira.mongodb.org/browse/PYTHON-3816
> PYTHON-3816 use Use PyObject_GetItem instead of PyMapping_GetItemString

- pymongo/hello.py
https://jira.mongodb.org/browse/PYTHON-3805
> PYTHON-3805 add types to hello.py

- pymongo/errors.py
https://jira.mongodb.org/browse/PYTHON-3804
> PYTHON-3804 add types to errors.py

- doc/examples/encryption.rst
https://jira.mongodb.org/browse/PYTHON-3818
> PYTHON-3818 Create unique key vault index in auto QE example

- bson/_cbsonmodule.c
https://jira.mongodb.org/browse/PYTHON-3817
> PYTHON-3817 Optimize BSON encoding of standard Python dict

- gridfs/grid_file.py
- pymongo/cursor.py
https://jira.mongodb.org/browse/PYTHON-3780
> PYTHON-3780 add types to cursor.py

- .evergreen/test-encryption-requirements.txt
- doc/changelog.rst
- pymongo/ocsp_support.py
- pyproject.toml
Successful patch: https://spruce.mongodb.com/version/64b04375306615a3d71adc10/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-3829 Certificate typecast in encryption breaking build

- bson/__init__.py
- bson/typings.py
- pymongo/auth_aws.py
- pymongo/monitoring.py
- pymongo/typings.py
https://jira.mongodb.org/browse/PYTHON-3831
> PYTHON-3831 remove _DocumentIn

- bson/__init__.py
- bson/_cbsonmodule.c
- bson/binary.py
- pymongo/auth.py
- pymongo/mongo_client.py
- test/test_bson.py
https://jira.mongodb.org/browse/PYTHON-3511
Follow on to https://github.com/mongodb/mongo-python-driver/pull/1161
> PYTHON-3511 Cleanup some more Python 2 references

- pymongo/bulk.py
- pymongo/helpers.py
- pymongo/operations.py
- test/test_transactions.py
https://jira.mongodb.org/browse/PYTHON-3811
> PYTHON-3811 add types to operations.py

- pymongo/read_concern.py
https://jira.mongodb.org/browse/PYTHON-3859
> PYTHON-3859 add types to read_concern.py

- pymongo/periodic_executor.py
https://jira.mongodb.org/browse/PYTHON-3812
> PYTHON-3812 add types to periodic_executor.py

- pymongo/server_description.py
https://jira.mongodb.org/browse/PYTHON-3862
> PYTHON-3862 add types to server_description.py

- pymongo/write_concern.py
https://jira.mongodb.org/browse/PYTHON-3870
> PYTHON-3870 add types to write_concern.py

- pymongo/socket_checker.py
https://jira.mongodb.org/browse/PYTHON-3864
> PYTHON-3864 add types to socket_checker.py

- pymongo/typings.py
https://jira.mongodb.org/browse/PYTHON-3868
> PYTHON-3868 add types to typings.py

- pymongo/results.py
https://jira.mongodb.org/browse/PYTHON-3861
> PYTHON-3861 add types to results.py

- pymongo/uri_parser.py
https://jira.mongodb.org/browse/PYTHON-3869
> PYTHON-3869 add types to uri_parser.py

- pymongo/server_selectors.py
https://jira.mongodb.org/browse/PYTHON-3863
> PYTHON-3863 add types to server_selectors.py

- pymongo/pyopenssl_context.py
- tools/ocsptest.py
https://jira.mongodb.org/browse/PYTHON-3814
> PYTHON-3814 add types to pyopenssl_context.py

- .github/workflows/pull_request_template.md
- CONTRIBUTING.rst
* Added a Pull Request Template as well as an addendum to our CONTRIBUTING.rst to explain the template
* Added `pull_request_template.md` 
* Added PR Guidance and general best practices to the `CONTRIBUTING.rst`
* See Screenshots
* Used this PR as an example
**BEFORE**
* 
**AFTER**
* 
* 
* Ruminating on the "stylistic" choices behind formatting. 
* Also looking for "content" review to make sure I'm not asking too much.
> PYTHON-3922: Contributor PR Template

- tox.ini
https://jira.mongodb.org/browse/PYTHON-3991
> PYTHON-3991 Fix MockupDB tests when run through tox

- .evergreen/run-tests.sh
Remove `.pytest_cache` as recommend here: https://stackoverflow.com/a/76454959
> PYTHON-3987 Fix coverage report handling

- test/test_discovery_and_monitoring.py
https://jira.mongodb.org/browse/PYTHON-3995
Should fix the race in test_rtt_connection_is_enabled_stream.
> PYTHON-3995 Fix race in serverMonitoringMode test

- .evergreen/config.yml
- .evergreen/run-mongodb-aws-test.sh
Requires https://github.com/mongodb-labs/drivers-evergreen-tools/pull/365
> PYTHON-3489 Remove legacy shell from test scripts

- doc/changelog.rst
- pymongo/message.py
- test/mockupdb/test_cursor.py
https://jira.mongodb.org/browse/PYTHON-4007
> PYTHON-4007 Stop sending exhaustAllowed to Serverless/load balanced clusters unless configured

- .evergreen/run-tests.sh
https://jira.mongodb.org/browse/PYTHON-4009
> PYTHON-4009 Include bson+gridfs in coverage report

- test/test_cursor.py
https://jira.mongodb.org/browse/PYTHON-4010
> PYTHON-4010 Fix test_timeout_kills_cursor_asynchronously

- pymongo/pool.py
- test/test_client.py
Based on the Go Driver implementation: https://github.com/mongodb/mongo-go-driver/commit/d8f19ab9cc105a06edcf186acb85f4e5656754a3
> PYTHON-3837 Driver Container and Kubernetes Awareness

- .evergreen/perf.yml
- test/performance/perf_test.py
https://spruce.mongodb.com/version/654a64ec850e61e18d5825fe/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-4033 Address perf test UserWarning

- test/srv_seedlist/load-balanced/loadBalanced-directConnection.json
- test/srv_seedlist/load-balanced/loadBalanced-true-txt.json
- test/srv_seedlist/load-balanced/srvMaxHosts-zero-txt.json
- test/srv_seedlist/load-balanced/srvMaxHosts-zero.json
- test/srv_seedlist/replica-set/direct-connection-false.json
- test/srv_seedlist/replica-set/encoded-userinfo-and-db.json
- test/srv_seedlist/replica-set/loadBalanced-false-txt.json
- test/srv_seedlist/replica-set/longer-parent-in-return.json
- test/srv_seedlist/replica-set/one-result-default-port.json
- test/srv_seedlist/replica-set/one-txt-record-multiple-strings.json
- test/srv_seedlist/replica-set/one-txt-record.json
- test/srv_seedlist/replica-set/srv-service-name.json
- test/srv_seedlist/replica-set/srvMaxHosts-equal_to_srv_records.json
- test/srv_seedlist/replica-set/srvMaxHosts-greater_than_srv_records.json
- test/srv_seedlist/replica-set/srvMaxHosts-less_than_srv_records.json
- test/srv_seedlist/replica-set/srvMaxHosts-zero-txt.json
- test/srv_seedlist/replica-set/srvMaxHosts-zero.json
- test/srv_seedlist/replica-set/two-results-default-port.json
- test/srv_seedlist/replica-set/two-results-nonstandard-port.json
- test/srv_seedlist/replica-set/txt-record-with-overridden-ssl-option.json
- test/srv_seedlist/replica-set/txt-record-with-overridden-uri-option.json
- test/srv_seedlist/replica-set/uri-with-admin-database.json
- test/srv_seedlist/replica-set/uri-with-auth.json
- test/srv_seedlist/sharded/srvMaxHosts-equal_to_srv_records.json
- test/srv_seedlist/sharded/srvMaxHosts-greater_than_srv_records.json
- test/srv_seedlist/sharded/srvMaxHosts-less_than_srv_records.json
- test/srv_seedlist/sharded/srvMaxHosts-zero.json
- test/test_dns.py
Implements [PYTHON-3170](https://jira.mongodb.org/browse/PYTHON-3170).
> PYTHON-3170 Run ping command in SRV spec tests

- pyproject.toml
Passing [builds](https://spruce.mongodb.com/version/655232fdc9ec445c352f3b5d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
> PYTHON-4039 Handle more warnings in tests

- doc/changelog.rst
(cherry picked from commit 9c45ef808a7e3e69479fb2edf664e1d4adc7b02f)
> PYTHON-4043 [v4.6] Add changelog entry for 4.6.1

- .github/workflows/release-python.yml
- RELEASE.md
- pyproject.toml
Here's a passing build on my fork: https://github.com/blink1073/mongo-python-driver/actions/runs/7023293310?pr=3
> PYTHON-4045 Use PyPI Trusted Publishing

- test/test_database.py
https://jira.mongodb.org/browse/PYTHON-4087
> PYTHON-4087 Flush writes before testing validate with background=True

- test/connection_monitoring/pool-clear-interrupting-pending-connections.json
https://jira.mongodb.org/browse/PYTHON-4156
> PYTHON-4156 Increase interruptInUseConnections timeout to fix flaky test

- pymongo/logger.py
PYTHON-4223 Fixes test.test_command_logging.TestCommandLoggingServiceId.test_command_log_messages_include_serviceId_when_in_LB_mode.
> PYTHON-4223 Log serviceId as hex string

- .evergreen/config.yml
- .github/CODEOWNERS
- .github/reviewers.txt
Depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/412
> PYTHON-4243 Use GitHub App to Auto Assign Reviewer

- pymongo/database.py
https://jira.mongodb.org/browse/PYTHON-4282
> PYTHON-4282 Stop using filemd5 in docs example for db.command

- .evergreen/config.yml
- pymongo/_azure_helpers.py
Depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/418
> PYTHON-3467 Use client_id instead of object_id for Azure username

- bson/_cbsonmodule.c
- pymongo/_cmessagemodule.c
https://jira.mongodb.org/browse/PYTHON-4285
> PYTHON-4285 More consistent PyModule_GetState checks

- bson/_cbsonmodule.c
https://jira.mongodb.org/browse/PYTHON-4305
> PYTHON-4305 Fix bson size check

- pymongo/operations.py
- test/test_index_management.py
https://jira.mongodb.org/browse/PYTHON-4332
> PYTHON-4332 create_search_index only sends "type" field when provided

- test/performance/perf_test.py
https://jira.mongodb.org/browse/PYTHON-4325
> PYTHON-4325 Add multi-threaded benchmarks for Find and RunCommand

- test/test_transactions_unified.py
https://jira.mongodb.org/browse/PYTHON-4361
> PYTHON-4361 Skip transactions tests on MMAPv1

- test/connection_logging/connection-logging.json
- test/connection_logging/connection-pool-options.json
- test/connection_monitoring/pool-checkout-maxConnecting-is-enforced.json
- test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-4362
> PYTHON-4362 Resync CMAP tests

- test/test_discovery_and_monitoring.py
https://jira.mongodb.org/browse/PYTHON-4334
> PYTHON-4334 Fix test_heartbeat_start_ordering, ensure TCPServer starts before client

- pymongo/bulk.py
```python
>>> client.test.foo.insert_many(data)
File "<stdin>", line 1, in <module>
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/_csot.py", line 108, in csot_wrapper
return func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/collection.py", line 742, in insert_many
blk.execute(write_concern, session, _Op.INSERT)
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/bulk.py", line 595, in execute
return self.execute_command(generator, write_concern, session, operation)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/bulk.py", line 462, in execute_command …
```
> PYTHON-2048 Improve error message for bulk_write failures due to unsupported storage enginge

- pyproject.toml
Update `pyproject.toml`'s source url.
> fix: update `pyproject.toml` project source url

- test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-4398
> PYTHON-4398 Close mongos test clients to avoid thread build up

- pymongo/mongo_client.py
(cherry picked from commit 2210f74002663bee1c7bebc4953cd363824e02d5)
Backport to v4.7.
> PYTHON-4473 Optimize find/aggregate/command by avoiding duplicate calls to _get_topology (#1652)

- .github/workflows/codeql.yml
> PYTHON-4384 [v4.7] Add Custom CodeQL Scanning

- doc/changelog.rst
- pymongo/topology.py
- test/server_selection_logging/operation-id.json
- test/server_selection_logging/replica-set.json
- test/server_selection_logging/sharded.json
- test/server_selection_logging/standalone.json
https://jira.mongodb.org/browse/PYTHON-4261
> PYTHON-4261 Reduce verbosity of "Waiting for suitable server to become available" log message

- pymongo/mongo_client.py
Backport of https://github.com/mongodb/mongo-python-driver/pull/1673
> PYTHON-4347 [v4.8] Improve performance by only calling get_topology once

- pymongo/asynchronous/mongo_client.py
- pymongo/asynchronous/pool.py
- pymongo/synchronous/mongo_client.py
- pymongo/synchronous/pool.py
These changes were overwritten or not correctly rebased by the async PyMongo beta PR.
> PYTHON-4348 PYTHON-4455 Fix missing changes from async beta merge

- test/connection_string/test/valid-warnings.json
For https://github.com/mongodb/specifications/pull/1602
> PYTHON-4463 Add missing data in connection string test

- .evergreen/config.yml
- test/__init__.py
- test/test_auth.py
- test/test_client.py
- test/test_connection_monitoring.py
- test/test_database.py
(cherry picked from commit 2b03001)
> PYTHON-4509 [v4.8] Update to FIPS host with Python 3.8 binary

- pymongo/pool.py
- test/test_logger.py
(cherry picked from commit ff1d903bf2cc2036f398f7b873993a2614a987de)
> PYTHON-4499 [v4.8] Log pymongo.connection at DEBUG without EventListeners

- pymongo/asynchronous/encryption.py
- pymongo/synchronous/encryption.py
https://jira.mongodb.org/browse/PYTHON-4527
Related to https://github.com/mongodb/libmongocrypt/pull/846
> PYTHON-4527 Opt into range V2 encryption

- doc/changelog.rst
- setup.py
https://jira.mongodb.org/browse/PYTHON-4507
> PYTHON-4507 [v4.8] pip>=21.3 is required for editable installs

- pymongo/common.py
- test/test_topology.py
https://jira.mongodb.org/browse/PYTHON-4524
> PYTHON-4524 Bump maxWireVersion for MongoDB 8.0

- README.md
- doc/changelog.rst
https://jira.mongodb.org/browse/PYTHON-4524
> PYTHON-4524 Document support for MongoDB 8.0

- doc/changelog.rst
- pymongo/asynchronous/encryption.py
- pymongo/synchronous/encryption.py
https://jira.mongodb.org/browse/PYTHON-4531
> PYTHON-4531 Add back RANGEPREVIEW

- pymongo/asynchronous/database.py
- pymongo/asynchronous/encryption.py
- pymongo/synchronous/database.py
- pymongo/synchronous/encryption.py
https://jira.mongodb.org/browse/PYTHON-4536
> PYTHON-4536 Cleanup param doc strings

- CONTRIBUTING.md
- tox.ini
https://jira.mongodb.org/browse/PYTHON-4526
> PYTHON-4526 DRIVERS_TOOLS needs to be set for encryption tests

- .github/workflows/release-python.yml
- .pre-commit-config.yaml
- pymongo/pyopenssl_context.py
(cherry picked from commit afd0b6f84c821f7bbafb698c4c9c784a3f400470)
> PYTHON-4541 [v4.8] Add attestations for Python Releases

- gridfs/asynchronous/grid_file.py
- gridfs/synchronous/grid_file.py
- pymongo/asynchronous/command_cursor.py
- pymongo/asynchronous/cursor.py
- pymongo/synchronous/command_cursor.py
- pymongo/synchronous/cursor.py
- test/asynchronous/test_cursor.py
- test/test_cursor.py
This optimization is showing improvement of between 70%-120% compared to the naive `to_list` implementation.
> PYTHON-4549 - Optimize Cursor.to_list

- .evergreen/resync-specs.sh
- test/read_write_concern/operation/default-write-concern-2.6.json
- test/read_write_concern/operation/default-write-concern-3.2.json
- test/read_write_concern/operation/default-write-concern-3.4.json
- test/read_write_concern/operation/default-write-concern-4.2.json
- test/test_read_write_concern_spec.py
- test/test_retryable_reads_unified.py
Note to reviewer: only the python file changes need to be reviewed.
> PYTHON-4267 Convert read/write concern spec tests to unified test format

- test/discovery_and_monitoring/unified/serverMonitoringMode.json
[PYTHON-4605](https://jira.mongodb.org/browse/PYTHON-4605)
POC for https://github.com/mongodb/specifications/pull/1626
> PYTHON-4605 Test serverMonitoringMode=poll waits after a successful heartbeat

- .evergreen/config.yml
- .evergreen/run-azurekms-fail-test.sh
- .evergreen/run-azurekms-test.sh
- .evergreen/run-gcpkms-test.sh
- .evergreen/run-tests.sh
- .evergreen/setup-encryption.sh
> PYTHON-4601 Address Azure KMS and GCP KMS setup failures

- test/__init__.py
- test/asynchronous/__init__.py
- test/csot/change-streams.json
- test/csot/close-cursors.json
- test/csot/command-execution.json
- test/csot/convenient-transactions.json
- test/csot/deprecated-options.json
- test/csot/error-transformations.json
- test/csot/global-timeoutMS.json
- test/csot/legacy-timeouts.json
- test/csot/non-tailable-cursors.json
- test/csot/override-operation-timeoutMS.json
- test/csot/retryability-legacy-timeouts.json
- test/csot/sessions-inherit-timeoutMS.json
- test/csot/sessions-override-operation-timeoutMS.json
- test/csot/sessions-override-timeoutMS.json
- test/csot/tailable-awaitData.json
- test/csot/tailable-non-awaitData.json
- test/discovery_and_monitoring/unified/hello-command-error.json
- test/discovery_and_monitoring/unified/hello-network-error.json
- test/discovery_and_monitoring/unified/interruptInUse-pool-clear.json
- test/discovery_and_monitoring/unified/minPoolSize-error.json
- test/load_balancer/cursors.json
- test/load_balancer/sdam-error-handling.json
- test/load_balancer/transactions.json
- test/test_pooling.py
- test/test_streaming_protocol.py
https://jira.mongodb.org/browse/PYTHON-4396
> PYTHON-4396 Unskip failCommand+appName tests on MongoDB 4.4.7+

- test/asynchronous/test_cursor.py
- test/test_cursor.py
PYTHON-4643
The explanation is that `max_await_time_ms(1)` interrupts the command before it can read the given document. To have the test run both fast and correctly we need to run to_list repeatedly in this test until we see the document we're expecting.
> PYTHON-4643 Fix test_to_list_tailable

- .github/workflows/test-python.yml
> PYTHON-4652 Remove duplicate async tests in Github Actions

- test/asynchronous/test_client_bulk_write.py
- test/test_client_bulk_write.py
[PYTHON-4641](https://jira.mongodb.org/browse/PYTHON-4641)
> PYTHON-4641 Fix failure in async version of client bulk CSOT test

- .evergreen/config.yml
- test/performance/perf_test.py
[PYTHON-4578](https://jira.mongodb.org/browse/PYTHON-4578)
> PYTHON-4578 Benchmark collection and client bulk write

- .github/workflows/test-python.yml
- doc/api/pymongo/asynchronous/mongo_client.rst
- doc/api/pymongo/mongo_client.rst
- doc/changelog.rst
- doc/examples/client_bulk.rst
- doc/examples/index.rst
- pymongo/asynchronous/mongo_client.py
- pymongo/errors.py
- pymongo/synchronous/mongo_client.py
[PYTHON-4630](https://jira.mongodb.org/browse/PYTHON-4630)
> PYTHON-4630 Add documentation for MongoClient.bulk_write

- pymongo/message.py
- test/asynchronous/test_client_bulk_write.py
- test/test_client_bulk_write.py
[PYTHON-4666](https://jira.mongodb.org/browse/PYTHON-4666)
> PYTHON-4666 Fix handling of large documents in client.bulk_write

- doc/examples/client_bulk.rst
- pymongo/asynchronous/client_bulk.py
- pymongo/message.py
- pymongo/synchronous/client_bulk.py
- test/asynchronous/test_client_bulk_write.py
- test/performance/perf_test.py
- test/test_client_bulk_write.py
[PYTHON-4668](https://jira.mongodb.org/browse/PYTHON-4668)
> PYTHON-4668 Improve performance of client.bulk_write

- bson/__init__.py
> PYTHON-4712 Improve BSON encoding/decoding docs

- test/__init__.py
- test/asynchronous/__init__.py
PYTHON-4794 Start running IPv6 tests again
> PYTHON-4794 Start running IPv6 tests again

- doc/async-tutorial.rst
PYTHON-4801 Add beta warning to async tutorial
> PYTHON-4801 Add beta warning to async tutorial

- doc/changelog.rst
Cherry-pick of 2ab8a0eae0e5112770d65a9512a6c85e18905d32
> PYTHON-4812 Update changelog for 4.9.2 and 4.9.1 [master]

- .evergreen/config.yml
Requires https://github.com/mongodb-labs/drivers-evergreen-tools/pull/517
> PYTHON-4818 Use OCSP Scripts from Drivers-Tools

- THIRD-PARTY-NOTICES
PYTHON-4873 Remove bson-stdint-win32.h from THIRD-PARTY-NOTICES
> PYTHON-4873 Remove bson-stdint-win32.h from THIRD-PARTY-NOTICES

- test/server_selection_logging/operation-id.json
- test/server_selection_logging/replica-set.json
- test/server_selection_logging/sharded.json
- test/server_selection_logging/standalone.json
Reverts mongodb/mongo-python-driver#1935
> Revert "PYTHON-4765 Resync server-selection spec"

- .evergreen/config.yml
- .evergreen/scripts/generate_config.py
Before: 70 tasks across 70 build variants
After: 15 tasks across 15 build variants
> PYTHON-4878 Use shrub.py for load balancer tests

- .evergreen/config.yml
- .evergreen/scripts/generate_config.py
Before: 432 tasks across 16 build variants
After: 36 tasks across 4 build variants
Patch [build](https://spruce.mongodb.com/version/6712caa76a74cb0007080b3a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
> PYTHON-4889 Use shrub.py for green framework tests

- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/scripts/generate_config.py
Before: 2271 tasks across 120 build variants
After: 1481 tasks across 121 build variants
> PYTHON-4910 Add server tasks that use both sync and async

- .evergreen/config.yml
- .evergreen/scripts/generate_config.py
- pymongo/asynchronous/mongo_client.py
- pymongo/asynchronous/monitor.py
- pymongo/asynchronous/pool.py
- pymongo/network_layer.py
- pymongo/synchronous/mongo_client.py
- pymongo/synchronous/monitor.py
- pymongo/synchronous/pool.py
- test/__init__.py
- test/asynchronous/__init__.py
- test/asynchronous/test_auth_spec.py
- test/asynchronous/test_change_stream.py
- test/asynchronous/test_client.py
- test/asynchronous/test_connection_logging.py
- test/asynchronous/test_connections_survive_primary_stepdown_spec.py
- test/asynchronous/test_create_entities.py
- test/asynchronous/test_crud_unified.py
- test/asynchronous/test_encryption.py
- test/asynchronous/unified_format.py
- test/asynchronous/utils_spec_runner.py
- test/test_connections_survive_primary_stepdown_spec.py
- test/test_create_entities.py
- test/unified_format.py
- test/utils_spec_runner.py
This reverts commits `2d98fb1f8e0aa079479764ad15661136b136e05c` and `cd69b3627bd916da4cd5900fd5d986a533764746`.
> Revert Fix test failures commits

- test/asynchronous/unified_format.py
- test/asynchronous/utils_spec_runner.py
- test/unified_format.py
- test/utils_spec_runner.py
PYTHON-4980 Ignore network error on killAllSessions
> PYTHON-4980 Ignore network error on killAllSessions

- test/asynchronous/unified_format.py
- test/unified_format.py
Build: https://spruce.mongodb.com/version/67505e4a794c34000700ff97/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5004 Fix handling of TEST_PATH

- .evergreen/sync-spawn-host.sh
Follow up to #2036 to ensure the repo is synced before starting to watch files.
> PYTHON-5016 Fix initial sync in spawn host script

- .evergreen/generated_configs/variants.yml
- .evergreen/scripts/generate_config.py
Passing build: https://spruce.mongodb.com/version/6777cbdcf40bb60007da4f70/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-4754 Add gevent test for Python 3.13

- test/transactions-convenient-api/unified/commit-retry.json
- test/transactions-convenient-api/unified/commit-writeconcernerror.json
- test/transactions/unified/findOneAndReplace.json
- test/transactions/unified/findOneAndUpdate.json
- test/transactions/unified/mongos-recovery-token.json
- test/transactions/unified/pin-mongos.json
- test/transactions/unified/retryable-commit.json
- test/transactions/unified/write-concern.json
PYTHON-5042 Resync transaction spec tests
Testing for DRIVERS-3081.
> PYTHON-5042 Resync transaction spec tests

- sbom.json
- fixes invalid JSON in the SBOM
> Fix invalid JSON in SBOM

- doc/changelog.rst
- pymongo/asynchronous/topology.py
- pymongo/synchronous/topology.py
https://jira.mongodb.org/browse/PYTHON-5155
I'm working on getting a stable dochub link for this too but for now I've updated it to the new page + anchor.
> PYTHON-5155 Fix FAQ link for fork safety

- test/connection_string/test/valid-options.json
- test/connection_string/test/valid-warnings.json
Testing for https://github.com/mongodb/specifications/pull/1760
> DRIVERS-2915 Add ENVIRONMENT auth mechanism property to test URIs

- .github/workflows/dist.yml
- .github/workflows/test-python.yml
(cherry picked from commit b4e32a1)
> PYTHON-5131 [v4.11] Migrate off of Ubuntu 20.04 GitHub Actions Runners

- .evergreen/scripts/setup_tests.py
- pyproject.toml
- uv.lock
Passing build: https://spruce.mongodb.com/version/67e2d8dedbb6920007ffc617/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5232 Fix aws lambda test setup

- .evergreen/generated_configs/tasks.yml
- .evergreen/generated_configs/variants.yml
- .evergreen/scripts/generate_config.py
Passing build: https://spruce.mongodb.com/version/67e58386e3383200074f544e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Before: 5 variants, 3 tasks each
After: 1 variant, 15 tasks
> PYTHON-5234 Clean up load balancer variants

- .evergreen/utils.sh
- test/auth_oidc/test_auth_oidc.py
Passing build: https://spruce.mongodb.com/version/67ebee944fc4ae0007f0ab86/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5255 Fix OIDC allowed_hosts test

- doc/changelog.rst
- pymongo/__init__.py
- test/test_default_exports.py
(cherry picked from commit e6a4a7145eccb0b6c76c84aa539f29b40f3424b3)
> PYTHON-5310 [v4.12] Fix uri_parser AttributeError when used directly (#2283)

- pyproject.toml
- Remove URL
- Match GitHub project description
> PYTHON-5364 Update package description

- pymongo/asynchronous/auth_oidc.py
- pymongo/asynchronous/cursor.py
- pymongo/asynchronous/helpers.py
- pymongo/synchronous/auth_oidc.py
- pymongo/synchronous/cursor.py
- test/asynchronous/test_auth_oidc.py
- test/asynchronous/test_auth_spec.py
- test/test_auth_oidc.py
- test/test_auth_spec.py
- tools/synchro.py
Master run of OIDC: https://spruce.mongodb.com/version/68372e828ed7030007313c7c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC (has failing tests)
PR run of OIDC: https://spruce.mongodb.com/version/6837256d869ae60007f5d7dc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
> PYTHON-5394 - Add native async support for OIDC

- README.md
Add mention of SemVer in adherence to [DRIVERS-3105](https://jira.mongodb.org/browse/). We already mention this in our [ReadTheDocs](https://pymongo.readthedocs.io/en/4.11/compatibility-policy.html)
> DRIVERS-3105: Update README.md to add mention of SemVer adherence
