mongodb/mongo-python-driver

pymongo/collection.py, pymongo/operations.py
Fix markup for Collation class in IndexModel documentation.
For https://jira.mongodb.org/browse/PYMODM-55
There was some confusion in PyMODM about how to create an index that used the "weights" property for a text index. The [PyMODM docs](https://pymodm.readthedocs.io/en/latest/api/index.html#pymodm.MongoModel) link to PyMongo's [IndexModel](http://api.mongodb.com/python/current/api/pymongo/operations.html#pymongo.operations.IndexModel). This links to [create_indexes](http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.create_indexes). From here, there's a dead end.
These changes link to the createIndexes command in the MongoDB manual, which provides a table showing all available options for the command. This also fixes some markup for the …
=> Link to createIndexes command from create_indexes documentation.

pymongo/cursor.py
only referencing `self.__collection.database` when actually needed
=> Slightly faster Cursor.next()

gridfs/grid_file.py
The program's current behavior will always call `collection.create_index(index)` regardless of whether this index exists or not, so when you use a mongo user which without `createIndex` privilege, you can't write to the `gridfs`, though those indexes are already created by admin.
=> Fix bug: SON object and list can not be compared

doc/_templates/layout.html, doc/conf.py, doc/pydoctheme/theme.conf
Need to check python 2.6 for the date
=> docs: add google tag

pymongo/uri_parser.py
The following one-character patch fixes the ugly looking message:
<pre>
pymongo.errors.InvalidURI: ("Invalid URI scheme: URI must begin with '%s' or '%s'", ('mongodb://', 'mongodb+srv://'))
</pre>
=> Use formatting operator to format error message

doc/tools.rst
* Mark some ORM-like layers as no longer maintained: MongoKit, MongoAlchemy, Minimongo, Manga
* Add testing driver: mongomock
* Add ORM-like layer: uMongo
=> Up-to-date tools documentation

pymongo/helpers.py, test/test_collection.py
It was previously possible to use a set to specify fields, but this is no longer being allowed due to new validation constraints.
It seems that the validation is being unnecessarily strict.  [PYTHON-946](https://jira.mongodb.org/browse/PYTHON-946) covered the relaxation of the validation to allow sequences; this trivial change extends that to sets as well.  (I'm presuming there was a good reason for not changing it to the more generic `collections.Collection`; otherwise, that would be a better fit.)
=> Allow fields to be a set

test/__init__.py, test/test_change_stream.py
Closes [PYTHON-1597](https://jira.mongodb.org/browse/PYTHON-1597)
This allows us to specify (with the help of a decorator on the `ClientContext`) the storage engine that the server must be running with for a given test to be executed.
Spec-tests introduced in [PYTHON-1565](https://jira.mongodb.org/browse/PYTHON-1565) can only be run when the server is using wired Tiger. These tests failed when the MMAPv1 engine was in use, resulting in [failures on evergreen](https://evergreen.mongodb.com/task/mongo_python_driver_tests_storage_engines__python_version~2.7_storage_engine~mmapv1_test_4.0_standalone_9b632c776c3ace91dd6fd71dd98164d77881f766_18_06_25_02_59_16).
I chose to use the `db.serverStatus()` command to obtain storage engine information because: 
1) other drivers already follow this …
=> ENH: add helper method to run tests on specific storage engines

.travis.yml
Looks like https://github.com/travis-ci/travis-ci/issues/943 was fixed.
https://github.com/travis-ci/travis-ci/issues/5485 isn't needed since we don't support Python 3.2 .
=> Remove Travis workarounds

test/test_collection.py
There's no need to project out the _id field in this test. I opened [SERVER-36598](https://jira.mongodb.org/browse/SERVER-36598) for the server bug.
=> PYTHON-1624 Fix failing $out test on MongoDB latest

doc/contributors.rst, pymongo/mongo_client.py
Hello, first time contributor here!
I was doing a little debugging on an old code of mine and started to read around the documentation available. To my surprise, MongoClient's docstring was set to 
```
A base class that provides attributes and methods common
to multiple pymongo classes.
SHOULD NOT BE USED BY DEVELOPERS EXTERNAL TO MONGODB.
```
Confused, I went on researching and found out that MongoClient inherits from a base class and does not provide a new docstring, cause the parent's docstring to be displayed.
=> Provide a docstring to MongoClient

pymongo/write_concern.py, test/test_write_concern.py
This would make errors like in this bug mongomock/mongomock#458 more readable.
=> Fix comparison of a WriteConcern object with None.

pymongo/pool.py
Current connection pool implementation is based upon python set() and prone to connection pool poisoning problem.
Python set() is unordered by definition. So each command executed withdraws random connection from pool, touching its last usage time. This scheme shows good result on persistent established loads, increasing number of connections to handle the load. But spikes of loads introduces pool poisoning problem. During the spikes of load connection pool creates new connection to handle the increased load (which is expected behavior), but when returning to normal levels connection pool cannot reduce amount of connections, because due to unordered set() commands passed to virtually all open connection, preventing them from expiration. So the amount of open connections is never decreased …
=> LIFO connection pool policy

pymongo/collection.py
Today I was implementing find_one_and_update, and I wanted to verify the behavior if no value was matched, but found the docs did not adequately document the behavior. I verified the behavior on MongoDB 3.6 and the latest pymongo and documented it here.
=> Document find_one_and_update return value on no match.

pymongo/uri_parser.py, test/test_uri_parser.py
I found this little snippet of code that supported some Python 2.4 behavior hanging around in the `uri_parser` module. I think we can safely remove it now.
=> Remove legacy Python 2.4 support code

test/test_transactions.py, test/transactions/bulk.json, test/transactions/error-labels.json, test/transactions/read-concern.json, test/transactions/transaction-options.json
Fix: properly skip tests that include 'skipReason'.
Revendor transaction spec tests at commit 367842f1ee4b80f75664a05c6b9d5b2498cf856d
=> PYTHON-1658 Test that transaction reads ignore db/collection readConcern

test/test_change_stream.py
I updated the test to pass on a replica set. Let's skip the test on sharded clusters for now while we wait for SPEC/SERVER changes to be decided.
=> PYTHON-1739 Skip failing change stream test on sharded clusters

pymongo/client_session.py, test/transactions/commit.json, test/transactions/error-labels.json, test/transactions/insert.json, test/transactions/retryable-abort.json, test/transactions/retryable-commit.json
Jira: https://jira.mongodb.org/browse/PYTHON-1730
This change makes Python use 'w':majority and 'wtimeout' according to the updated transaction spec: https://github.com/mongodb/specifications/blob/ba1b071/source/transactions/transactions.rst#majority-write-concern-is-used-when-retrying-committransaction
=> PYTHON-1730 Use w:majority when retrying commitTransaction

test/test_collection.py
Jira: https://jira.mongodb.org/browse/PYTHON-1766
Noticed while working on retryable reads because my local server was running slow and test_large_limit took over 30 seconds.
=> PYTHON-1766 Use insert_many to reduce test runtime

doc/examples/bulk.rst
Jira: https://jira.mongodb.org/browse/PYTHON-1767
=> PYTHON-1767 Ignore keyPattern/keyValue fields in doctest duplicate key error

bson/json_util.py
Fixes this warning from Python 3.8:
```
bson/json_util.py:702: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if doc['$minKey'] is not 1:
bson/json_util.py:711: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if doc['$maxKey'] is not 1:
```
=> Fix Python 3.8 SyntaxWarning: "is not" with a literal

pymongo/encryption.py, test/client-side-encryption/spec/aggregate.json, test/client-side-encryption/spec/basic.json, test/client-side-encryption/spec/bulk.json, test/client-side-encryption/spec/bypassAutoEncryption.json, test/client-side-encryption/spec/count.json, test/client-side-encryption/spec/countDocuments.json, test/client-side-encryption/spec/delete.json, test/client-side-encryption/spec/distinct.json, test/client-side-encryption/spec/explain.json, test/client-side-encryption/spec/find.json, test/client-side-encryption/spec/findOneAndDelete.json, test/client-side-encryption/spec/findOneAndReplace.json, test/client-side-encryption/spec/findOneAndUpdate.json, test/client-side-encryption/spec/getMore.json, test/client-side-encryption/spec/insert.json, test/client-side-encryption/spec/keyAltName.json, test/client-side-encryption/spec/localKMS.json, test/client-side-encryption/spec/localSchema.json, test/client-side-encryption/spec/missingKey.json, test/client-side-encryption/spec/replaceOne.json, test/client-side-encryption/spec/types.json, test/client-side-encryption/spec/updateMany.json, test/client-side-encryption/spec/updateOne.json, test/test_encryption.py
Jira: https://jira.mongodb.org/browse/PYTHON-2012
This PR depends on https://github.com/mongodb/libmongocrypt/pull/65. I need to wait until the libmongocrypt changes are merged before running a patch build. The tests pass locally.
Changes:
- silence mongocryptd output
- Resync spec tests
- Add prose test for custom endpoint for create_data_key
- Update the prose test of Data key and double encryption to check command started events
- Document 'endpoint' support
- Document that create_data_key returns a Binary with UUID subtype.
The only part left is the changes to bulk write batching and bson command size limits which I will put up as a separate review.
=> PYTHON-2012 FLE GA changes

bson/__init__.py, doc/contributors.rst, test/test_bson.py
This is a cut at [bug 2061](https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-2061). I’m a little unsure about whether the test change I’ve done is the best way to do it—the solution I have seems…OK, but not ideal.
I’m open to any feedback about this. Thanks!
=> [PYTHON-2061] bson: check for negative entry size in read_file_iter.

.evergreen/config.yml
Collect crash dumps from mongo-orchestration. Minidumps are enabled by default on Windows. Core dumps need to be enabled in the current executing shell via ulimit.
=> PYTHON-2064 Collect crash dumps from mongo-orchestration

doc/examples/authentication.rst
There is a small typo in doc/examples/authentication.rst.
Should read overridden rather than overidden.
=> Fix simple typo: overidden -> overridden

README.rst, doc/index.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-9413
Remove all references to google groups from Python driver docs.
=> DOCSP-9413: replace references to google groups with community forums

test/__init__.py, test/test_client.py, test/test_dns.py, test/test_replica_set_client.py, test/test_ssl.py
Jira: https://jira.mongodb.org/browse/PYTHON-1852
This doesn't fix all the usages of `ssl_*` (eg in test_ssl.py) but does fix a large majority of them.
=> PYTHON-1852 Use TLS option names in test suite ClientContext

pymongo/mongo_client.py, test/test_examples.py, test/test_transactions.py
[PYTHON-2154](https://jira.mongodb.org/browse/PYTHON-2154) [PYTHON-2189](https://jira.mongodb.org/browse/PYTHON-2189) Remove 4.5 transaction test workarounds
Explanation: The StaleConfig change in PYTHON-2189 accidentally causes the test_transactions suite to ignore _any_ failed test because there was a missing `raise` statement. Now that we're no longer masking test failures, this test began to fail:
```
ERROR: test_transactions_mongos_recovery_token_commitTransaction_retry_succeeds_on_new_mongos (test.test_transactions.TestTransactions)
File "/Users/shane/git/mongo-python-driver/test/__init__.py", line 442, in wrap
return f(*args, **kwargs)
File …
```
=> PYTHON-2082 Unpin session after RetryableWriteErrors from commitTransaction

pymongo/pool.py, pymongo/pyopenssl_context.py
Jira: https://jira.mongodb.org/browse/PYTHON-2163
This change does two things. First it fixes a bug where we were incorrectly not wrapping pyOpenSSL connection errors from wrap_socket. For example, before this change:
```
>>> client = MongoClient(ssl=True, serverSelectionTimeoutMS=1000).admin.command('ping')
File "<stdin>", line 1, in <module>
File "/Users/shane/git/mongo-python-driver/pymongo/database.py", line 737, in command
read_preference, session) as (sock_info, slave_ok):
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
return next(self.gen)
File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", line 1322, in _socket_for_reads
server = self._select_server(read_preference, …
```
=> PYTHON-2163 Suppress ragged EOFs when using PyOpenSSL to match the stdlib

pymongo/__init__.py, pymongo/cursor.py
Jira: https://jira.mongodb.org/browse/PYTHON-2220
=> PYTHON-2220 Mention Atlas Search in documentation

doc/changelog.rst, gridfs/__init__.py, gridfs/grid_file.py, test/test_transactions.py
Jira: [PYTHON-2243](https://jira.mongodb.org/browse/PYTHON-2243)
=> PYTHON-2243 Raise informative error message when attempting a GridFS operation in a transaction

bson/codec_options.py, doc/faq.rst
PYTHON-2277 Remove UuidRepresentation DeprecationWarning
=> PYTHON-2292 Fix failing doctest due to UuidRepresentation

doc/api/pymongo/mongo_client.rst, doc/changelog.rst, pymongo/mongo_client.py, test/test_client.py, test/test_monitoring.py, test/test_session.py
Jira: https://jira.mongodb.org/browse/PYTHON-2165
=> PYTHON-2165 Deprecate MongoClient is_locked, fsync, and unlock helpers

pymongo/client_session.py, pymongo/mongo_client.py
Jira: https://jira.mongodb.org/browse/PYTHON-2256
=> PYTHON-2256 Document that a ClientSession cannot be used for multiple operations concurrently

pymongo/mongo_client.py, pymongo/topology.py, test/test_discovery_and_monitoring.py, test/test_topology.py
Jira: https://jira.mongodb.org/browse/PYTHON-1438
=> PYTHON-1438 Mark a server unknown when connection handshake fails with a network timeout error

bson/json_util.py, test/test_json_util.py
Note that we do not need to handle other `UuidRepresentation` values because `$uuid` fields in extended JSON contain the UUID in their canonical textual representation which is platform-independent and not affected by byte order.
=> PYTHON-2263 Respect UuidRepresentation.UNSPECIFIED when parsing $uuid fields

test/change_streams/change-streams-resume-whitelist.json
This just resyncs the spec tests. The change in resume behavior was merged in PYTHON-2143.
=> PYTHON-2315 Special case resuming change streams from CursorNotFound errors

pymongo/socket_checker.py
Jira: https://jira.mongodb.org/browse/PYTHON-2320
Jython poll bug: https://bugs.jython.org/issue2900
Calling poll() on a SSLSocket registered with POLLHUP causes the following AttributeError: 'SSLSocket' object has no attribute 'channel':
```
File "pymongo/socket_checker.py", line 57, in select
res = self._poller.poll(timeout * 1000)
File "/usr/local/Cellar/jython/2.7.2/libexec/Lib/_socket.py", line 592, in poll
result = self._handle_poll(partial(self.queue.poll, timeout_in_ns, TimeUnit.NANOSECONDS))
File "/usr/local/Cellar/jython/2.7.2/libexec/Lib/_socket.py", line 541, in _event_test
fd, event = self._event_test(notification)
File "/usr/local/Cellar/jython/2.7.2/libexec/Lib/_socket.py", line 541, in _event_test
if mask & POLLHUP and (notification.hangup or not …
```
=> PYTHON-2320 Use select instead of poll on Jython

pymongo/common.py, pymongo/mongo_client.py, test/discovery_and_monitoring_integration/connectTimeoutMS.json, test/test_client.py, test/test_session.py, test/test_streaming_protocol.py
PYTHON-2296 Test behavior of connectTimeoutMS=0 with streaming protocol
PYTHON-2311 Fix flaky streaming protocol test
Patch: https://evergreen.mongodb.com/version/5f129b4e850e614ba95578e7
=> PYTHON-2294 Resync SDAM spec tests to workaround slow elections Windows and macOS

bson/buffer.c
```
bson/buffer.c:36:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
36 | static void set_memory_error() {
|             ^~~~~~~~~~~~~~~~
```
Jira: https://jira.mongodb.org/browse/PYTHON-2331
=> PYTHON-2331 Fix set_memory_error complier warning

pymongo/monitor.py, pymongo/topology.py
PYTHON-2304 Ensure _RttMonitor closes socket
This PR fixes the two flaky tests described in PYTHON-2328 and PYTHON-2304.
For PYTHON-2328 we reset the connection pool in Topology.on_change. This not only resolves the race in test_pool_reset but also avoids the need to acquire the Topology lock a second time when processing a failed heartbeat.
=> PYTHON-2328 Reset the connection pool in Topology.on_change

pymongo/pool.py, pymongo/thread_util.py
Gevent patches the Lock class such that it can raise Timeout exceptions while waiting in .acquire()
When these raise, it can cause the pymongo thread_util.py:Semaphore to exit the acquire() function without releasing self._cond's lock. Changing to `with self._cond` guarantees release even if an exception is raised by gevent.
Also, in pool.py, when waiting for the lock for active sockets, this same condition could occur and cause self._socket_semaphore's lock to be lost.
=> PYTHON-2334: Fix gevent race condition

pymongo/thread_util.py, test/test_client.py
This is a follow on to: https://github.com/mongodb/mongo-python-driver/pull/472
Before the fixes this test would fail like this:
```
======================================================================
ERROR: test_gevent_timeout (test.test_client.TestMongoClientFailover)
File "/Users/shane/git/mongo-python-driver/test/test_client.py", line 1975, in test_gevent_timeout
self.assertIsNone(ct.get())
File "src/gevent/greenlet.py", line 769, in gevent._gevent_cgreenlet.Greenlet.get
File "src/gevent/greenlet.py", line 364, in gevent._gevent_cgreenlet.Greenlet._raise_exception
File "/Users/shane/git/mongo-python-driver/venv3.8/lib/python3.8/site-packages/gevent/_compat.py", line 65, in …
```
=> PYTHON-2334 Add regression test for gevent.Timeout compatibility

test/test_discovery_and_monitoring.py, test/utils.py
Add 60 second timeout for joining threads in SDAM tests.
=> PYTHON-2332 Skip threaded SDAM tests when cdecimal is monkey patched

bson/codec_options.py, bson/json_util.py, test/test_json_util.py
Open question: Should we throw an exception if the user tries to change the `JSONMode` via `with_options`?
=> PYTHON-2354 Add support for JSONOptions.with_options

.evergreen/run-tests.sh
There seems to be a bug in dnspython 2.0 related to SRV lookups. For now we should downgrade to `dnspython<2.0` to get the test suite green.
=> PYTHON-2362 Test with dnspython<2.0 to avoid timeouts

.evergreen/config.yml, doc/changelog.rst, setup.py, test/test_custom_types.py
This change adds testing for Python 3.9 and fixes:
```
[2020/09/10 20:55:18.185] FAIL [0.002s]: test_instantiation (test_custom_types.TestBSONTypeEnDeCodecs)
[2020/09/10 20:55:18.185] ----------------------------------------------------------------------
[2020/09/10 20:55:18.185] TypeError: Can't instantiate abstract class testcodec with abstract method transform_python
[2020/09/10 20:55:18.185] During handling of the above exception, another exception occurred:
[2020/09/10 20:55:18.185] Traceback (most recent call last):
[2020/09/10 20:55:18.185]   File "/data/mci/183724bc86e179ad6d136f6b74916c26/src/test/test_custom_types.py", line 270, in test_instantiation
[2020/09/10 20:55:18.185]     run_test(TypeEncoder, {'python_type': MyType,}, fail=True)
[2020/09/10 20:55:18.185]   File …
```
=> PYTHON-2262 Test Python 3.9 in Evergreen

.evergreen/build-mac.sh, .evergreen/config.yml
Tested here: https://evergreen.mongodb.com/version/5f5c16890305b97395debec5
Here are the new files:
```
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp27-cp27m-macosx_10_14_intel.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp34-cp34m-macosx_10_6_intel.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp35-cp35m-macosx_10_6_intel.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp36-cp36m-macosx_10_6_intel.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp37-cp37m-macosx_10_6_intel.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-cp38-cp38-macosx_10_9_x86_64.whl
[2020/09/12 00:32:00.273] pymongo-3.11.1.dev1-py2.7-macosx-10.14-intel.egg
```
=> PYTHON-2372 Build macOS releases in Evergreen

.evergreen/build-mac.sh, .evergreen/build-manylinux-internal.sh, .evergreen/build-manylinux.sh, .evergreen/build-windows.sh, .evergreen/config.yml, .evergreen/utils.sh
Tested here: https://evergreen.mongodb.com/version/5f61533de3c3314c4c6884ff
=> PYTHON-2345 Ensure release files can be installed

.evergreen/build-mac.sh
Tested here: https://evergreen.mongodb.com/version/5f6e5959d6d80a45fc929848
=> PYTHON-2375 Remove macos system python workaround for missing wheel package

pymongo/helpers.py, pymongo/network.py, pymongo/server.py, test/test_database.py
I've performed the following requests in the drivers ticket:
> - Audit the driver for uses of error messages to make decisions
> - For each error message, determine the server's related error code and check that first, falling back to error message matching to avoid breaking changes with old server versions.
>
> For example, the Python driver does an exact match on the error message "ns not found". It should attempt to match error code 26 first, matching the error message as a fallback. The fallback is necessary to avoid a backward breaking change with MongoDB 2.6 and 3.0 which do not return an error code.
I also removed the "db assertion failure" check which was removed by the server in MongoDB 2.5.
=> PYTHON-2342 Prefer checking error codes over error messages

test/retryable_writes/insertOne-serverErrors.json, test/test_retryable_writes.py
Two changes:
- PYTHON-2357 Specify error label in retryable writes test (simply resyncs the tests).
- PYTHON-2356 Add errorLabelsContain/errorLabelsOmit support to retryable writes tests (implemented by transforming the retryable write test into the transaction test format).
=> PYTHON-2357 Specify error label in retryable writes test

bson/_cbsonmodule.c
Tested using a slightly modified version of the user-provided repro script:
```
import gc
from typing import Any
from pymongo import MongoClient
from bson.codec_options import CodecOptions
from bson.codec_options import TypeCodec, TypeRegistry
def memory_report(prefix):
gc.collect()
rr = {}
for obj in gc.get_objects():
tt = type(obj)
if ('bson.codec_options.CodecOptions' in str(tt)):
refs = gc.get_referrers(obj)
print(tt)
print(len(refs))
rr[tt] = rr.get(tt, 0) + 1
print(prefix + ' memory report:')
for key in rr:
nn = rr[key]
print(f' {key}: {nn}')
class MyClass:
pass
class MyCodec(TypeCodec):  # type: ignore
@property
def python_type(self) -> Any:
return MyClass
def transform_python(self, value: Any) -> Any:
return value
@property
def bson_type(self) -> Any:
return int
def …
```
=> PYTHON-2382 Destroy codec options struct in _cbson._element_to_dict

pymongo/pool.py, test/cmap/connection-must-have-id.json, test/cmap/connection-must-order-ids.json, test/cmap/pool-checkin-destroy-closed.json, test/cmap/pool-checkin-destroy-stale.json, test/cmap/pool-checkin-make-available.json, test/cmap/pool-checkin.json, test/cmap/pool-checkout-connection.json, test/cmap/pool-checkout-multiple.json, test/cmap/pool-checkout-no-idle.json, test/cmap/pool-checkout-no-stale.json, test/cmap/pool-close-destroy-conns.json, test/cmap/pool-create-max-size.json, test/cmap/pool-create-min-size.json, test/cmap/wait-queue-timeout.json, test/test_cmap.py
This uncovered a minor oversight in our minPoolSize connection creation logic. We did create the connection but we did not ensure that the connection was authenticated. Connections created in the background (for minPoolSize) are now authenticated. This is a minor performance improvement (lower latency on first connection use).
=> PYTHON-2360 Ensure ConnectionCreatedEvents are emitted before ConnectionReadyEvents

pymongo/mongo_client.py, test/sessions/dirty-session-errors.json
This change fixes two issues:
1. PYTHON-2392 Implicit sessions should always be discarded after connection errors
1. PYTHON-2075 Add more sessions tests with more read and write commands
=> PYTHON-2392 Implicit sessions should always be discarded after connection errors

doc/faq.rst
While chasing down a configuration issue I noticed the docs refer to `maxIdleTime` but that doesn't seem to exist in the code, but `maxIdleTimeMS` does. This just updates the FAQ so no one else trips on this.
=> Changing maxIdleTime to maxIdleTimeMS

.evergreen/run-tests.sh
This reverts commit c54974067772f268a9a9dc6dbba0a490e6b8e842.
This should no longer be needed now that our toolchain installs dnspython<2.0.
=> Revert "PYTHON-2362 Use dnspython<2.0 to avoid timeouts (#484)"

doc/tools.rst
MincePy is an ODM built on top of pymongo using the data-mapper pattern.
Be great if you guys would be willing to include this in the list as I think it offers something quite different from most (if not all) of the other ODMs in that it doesn't require that users subclass from a common model class, which means that any arbitrary Python object can be made storable.  This is invaluable in situations when you don't own (i.e. they're not in your codebase) the types you want to save.
=> Added the mincePy ODM library to documented tools

.evergreen/config.yml, pymongo/encryption.py, pymongo/encryption_options.py, test/client-side-encryption/custom/azure-dek.json, test/client-side-encryption/custom/azure-gcp-schema.json, test/client-side-encryption/custom/gcp-dek.json, test/test_encryption.py
Depends on https://github.com/mongodb/libmongocrypt/pull/118
=> PYTHON-2371 Add Azure and GCP support for CSFLE

.evergreen/build-mac.sh
Patch: https://evergreen.mongodb.com/version/5fa5ac2f0305b945939ab269
=> PYTHON-2403 Add macOS Python 3.9 release automation

pymongo/errors.py, test/test_errors.py
For some background see my comment on the Jira ticket here: https://jira.mongodb.org/browse/PYTHON-2415?focusedCommentId=3476301&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3476301
=> PYTHON-2415 Support pickle in BulkWriteError

pymongo/monitor.py, pymongo/server_description.py, test/test_client.py
When the SDAM monitor check fails, a ServerDescription is created from
the exception. This exception is kept alive via the
ServerDescription.error field. Unfortunately, the exception's traceback
contains a reference to the previous ServerDescription. Altogether this
means that each consecutively failing check leaks memory by building an
ever growing chain of ServerDescription -> Exception -> Traceback ->
Frame -> ServerDescription -> ... objects.
This change breaks the chain and prevents the memory leak by clearing
the Exception's __traceback__, __context__, and __cause__ fields.
=> PYTHON-2433 Fix Python 3 ServerDescription/Exception memory leak

.evergreen/config.yml, .evergreen/run-mongodb-aws-test.sh, .evergreen/utils.sh
Tested here: https://evergreen.mongodb.com/version/5fb843b761837d105a7a3fa2
This change fixes this error:
```
[2020/11/12 23:45:52.296] Running command 'shell.exec' in "run aws auth test with assume role credentials" (step 4.1 of 8)
[2020/11/12 23:45:52.512] /usr/local/lib/python2.7/site-packages/virtualenv.py:1047: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
[2020/11/12 23:45:52.512]   import imp
[2020/11/12 23:45:52.559] Using base prefix '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9'
[2020/11/12 23:45:52.559] New python executable in /data/mci/d1de1a1943ca42ab82064dbabed0a5c2/src/mongovenv/bin/python3.9
[2020/11/12 23:45:52.559] Also creating executable in …
```
=> PYTHON-2431 Fix MONGODB-AWS auth tests on macOS

doc/faq.rst, pymongo/common.py, pymongo/pool.py, test/cmap/pool-checkout-maxConnecting-is-enforced.json, test/cmap/pool-checkout-maxConnecting-timeout.json, test/cmap/pool-checkout-returned-connection-maxConnecting.json, test/test_cmap.py, test/test_pooling.py, test/utils_spec_runner.py
At most 2 connections can be in the pending state per connection pool.
The pending state covers all the work required to setup a new connection
including TCP, TLS, and MongoDB authentication. For example, if two
threads are currently creating connections, a third thread will wait for
either an existing connection to be checked back into the pool or for
one of the two threads to finish creating a connection.
The change reduces the likelihood of connection storms and improves the
driver's ability to reuse existing connections.
=> PYTHON-2363 Rate limit new connection creations via maxConnecting

pymongo/socket_checker.py, test/test_pooling.py
This PR uses https://github.com/mongodb/mongo-python-driver/pull/526 as a base and then adds a regression test.
=> PYTHON-2443 Fix TypeError when pyOpenSSL socket has timeout of None (with regression test)

test/cmap/pool-checkout-maxConnecting-is-enforced.json, test/test_cmap.py
Tested here: https://evergreen.mongodb.com/version/5fc6afbdd1fe0771a322eaec
And a second time for good measure: https://evergreen.mongodb.com/version/5fc6edb032f417146256a3aa
=> PYTHON-2447 Fix race in CMAP maxConnecting test

test/test_streaming_protocol.py
Implements: https://github.com/mongodb/specifications/pull/879/
=> PYTHON-2457 Test that clients wait 500ms between failed heartbeat checks

pymongo/helpers.py, test/test_retryable_writes.py
This change will be backported to 3.11 and 3.12 branches
=> PYTHON-2452 Ensure command-responses with RetryableWriteError label are retried on MongoDB 4.4+

.evergreen/config.yml, .evergreen/run-ocsp-tests.sh, .evergreen/run-tests.sh, .evergreen/test-encryption-requirements.txt, .evergreen/utils.sh
This change does the following:
- PYTHON-2366  Adds Python 3.9 testing for OCSP+FLE.
- PYTHON-2449 Fixes PyPy testing by migrating from RHEL 6.2/Ubuntu 16 to Debian 9.2. The former have OpenSSL 1.0.1/1.0.2 while debian has 1.1.0. This works around the pyopenssl connect errors described in https://github.com/pyca/pyopenssl/issues/981 .
- PYTHON-2449 Fixes Windows test setup failures caused by outdated pip versions being unable to install cryptography wheels. The fix is to upgrade pip.
I'm planning to backport these changes which is why I had to change PyPy 2 testing. 
Tested here: https://evergreen.mongodb.com/version/5fd929ef57e85a0b36c0ec64
=> PYTHON-2366 Test OCSP+FLE with Python 3.9

pymongo/collection.py, pymongo/database.py, pymongo/mongo_client.py, test/test_client.py, test/test_collection.py, test/test_database.py
=> PYTHON-2466 Make pymongo client, database and collection objects hashable.

doc/changelog.rst, doc/index.rst, doc/migrate-to-pymongo4.rst
Most of the verbiage I copied from migrate-to-pymongo3.rst. Going forward we should update this guide whenever we make a breaking change in 4.0.
=> PYTHON-2388 Begin PyMongo 4.0 migration guide

doc/api/pymongo/database.rst, doc/changelog.rst, doc/migrate-to-pymongo4.rst, pymongo/database.py, test/test_database.py
Depends on https://github.com/mongodb/mongo-python-driver/pull/540.
=> PYTHON-1316 Remove Database.eval and database.SystemJS

RELEASE.rst
Very small PR to adjust Shane's change to the release checklist - instead of the DOCS project, the docs team would prefer we file to DOCSP (private by default). My fault for a non-specific Jira ticket!
=> PYTHON-2455 Update release checklist to include step to file docs ticket outlining compatibility changes/lack thereof

.evergreen/config.yml, test/versioned-api/crud-api-version-1-strict.json, test/versioned-api/test-commands-deprecation-errors.json, test/versioned-api/transaction-handling.json
This change:
- adds testing against a server started with acceptAPIVersion2.
- skips the failing $listLocalSessions test related to DRIVERS-1505.
- resyncs the spec test added in DRIVERS-1504.
=> PYTHON-2482 Test Versioned API with a server started with acceptAPIVersion2

.evergreen/build-mac.sh, .evergreen/build-manylinux-internal.sh, .evergreen/build-manylinux.sh, .evergreen/build-windows.sh, .evergreen/config.yml, .evergreen/utils.sh
This change also removes `git_tag_only:true` so that we can test our changes to the release build process without pushing a test-only tag and without manually editing the config. I haven't changed the evg project config so when a tag is pushed we'll have the same behavior as before (the release task will run automatically in a new build).
This change also stops building `.egg` files (https://jira.mongodb.org/browse/PYTHON-1300).
=> PYTHON-2502 Remove Python 2.7 from release scripts

.evergreen/build-manylinux.sh
Minor cleanup I noticed while doing the 3.11.3 release.
=> PYTHON-1974 Remove manylinux containers only needed for 3.4

pymongo/topology.py, test/discovery_and_monitoring/errors/write_errors_ignored.json, test/test_discovery_and_monitoring.py
This change implements: SPEC-1759
=> PYTHON-2543 Do not mark a server unknown from a "writeErrors" response

pymongo/network.py, pymongo/pool.py, test/test_client.py
Before this change:
```python
File "/Users/shane/git/mongo-python-driver/test/test_client.py", line 1579, in test_network_error_message
client.pymongo_test.test.find_one({})
File "/Users/shane/git/mongo-python-driver/pymongo/collection.py", line 1261, in find_one
for result in cursor.limit(-1):
File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 1199, in next
if len(self.__data) or self._refresh():
File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 1120, in _refresh
self.__send_message(q)
File "/Users/shane/git/mongo-python-driver/pymongo/cursor.py", line 995, in __send_message
response = client._run_operation_with_response(
File "/Users/shane/git/mongo-python-driver/pymongo/mongo_client.py", line 1271, in _run_operation_with_response
return …
```
=> PYTHON-2596 Include host in error message when connection is closed

pymongo/helpers.py, test/discovery_and_monitoring/errors/non-stale-topologyVersion-greater-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/non-stale-topologyVersion-missing-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/non-stale-topologyVersion-proccessId-changed-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/post-42-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/pre-42-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/prefer-error-code.json, test/discovery_and_monitoring/errors/stale-generation-afterHandshakeCompletes-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/stale-generation-afterHandshakeCompletes-network.json, test/discovery_and_monitoring/errors/stale-generation-afterHandshakeCompletes-timeout.json, test/discovery_and_monitoring/errors/stale-generation-beforeHandshakeCompletes-LegacyNotPrimary.json, test/discovery_and_monitoring/errors/stale-generation-beforeHandshakeCompletes-network.json, test/discovery_and_monitoring/errors/stale-topologyVersion-LegacyNotPrimary.json
Add 10058 as a "not master" error code to account for MongoDB<=3.2 errors.
This change implements: https://github.com/mongodb/specifications/pull/920
=> PYTHON-2544 Do not check error messages when an error code is present

doc/changelog.rst, setup.py
FYI I will open a separate PR to backport this to the v3.12 branch.
=> PYTHON-2583 Bump minimum required PyMongoCrypt version to 1.1.0

bson/raw_bson.py
Adds an Example for usage of RawBSONDocuments with the use case of moving documents across different collections
=> PYTHON-1359: Add Example for RawBSONDocument

pymongo/pool.py, test/test_client.py
PYTHON-2616 Fix test_network_error_message when TLS is enabled.
=> PYTHON-2615 Reinstate TLS network timeout workaround due to eventlet

pymongo/collection.py, test/test_collection.py
Changed type checking from `abc.Iterable` to `abc.Sequence` in order to better match 'list-like' types
```
TypeError                                 
Traceback (most recent call last)
<ipython-input-6-9084eaf77999> in <module>
----> 1 client.test.test.insert_many(RawBSONDocument(bson.BSON.encode({'_id':2})))
~/mongo-python-driver/pymongo/collection.py in insert_many(self, documents, ordered, bypass_document_validation, session)
688         """
689         if not isinstance(documents, abc.Sequence) or not documents:
--> 690             raise TypeError("documents must be a non-empty list")
691         inserted_ids = []
692         def gen():
TypeError: documents must be a non-empty list
```
=> PYTHON-1690: Fix error message when insert_many is given a single RawBSONDocument instead of a list

doc/api/pymongo/index.rst, doc/api/pymongo/mongo_client.rst, doc/api/pymongo/server_description.rst, doc/api/pymongo/topology_description.rst, doc/changelog.rst, pymongo/mongo_client.py, test/test_client.py
Add a property for accessing current topology description in MongoClient.
Open Questions:
How to test these changes/run locally?
=> PYTHON-2480: Add MongoClient helper to access the current TopologyDescription

bson/_cbsonmodule.c
https://jira.mongodb.org/browse/PYTHON-2630
=> PYTHON-2630 Statically initialize Py_buffer to avoid false positives in Coverity

bson/_cbsonmodule.c, test/test_bson.py
https://jira.mongodb.org/browse/PYTHON-2631
=> PYTHON-2631 Add missing error message to InvalidBSON error

pymongo/topology.py, test/pymongo_mocks.py, test/test_client.py, test/test_cmap.py
Fixes a noisy OperationFailure: Authentication failed error.
Do not attempt to create unneeded connections to arbiters, ghosts,
hidden members, or unknown members.
=> PYTHON-2634 Only update pools for data-bearing servers

pymongo/mongo_client.py, test/test_client.py
Switch from common dictionary to CaseInsensitiveDictionary to fix `cased_key` attribute error.
=> PYTHON-2397: MongoClient(ssl=True, tls=False) fails with an AttributeError

pymongo/daemon.py
Error message after this change:
```
/Users/pmital/Developer/mongo-python-driver/pymongo/daemon.py:137: RuntimeWarning: Failed to start mongocryptd: is it on your $PATH?
Original exception: [Errno 2] No such file or directory: 'mongocryptd': 'mongocryptd'
_silence_resource_warning(_spawn(sys.argv[1:]))
/Users/pmital/Developer/mongo-python-driver/pymongo/daemon.py:137: RuntimeWarning: Failed to start mongocryptd: is it on your $PATH?
Original exception: [Errno 2] No such file or directory: 'mongocryptd': 'mongocryptd'
_silence_resource_warning(_spawn(sys.argv[1:]))
```
=> PYTHON-2234 Only rely on standard library in daemon.py

pymongo/cursor.py
- Add a informative UserWarning when no_cursor_timeout is set
=> PYTHON-1880: Raise a warning when no_cursor_timeout is used with an implicit session

pymongo/srv_resolver.py, test/test_client.py
Fixes the following deprecation warning:
```txt
/home/jr769/miniconda3/envs/py38/lib/python3.8/site-packages/pymongo/srv_resolver.py:72: DeprecationWarning: please use dns.resolver.resolve() instead
results = resolver.query('_mongodb._tcp.' + self.__fqdn, 'SRV',
/home/jr769/miniconda3/envs/py38/lib/python3.8/site-packages/pymongo/srv_resolver.py:57: DeprecationWarning: please use dns.resolver.resolve() instead
results = resolver.query(self.__fqdn, 'TXT',
```
=> PYTHON-2364 Replace deprecated dns.resolver.query with dns.resolver.resolve

.evergreen/config.yml, test/versioned-api/runcommand-helper-no-api-version-declared.json, test/versioned-api/test-commands-deprecation-errors.json, test/versioned-api/test-commands-strict-mode.json, test/versioned-api/transaction-handling.json
Also resolves PYTHON-2599 and PYTHON-2641.
=> PYTHON-2600 Resync spec tests for versioned api

pymongo/uri_parser.py
- Generate installation instruction for user to copy paste when dnspython is not installed. 
- I wasn't sure about getting path for Python so I think this is the most straightforward but having to import `os` only for the path seems a bit excessive. But let me know if you would like me to change it :)
=> PYTHON-2605: Improve mongodb+srv:// error message when dnspython is not installed

README.rst, doc/contributors.rst, doc/index.rst
- Just a minor update to sphinx website since the old link is no longer working
=> Update link to sphinx website

.evergreen/config.yml, .evergreen/run-tests.sh, test/test_ssl.py
https://jira.mongodb.org/browse/PYTHON-2603
Patch: https://evergreen.mongodb.com/version/6082160f61837d3849468e47
=> PYTHON-2603 Standardize on ubuntu1804-zseries, ubuntu1804-power8, and ubuntu1804-arm64

test/test_client.py
Fixes the "no server" test failures: 
```
[2021/04/19 22:43:38.653] FAIL [10.026s]: test_direct_client_maintains_pool_to_arbiter (test_client.TestClientPool)
[2021/04/19 22:43:38.653] ----------------------------------------------------------------------
[2021/04/19 22:43:38.653] Traceback (most recent call last):
[2021/04/19 22:43:38.653]   File "/data/mci/c3fd0d8a3cd0109c13fe181f4d100ef4/src/test/test_client.py", line 2082, in test_direct_client_maintains_pool_to_arbiter
[2021/04/19 22:43:38.653]     listener.wait_for_event(monitoring.ConnectionReadyEvent, 1)
[2021/04/19 22:43:38.653]   File "/data/mci/c3fd0d8a3cd0109c13fe181f4d100ef4/src/test/utils.py", line 93, in wait_for_event
[2021/04/19 22:43:38.653]     'find %s %s event(s)' % (count, event))
[2021/04/19 22:43:38.653]   File …
```
=> PYTHON-2634 Skip arbiter tests when no server is running

pymongo/database.py, test/test_database.py
See the docs here: https://docs.mongodb.com/manual/reference/command/profile/
`sampleRate` was added in 3.6.
`filter` was added in 4.4.2.
Filter is a bit odd in that it accepts a query document OR the string "unset" which resets and disables the filter. For this reason I decided not to perform client-side type validation on the filter parameter.
I also decided not to add `**kwargs`. Adding `**kwargs` let's users do strange things like pass arbitrary command arguments (txnNumber, lsid, writeConcern, etc..) and makes the code more confusing since we then need to define (or at least think about) precedence in cases like this: `db.set_profiling_level(ALL, slow_ms=50, slowms=55)`
=> PYTHON-2533 Add support for sample_rate and filter in set_profiling_level

pymongo/srv_resolver.py
This change works around the following eventlet bug:
```
$ python green_framework_test.py eventlet -s test.test_srv_polling.TestSrvPolling.test_addition
...
test_addition (test.test_srv_polling.TestSrvPolling) ... ERROR
======================================================================
ERROR: test_addition (test.test_srv_polling.TestSrvPolling)
File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/dns/resolver.py", line 212, in __init__
rrset = response.find_rrset(response.answer, qname,
File "/Users/shane/pymongo-pycharm-3.8/lib/python3.8/site-packages/dns/message.py", line 341, in find_rrset
raise KeyError
KeyError
During handling of the above exception, another …
```
=> PYTHON-2667 Fix SRV support when running with eventlet

test/srv_seedlist/encoded-userinfo-and-db.json, test/srv_seedlist/txt-record-not-allowed-option.json, test/srv_seedlist/txt-record-with-overridden-ssl-option.json, test/srv_seedlist/uri-with-admin-database.json, test/srv_seedlist/uri-with-auth.json, test/test_dns.py
Add support for validating parsed_options and running non-TLS tests.
This implements the following (ancient) spec changes which never has drivers tickets created for them: 
- https://github.com/mongodb/specifications/commit/53c8c19400f7808f472c5013db194e9af34153e9
- https://github.com/mongodb/specifications/commit/643a8790c65a864835cb1014d5b5939e5e65daa5
- https://github.com/mongodb/specifications/commit/120a529a95a16e7980ace0c78f07133db8c9578c
=> PYTHON-2678 Resync SRV spec tests

doc/examples/tls.rst, doc/migrate-to-pymongo4.rst, pymongo/common.py, pymongo/mongo_client.py, test/test_ssl.py
Should I create a new section in the PyMongo 4 migration guide for deprecated/remove URI options?
=> PYTHON-2396 Deprecate ssl_keyfile and ssl_certfile URI options

pymongo/client_options.py, pymongo/ismaster.py, pymongo/mongo_client.py, pymongo/pool.py, pymongo/server.py, pymongo/server_description.py, pymongo/server_type.py, pymongo/settings.py, pymongo/topology.py, pymongo/topology_description.py
This implements most of the load balancers spec changes: https://github.com/mongodb/specifications/blob/master/source/load-balancers/load-balancers.rst#server-discovery-and-monitoring
- Disable SRV Polling.
- Disable SDAM compatibility check.
- Disable logicalSessionTimeoutMinutes check.
- Disable server session pool pruning.
- Disable server selection.
- Disable Monitors.
- A ServerType of LoadBalancer MUST be considered a data-bearing server.
- "drivers MUST emit the following series of SDAM events" section.
- Send loadBalanced:True with handshakes, validate serviceId.
- Add topologyVersion fallback when serviceId is missing.
- Don't mark load balancers unknown from operation errors.
The notable things left out are testing and the various Connection Pooling changes:
- connection pinning …
=> PYTHON-2672 SDAM, CMAP, and server selection changes for load balancers

test/command_monitoring/find.json, test/test_collection.py, test/unified-test-format/valid-pass/poc-command-monitoring.json
3 Changes to get the tests green:
- PYTHON-2729 Update explain response format parsing for 5.0
- PYTHON-2721 Temporarily skip failing regex test on 5.0
- PYTHON-2730 Temporarily skip failing killCursors tests on 5.0
=> PYTHON-2729 PYTHON-2721 PYTHON-2730 Make 5.0 tests green

pymongo/cursor.py, pymongo/message.py, pymongo/response.py, pymongo/server.py, test/test_monitoring.py
This is mostly so I can see if CI passes.
=> [Backport] PYTHON-1636 Support exhaust cursors in OP_MSG (#629)

.evergreen/config.yml
Some action items from the the initial [Evergreen patch build](https://evergreen.mongodb.com/version/60b0363530661520e5bd6609?redirect_spruce_users=true):
=> PYTHON-2727 Start testing against MongoDB 5.0 in Evergreen

pymongo/pool.py, test/__init__.py, test/load_balancer/test_crud_unified.py, test/load_balancer/test_dns.py, test/load_balancer/test_load_balancer.py, test/load_balancer/test_retryable_change_stream.py, test/load_balancer/test_retryable_reads.py, test/load_balancer/test_retryable_writes.py, test/load_balancer/test_transactions_unified.py, test/load_balancer/test_uri_options.py, test/load_balancer/test_versioned_api.py, test/test_load_balancer.py, test/unified_format.py
This change fixes a few things:
- Moves test_load_balancer.py to the top-level to ensure we run the LB spec tests against non-LB clusters as well.
- Fixes a bug in the unified test runner where an operation which was expected to fail but actually succeeded unexpectedly passed the test.
- Fixes the serviceId fallback logic. In particular, we only enable the fallback when testing against a LB. 
- Fixes a socket leak when SocketInfo connection handshake fails.
Before the serviceId fallback logic fix:
```
$ python3 test/test_load_balancer.py -v
skipped 'TestUnifiedEventMonitoring runOnRequirements not satisfied'
skipped 'TestUnifiedLbConnectionEstablishment runOnRequirements not satisfied'
test_operations_against_non-load_balanced_clusters_fail_if_URI_contains_loadBalanced=true …
```
=> PYTHON-2744 Run LB tests against non-LB clusters

pymongo/change_stream.py, pymongo/errors.py, pymongo/helpers.py, pymongo/message.py, pymongo/mongo_client.py, pymongo/monitor.py, pymongo/network.py, pymongo/pool.py, pymongo/server.py, pymongo/topology.py, test/test_connections_survive_primary_stepdown_spec.py, test/test_discovery_and_monitoring.py, test/test_errors.py, test/test_gridfs.py, test/test_gridfs_bucket.py, test/test_monitoring.py, test/test_sdam_monitoring_spec.py, test/unified_format.py
We _could_ have raised a DeprecationWarning in `NotMasterError.__init__` if we didn't need to continue supporting application code that uses `NotMasterError` - specifically, we want `except NotMasterError` to catch raising `NotPrimaryError` which requires that `NotPrimaryError` inherit from `NotMasterError`. Consequently, every time `NotPrimaryError` is instantiated it would end up raising `NotMasterError`'s `DeprecationWarning`.
=> PYTHON-2572 Introduce NotPrimaryError and deprecate NotMasterError

pymongo/pool.py, test/test_load_balancer.py
See https://jira.mongodb.org/browse/PYTHON-2761
=> PYTHON-2761 Don't return a pinned connection to the pool multiple times

pymongo/client_session.py, pymongo/command_cursor.py, pymongo/cursor.py, pymongo/mongo_client.py, test/__init__.py, test/test_gridfs.py, test/test_load_balancer.py, test/test_retryable_reads.py
It's not safe to return the pinned connection to the pool from within Cursor.__del__ because the Pool's lock may be held by a python thread while the cyclic garbage collector runs. Instead we send the cursor cleanup request to the client's background thread. The thread will send killCursors on the pinned socket and then return the socket to the pool.
=> PYTHON-1272 Fix deadlock for GC cycled pinned cursors

test/test_collection.py
This test started failing because of the combination of OP_MSG exhaust (PYTHON-1636) and Cursor.__del__ changes (PYTHON-1272). With OP_MSG exhaust the more_to_come flag is not set until after the first getMore. If the exhaust cursor is closed before that happens then we don't have to close the connection. I've updated the test to ensure the first getMore runs so that the cursor will always be pinned and more_to_come will always be true.
=> PYTHON-2765 Fix test_exhaust failure due to OP_MSG and __del__ changes

test/discovery_and_monitoring/load-balanced/discover_load_balancer.json, test/sdam_monitoring/load_balancer.json, test/server_selection/server_selection/LoadBalanced/read/Nearest.json, test/server_selection/server_selection/LoadBalanced/read/Primary.json, test/server_selection/server_selection/LoadBalanced/read/PrimaryPreferred.json, test/server_selection/server_selection/LoadBalanced/read/Secondary.json, test/server_selection/server_selection/LoadBalanced/read/SecondaryPreferred.json, test/server_selection/server_selection/LoadBalanced/write/Nearest.json, test/server_selection/server_selection/LoadBalanced/write/Primary.json, test/server_selection/server_selection/LoadBalanced/write/PrimaryPreferred.json, test/server_selection/server_selection/LoadBalanced/write/Secondary.json, test/server_selection/server_selection/LoadBalanced/write/SecondaryPreferred.json, test/test_discovery_and_monitoring.py, test/test_sdam_monitoring_spec.py, test/utils_selection_tests.py
Now we have all the LB tests:
```
$ git grep --name-only oadBala  -- '*.json'
source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection.json
source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-replicaSet-errors.json
source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-true-multiple-hosts.json
source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-true-txt.json
source/initial-dns-seedlist-discovery/tests/replica-set/loadBalanced-false-txt.json
source/load-balancers/tests/lb-connection-establishment.json
source/load-balancers/tests/non-lb-connection-establishment.json
source/server-discovery-and-monitoring/tests/load-balanced/discover_load_balancer.json …
```
=> PYTHON-2768 Add SDAM and server selection spec tests for load balancers

pymongo/pool.py, pymongo/topology_description.py, test/test_topology.py
The serviceId field is not supposed to be returned for non-LB mode. This change fixes the pymongo bug in the ticket by removing the field (if it exists) when in non-LB mode.
=> PYTHON-2791 Ignore erroneous serviceId field for non-LB connections

pymongo/client_session.py, test/sessions/unified/snapshot-sessions-unsupported-ops.json, test/sessions/unified/snapshot-sessions.json, test/test_session.py, test/unified_format.py
Implements: https://github.com/mongodb/specifications/pull/1033
=> PYTHON-2776 Raise error on unsupported snapshot read commands

pymongo/command_cursor.py, pymongo/cursor.py
This will be tested by the ADL prose test being added in #665
=> PYTHON-2799 Use namespace returned from initial command response for killCursors

test/test_encryption.py
Implements: https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/tests/README.rst#bypass-spawning-mongocryptd
=> PYTHON-2096 Validate that mongocryptd is not spawned if bypassAutoEncryption=true

.evergreen/config.yml, .evergreen/install-dependencies.sh, .evergreen/run-mod-wsgi-tests.sh, .evergreen/run-tests.sh, .evergreen/test-encryption-requirements.txt, test/test_encryption.py
Implements the tests described here: https://github.com/mongodb/specifications/tree/master/source/client-side-encryption/tests#kms-tls-tests
Patch (Note the Windows failures are unrelated see PYTHON-2798): https://spruce.mongodb.com/version/60e643e47742ae7acd922fe3/tasks
=> PYTHON-2608 Test that KMS TLS connections verify peer certificates

.evergreen/run-tests.sh, test/__init__.py, test/test_encryption.py, test/test_ssl.py
Apparently SSL_CERT_FILE does work on Windows. We can use it to workaround the issue in BUILD-13574.
=> PYTHON-2798 Workaround windows cert issue with SSL_CERT_FILE

.evergreen/config.yml, .evergreen/run-tests.sh, .evergreen/utils.sh
When I backported PYTHON-2608 I didn't realize that the mock KMS script requires Python 3.5+. For <3.5 we need to create yet another virtualenv. This fixes the encryption tests on v3.12.
=> PYTHON-2608 Fix KMS TLS testing on Python <3.5

test/test_legacy_api.py
=> PYTHON-2807 Skip OP_KILL_CURSORS test on 5.0+

pymongo/collection.py, pymongo/database.py
Also resolves "PYTHON-2840 Document "let" support for aggregation".
=> PYTHON-2802 Link to create command docs in create_collection 

pymongo/topology.py, test/test_client.py
See: https://jira.mongodb.org/browse/DRIVERS-1804
And: https://github.com/mongodb/specifications/commit/7c9af915f6e0d8d73e97805cdb501f8a74a40fab
=> PYTHON-2750 Don't mark arbiter pools ready unless directly connected

.evergreen/build-manylinux-internal.sh, .evergreen/build-manylinux.sh, .evergreen/config.yml
See: https://evergreen.mongodb.com/version/60ff3bd31e2d176fd57d25d7
I decided to split the manylinux release process into 2 tasks to reduce the runtime. Each task takes ~25 minutes, whereas combined into one task would take ~50 minutes.
=> PYTHON-2816 Generate pip < 20.3 compatible manylinux wheels

pymongo/command_cursor.py
Seeing as this class isn't really meant for end user consumption I don't think there is any point of documenting this?
=> PYTHON-1363 Remove unused retrieved parameter from CommandCursor

pymongo/topology.py, test/__init__.py, test/test_cmap.py, test/test_retryable_reads.py, test/test_retryable_writes.py
Implements:
- https://github.com/mongodb/specifications/blob/master/source/retryable-writes/tests/README.rst#prose-tests
- https://github.com/mongodb/specifications/blob/master/source/retryable-reads/tests/README.rst#poolclearederror-retryability-test
=> PYTHON-2602 Test that pool paused errors are retryable

test/sessions/unified/snapshot-sessions-not-supported-client-error.json, test/unified-test-format/invalid/test-expectEvents-minItems.json, test/unified_format.py
Implementing https://github.com/mongodb/specifications/pull/1046
=> PYTHON-2856 Properly assert 0 events in snapshot reads tests

test/__init__.py, test/test_retryable_reads.py, test/test_retryable_writes.py
Fixes this test failure:
```
[2021/08/06 23:40:10.617] FAIL [1.020s]: test_pool_paused_error_is_retryable (test_retryable_writes.TestPoolPausedError)
--
[2021/08/06 23:40:10.617] ----------------------------------------------------------------------
[2021/08/06 23:40:10.617] Traceback (most recent call last):
[2021/08/06 23:40:10.617]   File "/data/mci/f83875c397b2c8b56542a4fad582fb33/src/test/__init__.py", line 547, in wrap
[2021/08/06 23:40:10.617]     return f(*args, **kwargs)
[2021/08/06 23:40:10.617]   File "/data/mci/f83875c397b2c8b56542a4fad582fb33/src/test/__init__.py", line 547, in wrap
[2021/08/06 23:40:10.617]     return f(*args, **kwargs)
[2021/08/06 23:40:10.617]   File "/data/mci/f83875c397b2c8b56542a4fad582fb33/src/test/__init__.py", line 199, in wrap
[2021/08/06 …
```
=> PYTHON-2534 Avoid race in test_pool_paused_error_is_retryable

pymongo/client_options.py, pymongo/encryption.py, pymongo/pool.py, pymongo/ssl_support.py, test/test_client.py, test/test_ssl.py, test/test_uri_parser.py, tools/ocsptest.py
This PR fixes the refactor in PYTHON-2162. I've changed get_ssl_context in all places and double checked the parameter translation.
=> PYTHON-2879 Fix get_ssl_context for CSFLE and ocsptest.py

doc/changelog.rst, doc/migrate-to-pymongo4.rst, pymongo/driver_info.py, test/test_client.py
https://jira.mongodb.org/browse/PYTHON-2057
=> PYTHON-2057 Make 'name' a required argument for DriverInfo class

bson/json_util.py, doc/changelog.rst, doc/migrate-to-pymongo3.rst, doc/migrate-to-pymongo4.rst, gridfs/grid_file.py, test/test_bson_corpus.py, test/test_json_util.py
TODO: 
The options are to 1) ignore these options (keep the current behavior), 2) raise an error when an incompatible option is specified, or 3) allow users to configure these options with any json_mode. For now I've gone with option 2).
=> PYTHON-2046 Change default JSONMode from LEGACY to RELAXED

bson/json_util.py, test/bson_corpus/top.json
https://jira.mongodb.org/browse/PYTHON-2883
=> PYTHON-2883 Regex decoding error tests in top.json have unexpected, invalid syntax

doc/changelog.rst, doc/migrate-to-pymongo4.rst, test/test_decimal128.py
Fixes this "no server" test failure: https://evergreen.mongodb.com/task/mongo_python_driver_no_server_no_server_11752ed594f8d0fd3dac342b01b6c2e1a594e458_21_09_16_23_53_50
Also removes some more MongoDB <= 3.4 info from the migration guide.
=> PYTHON-2899 Fix "no server" tests and cleanup docs

test/utils.py
This should cherry pick cleanly to v3.12 as well.
=> PYTHON-2921 Fix eventlet detection with Python 3.10

.evergreen/build-mac.sh, .evergreen/build-manylinux-internal.sh, .evergreen/build-manylinux.sh, .evergreen/build-windows.sh, setup.py
Ongoing patch here: https://evergreen.mongodb.com/version/61673fb90305b97de980924f
=> PYTHON-2923 Add Python 3.10 to release tasks

test/test_errors.py
Only keep the old behaviour around for older PyPy versions. xref https://github.com/conda-forge/pymongo-feedstock/pull/50
=> TEST: PyPy7.3.7 fixed unicode repr

doc/api/pymongo/mongo_client.rst, doc/changelog.rst, doc/migrate-to-pymongo4.rst, pymongo/mongo_client.py, pymongo/topology_description.py, test/__init__.py, test/test_bulk.py, test/test_client.py, test/test_collection.py
Apps should use the hello command instead:
```python
doc = client.admin.command('hello')
max_bson_size = doc['maxBsonObjectSize']
max_message_size = doc['maxMessageSizeBytes']
max_write_batch_size = doc['maxWriteBatchSize']
```
I'll address the remaining configuration attributes (max_pool_size, min_pool_size, max_idle_time_ms, local_threshold_ms, server_selection_timeout, etc.) in a new PR.
=> PYTHON-2164 Remove client max_bson_size/max_message_size/max_write_batch_size

test/cmap/pool-checkout-minPoolSize-connection-maxConnecting.json
Python already has the correct behavior so we just need to add the new test.
=> PYTHON-2941 Add a CMAP test that verifies the background thread hands over connections to threads doing checkout

test/test_transactions.py
This test often fails on windows because the host is too slow. For example:
```
[2021/11/13 01:27:37.211] ERROR: test_transaction_starts_with_batched_write (test_transactions.TestTransactions)
[2021/11/13 01:27:37.211] ----------------------------------------------------------------------
[2021/11/13 01:27:37.211] Traceback (most recent call last):
[2021/11/13 01:27:37.211]   File "C:\data\mci\095314dcd9cb2f3eef50d8f626aa69ad\src\test\__init__.py", line 555, in wrap
[2021/11/13 01:27:37.211]     return f(*args, **kwargs)
[2021/11/13 01:27:37.211]   File "C:\data\mci\095314dcd9cb2f3eef50d8f626aa69ad\src\test\__init__.py", line 555, in wrap
[2021/11/13 01:27:37.211]     return f(*args, **kwargs)
[2021/11/13 01:27:37.211]   File "C:\data\mci\095314dcd9cb2f3eef50d8f626aa69ad\src\test\test_tran …
```
=> PYTHON-2915 Skip large txn test on slow Windows hosts

doc/changelog.rst, pymongo/encryption.py, pymongo/encryption_options.py, setup.py
Depends on https://github.com/mongodb/libmongocrypt/pull/218
=> PYTHON-3001 Bump minimum pymongocrypt version to 1.2.0

.evergreen/perf.yml
We don't support 3.0 or 3.4 anymore.
=> PYTHON-2919 Remove MongoDB 2.6-3.4 from performance testing

.evergreen/config.yml, RELEASE.rst
This change:
- automatically combines release wheels into one archive
- adds the sdist build
- moves the manylinux wheel builds to ubuntu2004-large because they are expensive
- refactors the EVG release matrix into a single variant
- updates the release.rst docs for the newly simplified release process
Testing here: https://spruce.mongodb.com/version/619d6da457e85a345d0aafb7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-2434 Automatically combine release wheels + sdist into one archive

pymongo/topology_description.py, test/mockupdb/test_rsghost.py, test/server_selection/server_selection/Unknown/read/ghost.json, test/server_selection/server_selection/Unknown/write/ghost.json, test/utils_selection_tests.py
This change fixes the bug and also implements DRIVERS-1999.
=> PYTHON-3027 Fix server selection when topology type is Unknown

bson/decimal128.py, doc/examples/authentication.rst, doc/examples/bulk.rst, pymongo/aggregation.py, pymongo/client_session.py, pymongo/collection.py, pymongo/common.py, pymongo/cursor.py, pymongo/database.py, pymongo/mongo_client.py, pymongo/operations.py, pymongo/pool.py, pymongo/results.py, pymongo/write_concern.py, test/test_collection.py, test/test_cursor.py, test/utils.py
This was the command I used to look for lines to remove:
```
$ git grep 'ongo' -- ':(exclude)doc/changelog.rst' | grep -E '3\.[0123456789]|2\.[0123456789]'
```
=> Removed references to outdated server versions

doc/changelog.rst, pymongo/aggregation.py, pymongo/collection.py, pymongo/mongo_client.py, pymongo/read_preferences.py, pymongo/topology_description.py, test/crud/unified/aggregate-write-readPreference.json, test/crud/unified/db-aggregate-write-readPreference.json, test/test_read_preferences.py
Implementation of https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#read-preferences-and-server-selection including the changes in DRIVERS-823 and DRIVERS-1969.
=> PYTHON-2554 Support $merge and $out executing on secondaries

.evergreen/utils.sh
Tests are passing here: https://evergreen.mongodb.com/version/61afbeac1e2d1765ffcf91e9
=> PYTHON-3026 Fix Windows Python 3.6 tests

.github/workflows/test-python.yml
Passing tests here: https://github.com/ShaneHarvey/mongo-python-driver/actions/runs/1560579660
Note that our main testing is done on Evergreen (https://evergreen.mongodb.com/waterfall/mongo-python-driver) but actions is useful to get quicker feedback and help external contributors.
=> PYTHON-2473 Add basic Github Actions testing

THIRD-PARTY-NOTICES, setup.py
This has one side effect that a warning is printed when running setup.py check or sdist:
```
$ python3.10 setup.py check
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too
``` 
And:
```
python3.10 setup.py sdist
running sdist
running egg_info
writing pymongo.egg-info/PKG-INFO
writing dependency_links to pymongo.egg-info/dependency_links.txt
writing requirements to pymongo.egg-info/requires.txt
writing top-level names to pymongo.egg-info/top_level.txt
reading manifest file 'pymongo.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'pymongo.egg-info/SOURCES.txt'
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too …
```
=> PYTHON-2160 Stop using Google Groups email address

.evergreen/perf.yml, test/performance/perf_test.py
Followed the migration guide here: https://github.com/10gen/performance-tooling-docs/blob/main/getting_started/performance_monitoring_setup.md#legacy-data-migration
Testing here: https://spruce.mongodb.com/version/61b2a9a5562343496412629b
=> PYTHON-2888 Migrate from json.send to perf.send

pymongo/aggregation.py, pymongo/change_stream.py, pymongo/collection.py, pymongo/database.py, pymongo/message.py, pymongo/mongo_client.py, pymongo/network.py, pymongo/pool.py, pymongo/server.py, test/crud/unified/aggregate-write-readPreference.json, test/crud/unified/db-aggregate-write-readPreference.json, test/mockupdb/test_mongos_command_read_mode.py, test/mockupdb/test_op_msg_read_preference.py, test/mockupdb/test_query_read_pref_sharded.py, test/test_cursor.py, test/test_read_preferences.py
This change fixes how pymongo sends $readPreference to the server via OP_MSG:
- Stop sending $readPreference to standalone servers. The spec says to omit it.
- Stop sending $readPreference with primary read preference to all servers. The spec says to omit "primary" since it's the server's default.
- The final rule is to always send $readPreference=primaryPreferred when directly connected to a single replica set member. This is to ensure that the app does not get NotPrimary errors for direct connections.
This change also removes the `secondary_ok` variable which is no longer needed. Instead of tracking the "secondary ok" boolean we replace the input read preference with the effective read preference (primary, primaryPreferred, or the original read preference). 
This change depends on …
=> PYTHON-1864 PYTHON-2931 Spec complaint $readPreference 

.evergreen/config.yml, .evergreen/run-mod-wsgi-tests.sh, .evergreen/run-tests.sh, .evergreen/utils.sh, test/test_encryption.py
Note that testing more things with Python 3.10 is a side effect, but https://jira.mongodb.org/browse/PYTHON-3043 and https://jira.mongodb.org/browse/PYTHON-3042 remain.
=> PYTHON-2903 Migrate testing from Amazon1 to Ubuntu 18.04

pymongo/message.py
Fix this bug in PYTHON-2763:
```python
[2021/12/13 23:49:53.657] ERROR: test_automatic (test_encryption.TestAzureEncryption)
[2021/12/13 23:49:53.657] ----------------------------------------------------------------------
[2021/12/13 23:49:53.657] Traceback (most recent call last):
[2021/12/13 23:49:53.657]   File "/data/mci/a675b9166889c90001e88dd30fc0da34/src/test/test_encryption.py", line 1441, in test_automatic
[2021/12/13 23:49:53.657]     return self._test_automatic(
[2021/12/13 23:49:53.657]   File "/data/mci/a675b9166889c90001e88dd30fc0da34/src/test/test_encryption.py", line 1414, in _test_automatic
[2021/12/13 23:49:53.657]     output_doc = coll.find_one({})
[2021/12/13 23:49:53.657]   File "/data/mci/a675b9166889c90001e88dd30fc0da34/src/pymongo/collection.py", line 1133, in …
```
=> PYTHON-2763 Fix check_keys removal in encryption

doc/installation.rst
When installing a package with multiple dependencies in zsh, you write it under quotations, like so:
```
$ python3 -m pip install "pymongo[aws]"
```
or else it will give you this error:
```
zsh: no matches found: pymongo[aws]
```
Separate each subsection by the way it's done on each OS, if the syntax above is different.
=> Change pip installation of pymongo to quotations

.evergreen/config.yml
https://spruce.mongodb.com/version/61b9196cd1fe071038194cfb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-3042 Migrate OCSP testing to Ubuntu 20.04

pymongo/server.py
I guess colon`:` is for use rather than hyphen`-`
=> Edit simple typo in docs

test/test_encryption.py
(cherry picked from commit 561ee7cf77fcbdefb9e2f46691f2b2ba4c65198b)
=> PYTHON-3110 [v3.13] Remove use of example.com in CSFLE tests (#848)

.evergreen/resync-specs.sh
These two workarounds were accidentally removed in PYTHON-3071
=> Add resync-syncs workarounds for incomplete spec work

pymongo/ocsp_support.py, pymongo/pyopenssl_context.py
I opened https://jira.mongodb.org/browse/PYTHON-3132 to update our dependency to pyopenssl>=20.0 in which case we can remove the fallback. I'm preserving the pyopenssl<20.0 behavior to ease backports.
=> PYTHON-2147 Use verified peer cert chain in OCSP when available

doc/contributors.rst, pymongo/results.py
As described in [PYTHON-3124](https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-3124), there were some overlapping slots in `_WriteResult` subclasses.
I see there have been several `__slots__`  issues in pymongo in the past. I discovered this slot issue with [slotscheck](https://github.com/ariebovenberg/slotscheck), a tool I maintain. If you like, I can add it to CI as I've done for [instagram/LibCST](https://github.com/Instagram/LibCST/pull/615), [sqlalchemy/sqlalchemy](https://github.com/sqlalchemy/sqlalchemy/pull/7670), and [aio-libs/aiohttp](https://github.com/aio-libs/aiohttp/pull/6547).
=> PYTHON-3124 Remove overlapping slots from _WriteResult subclasses

test/test_pooling.py
Removing $where fixes the test failures.
=> PYTHON-3142 Stop using $where in test_maxConnecting

doc/changelog.rst, pymongo/topology_description.py, test/discovery_and_monitoring/rs/electionId_precedence_setVersion.json, test/discovery_and_monitoring/rs/electionId_setVersion.json, test/discovery_and_monitoring/rs/null_election_id.json, test/discovery_and_monitoring/rs/set_version_can_rollback.json, test/discovery_and_monitoring/rs/setversion_equal_max_without_electionid.json, test/discovery_and_monitoring/rs/setversion_greaterthan_max_without_electionid.json, test/discovery_and_monitoring/rs/setversion_without_electionid.json, test/test_discovery_and_monitoring.py
Draft implementation of DRIVERS-1954: https://github.com/mongodb/specifications/pull/1122
TODO:
=> PYTHON-2970 SDAM should give priority to electionId over setVersion to detect a stale primary

test/__init__.py, test/test_client.py
This change avoids false positives for the main client_context client. I also changed the output to be a little more readable. When the check finds a real problem, the new output looks like this:
```
pypy3 setup.py test -s test.test_client.TestClient
...
test_waitQueueTimeoutMS (test.test_client.TestClient) ... ok
Ran 57 tests in 19.489s
OK (skipped=9)
WARNING: found Topology with running threads:
Threads: [<PeriodicExecutor(name=pymongo_server_monitor_thread) object at 0x7facb8231248>, <PeriodicExecutor(name=pymongo_server_rtt_thread) object at 0x7facb8231328>]
Topology: <Topology <TopologyDescription id: 6230fe16efe40a2b8ad01304, topology_type: ReplicaSetWithPrimary, servers: [<ServerDescription ('localhost', 27017) …
```
=> PYTHON-3174 Remove noisy running Topology check for main test client

test/__init__.py, test/test_raw_bson.py
This code was mistakenly added in PYTHON-2463 (#737).
=> PYTHON-3174 Don't reinit client_context.client

pymongo/collection.py, pymongo/database.py, pymongo/mongo_client.py, test/test_client.py, test/test_collection.py, test/test_database.py
As noted in PYTHON-3084, this was the only way to get the typing.Iterable instance check to fail. We could also remove `__next__`+`next` (from client/Database only) but I kept them around so that users get better error messages `TypeError: 'MongoClient' object is not iterable` vs `TypeError: name must be an instance of str`.
=> PYTHON-3084 MongoClient/Database/Collection should not implement Iterable

doc/examples/copydb.rst
https://jira.mongodb.org/browse/PYTHON-3138
I inlined part of the mongodump example for convenience.
=> PYTHON-3138 copydb was removed in MongoDB 4.2

pymongo/network.py, test/__init__.py, test/sigstop_sigcont.py, test/test_client.py
Poll monitor socket with timeout=0 one last time after timeout expires.
=> PYTHON-3186 Avoid SDAM heartbeat timeouts on AWS Lambda

test/change_streams/unified/change-streams.json, test/sessions/driver-sessions-dirty-session-errors.json, test/test_session.py, test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-3160
=> PYTHON-3160 Fix MMAPv1 tests

test/__init__.py, test/sigstop_sigcont.py
https://jira.mongodb.org/browse/PYTHON-3191
=> PYTHON-3191 Fix test_sigstop_sigcont with Versioned API

pymongo/collection.py
Line 1446 of this file originally read as follows:
> "`filter` (optional): a SON object specifying elements..."
I believe "SON" is a typo for "JSON", so have updated it to read as follows:
> "`filter` (optional): a JSON object specifying elements..."
=> Improve docstrings for SON parameters

MANIFEST.in, setup.py
The typing markers should be declared in the `package_data` to get picked up and packaged into the distributed wheels.
=> PYTHON-3214 Fix typing markers not being included in the distribution

test/test_encryption.py
https://jira.mongodb.org/browse/PYTHON-3210
=> PYTHON-3210 Remove flakey string assertion from invalid aws creds FLE test

setup.py
https://jira.mongodb.org/browse/PYTHON-3216
```
unzip -l dist/pymongo-4.2.0.dev0-cp37-cp37m-macosx_10_9_x86_64.whl | grep '.pyi'
3331  04-05-2022 20:40   bson/codec_options.pyi
```
=> PYTHON-3216 Include codec_options.pyi in release distributions

bson/__init__.py, bson/_cbsonmodule.c, doc/changelog.rst, test/test_bson.py
https://jira.mongodb.org/browse/PYTHON-3222
This change fixes a number of issues:
1. Fixes a memory leak of CodecOptions() in C extension's default_codec_options function. The leak occurs when not passing a CodecOptions to decode_all, (ie `decode_all(data)` or  `decode_all(data, None)`).
1. Fixes support for keyword argument codec_options for bson.decode_all.
1. Fixes a documentation issue where bson.decode_all was not showing up in the docs page.
1. Adds the changelog for 4.1.1
=> PYTHON-3222 Fix memory leak in cbson decode_all

test/test_collection.py
https://jira.mongodb.org/browse/PYTHON-3225
I thought it simpler to stop testing this case altogether rather than try to parse which version supports it or not. The driver doesn't do anything different for a capped collection anyway.
=> PYTHON-3225 Stop testing delete on capped collections

test/__init__.py, test/test_encryption.py, test/test_retryable_reads.py, test/unified_format.py, test/utils_spec_runner.py
This shaves off anywhere from 1 minute to **16 minutes** from the test suite on macos depending of the server version and topology: https://spruce.mongodb.com/task/mongo_python_driver_test_macos__platform~macos_1014_auth~auth_ssl~ssl_test_4.2_replica_set_patch_05b55e88dfa1636511eeeac56d4a75593a76fbeb_6270a5ab5623434c42b90339_22_05_03_03_46_53/tests?execution=0&sortBy=STATUS&sortDir=ASC
On "macOS 10.14 Auth SSL" alone this change saves 67 minutes of execution time (Time Spent 3h 32m vs 4h 25m).
=> PYTHON-3250 Speed up majority writes in test suite

pymongo/uri_parser.py, test/test_uri_parser.py
Minor change to improve the error behavior in https://jira.mongodb.org/browse/PYTHON-3251. 
Before this change:
```
>>> uri_parser.parse_uri('mongodb://mongo-service:27017 ')
...
ValueError: Port must be an integer between 0 and 65535: 27017 
```
After this change:
```
>>> uri_parser.parse_uri('mongodb://mongo-service:27017 ')
...
ValueError: Port must be an integer between 0 and 65535: '27017 '
```
=> PYTHON-3251 Make extra whitespace visible in invalid port exception

pymongo/topology.py, pymongo/topology_description.py
Fixes https://jira.mongodb.org/browse/PYTHON-3065.
Explanation:
PYTHON-3065 looked like a flakey test but is actually a real bug. With some extra logging the test failure looks like this:
```
test_direct-connection-false (test.test_dns.TestDNSRepl) ... _ensure_opened: <TopologyDescription id: 6275bd337ad1d299c0eefa54, topology_type: Unknown, servers: [<ServerDescription ('localhost.test.build.10gen.cc', 27017) server_type: Unknown, rtt: None>]>
MongoClient(mongodb+srv://test3.test.build.10gen.cc/?directConnection=false, **{'tlsCertificateKeyFile': '/Users/shane/git/mongo-python-driver/test/certificates/client.pem', 'tlsCAFile': '/Users/shane/git/mongo-python-driver/test/certificates/ca.pem', 'tlsAllowInvalidHostnames': True, 'appname': 'test_direct-connection-false'})
_process_change: …
```
=> PYTHON-3065 Ignore SRV polling update when topology is discovered to be a replica set

pymongo/pool.py, pymongo/topology.py
https://jira.mongodb.org/browse/PYTHON-3257
This change fixes a regression in pymongo 4.0.
```python
$ cat fork_test.py 
from os import fork
from pymongo import MongoClient, errors
client = MongoClient()
client.admin.command('ping')
pid = fork()
if pid:
print('parent exiting')
else:
print('ping in child:')
for i in range(1, 50):
try:
print(client.admin.command('ping'))
break
except errors.AutoReconnect as exc:
print(f'failure {i}: {exc}')
```
Output before this change:
```
$ python fork_test.py
parent exiting
ping in child:
/Users/shane/git/mongo-python-driver/pymongo/topology.py:177: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe …
```
=> PYTHON-3257 Fix "connection pool paused" errors in child after fork

pymongo/pool.py, pymongo/pyopenssl_context.py, pymongo/ssl_support.py, test/test_encryption.py, test/test_ssl.py
This is tangentially related to some work I did on CSOT so I figured I would knock it out. 
This change fixes the issue described in PYTHON-3187 and also cleans up the Python <3.7 ssl support code for check_hostname and SNI.
=> PYTHON-3187 Avoid tight poll() loop on pyopenssl connections

.evergreen/config.yml, .evergreen/run-tests.sh, pymongo/encryption.py, pymongo/encryption_options.py, test/test_encryption.py
PYTHON-3277 Rename csfle library to crypt_shared.
=> PYTHON-3277 Rename csfle library to crypt_shared

.evergreen/resync-specs.sh, .evergreen/run-tests.sh, pymongo/encryption.py, pymongo/encryption_options.py, test/client-side-encryption/etc/data/encryptedFields.json, test/client-side-encryption/etc/data/keys/key1-document.json, test/client-side-encryption/etc/data/keys/key1-id.json, test/client-side-encryption/etc/data/keys/key2-document.json, test/client-side-encryption/etc/data/keys/key2-id.json, test/test_encryption.py
PYTHON-3245 Implement explicit queryable encryption.
Depends on https://github.com/mongodb/libmongocrypt/pull/358/
Implements the prose test here: https://github.com/mongodb/specifications/tree/d4c9432c4b4425fd3dcc0dad0f65d954e7e6e1e4/source/client-side-encryption/tests#explicit-encryption
=> PYTHON-3245 Support explicit queryable encryption

pymongo/encryption.py
Better docs for encrypt() which you can see rendered here: https://pymongo--960.org.readthedocs.build/en/960/api/pymongo/encryption.html#pymongo.encryption.ClientEncryption.encrypt
=> PYTHON-3245 Fix docs for index_key_id

pymongo/__init__.py, pymongo/_csot.py, pymongo/topology.py, test/test_csot.py
https://jira.mongodb.org/browse/PYTHON-3290
=> PYTHON-3290 Support nested pymongo.timeout() calls

setup.py
I will update this once we create a tag for https://github.com/mongodb/libmongocrypt/pull/366.
=> PYTHON-3294 Depend on PyMongoCrypt 1.3.0b0 tag for beta

pymongo/__init__.py, pymongo/_csot.py, test/test_csot.py
Fix an issue with https://jira.mongodb.org/browse/PYTHON-3290
=> PYTHON-3290 Nested pymongo.timeout() calls only shorten the deadline

bson/_cbsonmodule.c, bson/buffer.c, bson/buffer.h, bson/encoding_helpers.c, bson/encoding_helpers.h, bson/time64.c, bson/time64.h, doc/contributors.rst, pymongo/_cmessagemodule.c
Refactored some of the C symbols so that they avoid conflicts as mentioned in [PYTHON-2110](https://jira.mongodb.org/browse/PYTHON-2110). The following symbols should be refactored as:
```
PyInit__cmessage        => pymongo_PyInit__cmessage
buffer_free             => pymongo_buffer_free
buffer_get_buffer       => pymongo_buffer_get_buffer
buffer_get_position     => pymongo_buffer_get_position
buffer_new              => pymongo_buffer_new
buffer_save_space       => pymongo_buffer_save_space
buffer_update_position  => pymongo_buffer_update_position
buffer_write            => pymongo_buffer_write
PyInit__cmessage        => pymongo_PyInit__cmessage
buffer_free             => pymongo_buffer_free
buffer_get_buffer       => pymongo_buffer_get_buffer
buffer_get_position     => …
```
=> PYTHON-2110 Refactored some C to avoid symbol conflicts

doc/migrate-to-pymongo4.rst, gridfs/__init__.py, gridfs/grid_file.py, test/test_grid_file.py, test/test_gridfs.py
The [spec for GridFS](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#id21) says not to rollback any changes that occur as a result of errors while uploading a file, so this test was added to check that the state doesn't get rolled back.
=> PYTHON-1552 Adds test that an exception thrown while writing a GridFS file ensures chunks are saved, but not associated with a file.

test/unified-test-format/valid-pass/collectionData-createOptions.json, test/unified_format.py
Explanation:
> If the size field is less than or equal to 4096, then the collection will have a cap of 4096 bytes.
https://www.mongodb.com/docs/manual/core/capped-collections/#create-a-capped-collection
=> PYTHON-3337 Fix capped collection test on MMAPv1

pymongo/mongo_client.py, pymongo/pool.py, test/test_csot.py
Explanation: 
1.  In load balanced mode the driver skips SDAM so we need to fallback to using the connection's rtt calculated from the connection handshake.
1.  In load balanced mode the driver also skips server selection so we cannot rely on a ServerSelectionTimeoutError to abort the retry loop. Instead we need to explicitly check the CSOT timeout has not expired.
=> PYTHON-3345 CSOT use connection handshake RTT for load balanced mode

pymongo/database.py, pymongo/ocsp_support.py
There are small typos in:
- pymongo/database.py
- pymongo/ocsp_support.py
Fixes:
- Should read `tolerance` rather than `tolerence`.
- Should read `automatically` rather than `automactically`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

pymongo/change_stream.py, test/test_change_stream.py, test/test_csot.py, test/unified_format.py
https://jira.mongodb.org/browse/PYTHON-3363
=> PYTHON-3363 Allow change stream to be resumed after a timeout

bson/codec_options.py, test/test_bson.py
Removed `__repr__` so that the default behavior is used, and changed test to match.
=> PYTHON-3371 Remove DatetimeConversionOpts.__repr__

pymongo/change_stream.py, test/test_change_stream.py
Fix: https://jira.mongodb.org/browse/PYTHON-3389
=> PYTHON-3389 Close ChangeStream after non-resumable non-timeout errors

doc/changelog.rst, doc/faq.rst
Also updated the FAQ for the fork safety section.
=> Changelog 4.3

test/unified_format.py, test/utils.py
This PR fixes https://jira.mongodb.org/browse/PYTHON-2531 and https://jira.mongodb.org/browse/PYTHON-3405.
PYTHON-2531 was a test bug where we had an infinite loop in ensure_all_connected. 
PYTHON-3405 was a test bug where we were incorrect comparing a ServerDescription with a _Address which always compare unequal.
=> PYTHON-3405/PYTHON-2531 Fix tests for primary step down

test/__init__.py, test/test_encryption.py, test/test_fork.py
This will help debug the failures in PYTHON-3406.
=> PYTHON-3406 Refactor fork tests to print traceback on failure

test/__init__.py, test/test_encryption.py, test/test_fork.py
This PR improves the tests by logging a traceback when a fork() test encounters a deadlock. For example, when I remove the lock sanitation code here is the new output:
```
$ python test/test_fork.py -v -k test_lock_client
test_lock_client (__main__.TestFork) ... Process ForkProcess-1:
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "test/test_fork.py", line 49, in target
self.client.admin.command("ping")
File "/Users/shane/git/mongo-python-driver/pymongo/_csot.py", line 105, in csot_wrapper
return func(self, …
```
=> PYTHON-3406 Log traceback when fork() test encounters a deadlock

pymongo/monitoring.py
I was researching how to log queries.
Found the `monitoring` module with great examples.
And found out that the example of [ConnectionPoolLogger](https://pymongo.readthedocs.io/en/stable/api/pymongo/monitoring.html#:~:text=Connection%20monitoring%20and%20pooling%20events%20are%20also%20available.%20For%20example%3A) is [missing one new method](https://pymongo.readthedocs.io/en/stable/api/pymongo/monitoring.html#pymongo.monitoring.ConnectionPoolListener.pool_ready).
As a result of this - `NotImplementedError` on invocation of the method.
So, I made a single commit to fix it.
=> PYTHON-3441 docs: add missed method in monitoring logger example

doc/changelog.rst, pymongo/topology_description.py, test/discovery_and_monitoring/rs/electionId_precedence_setVersion.json, test/discovery_and_monitoring/rs/null_election_id-pre-6.0.json, test/discovery_and_monitoring/rs/null_election_id.json, test/discovery_and_monitoring/rs/secondary_ignore_ok_0-pre-6.0.json, test/discovery_and_monitoring/rs/set_version_can_rollback.json, test/discovery_and_monitoring/rs/setversion_equal_max_without_electionid.json, test/discovery_and_monitoring/rs/setversion_greaterthan_max_without_electionid.json, test/discovery_and_monitoring/rs/setversion_without_electionid-pre-6.0.json, test/discovery_and_monitoring/rs/setversion_without_electionid.json, test/discovery_and_monitoring/rs/use_setversion_without_electionid-pre-6.0.json, test/discovery_and_monitoring/rs/use_setversion_without_electionid.json, test/discovery_and_monitoring/unified/rediscover-quickly-after-step-down.json, test/utils.py
This PR:
- Implements [PYTHON-2970](https://jira.mongodb.org/browse/PYTHON-2970) by reapplying the original change from #845. 
- Implements [PYTHON-3400](https://jira.mongodb.org/browse/PYTHON-3400) to only use the new logic on MongoDB 6.0+
=> PYTHON-2970 Prioritize electionId over setVersion for stale primary check on 6.0+

test/client-side-encryption/spec/maxWireVersion.json, test/test_encryption.py
(cherry picked from commit e3ff041b474835f007faaead470bb12dcc9dc22c)
=> PYTHON-3433 [v3.13] Failure: test.test_encryption.TestSpec.test_legacy_maxWireVersion_operation_fails_with_maxWireVersion___8 (#1052)

doc/changelog.rst, pymongo/collection.py, pymongo/mongo_client.py, setup.py
=> PYTHON-3499 Changelog for 3.13

doc/changelog.rst, gridfs/grid_file.py
Benchmark results for iterating a randomly generated file with readline() before this change:
```
client.server_info()['version']='5.0.13' pymongo.__version__='4.4.0.dev0'
object_size_mb= 1, chunk_size_kb= 128, 0.030s
object_size_mb= 1, chunk_size_kb= 256, 0.036s
object_size_mb= 1, chunk_size_kb= 512, 0.056s
object_size_mb= 1, chunk_size_kb=1024, 0.122s
object_size_mb= 1, chunk_size_kb=8192, 0.116s
object_size_mb= 5, chunk_size_kb= 128, 0.179s
object_size_mb= 5, chunk_size_kb= 256, 0.185s
object_size_mb= 5, chunk_size_kb= 512, 0.338s
object_size_mb= 5, chunk_size_kb=1024, 0.652s
object_size_mb= 5, chunk_size_kb=8192, 8.401s
object_size_mb=20, chunk_size_kb= 128, 0.869s
object_size_mb=20, chunk_size_kb= 256, 1.131s
object_size_mb=20, chunk_size_kb= 512, 1.694s
object_size_mb=20, …
```
=> PYTHON-3508 Improve the performance of GridOut.readline and GridOut.read

test/test_create_entities.py, test/test_mypy.py
PYTHON-3528 Skip TestCreateEntities when no server is running.
PYTHON-3527 Skip test_typeddict_find_notrequired when no server is running.
Also fixes the 150s TestCreateEntities issue.
=> PYTHON-3527 + PYTHON-3528 Fix no-server tests

bson/codec_options.py, bson/json_util.py
Weirdly enough sphinx does not recognize the docstring if you put it in `__new__`, so I had to define an `__init__`  function for the docstring, but it does not do anything because the class is immutable.
=> PYTHON-3558 Missing docs for JSONOptions

setup.py, test/test_load_balancer.py, test/test_read_concern.py
By looking at the server logs I discovered that the 4.0 primary was blocked from running the agg $out operation because a previous test intentionally left a transaction open. I've updated the test to close the transaction on the server so the test runs in a few milliseconds instead of 1 minute now.
=> PYTHON-3577 Fix test_aggregate_out on 4.0 replica set

test/test_retryable_writes.py
The server no longer performs a write when running `replace_one({}, {})` on an empty document so I've updated the test operations to ensure a new document needs to be written.
=> PYTHON-3596 Guarantee a document update in retryable writes tests

test/test_load_balancer.py
https://jira.mongodb.org/browse/PYTHON-3577 
Fixes this error on serverless:
```
[2023/02/02 20:32:46.535] ERROR [1.071s]: test_session_gc (test_load_balancer.TestLB)
[2023/02/02 20:32:46.535] ----------------------------------------------------------------------
[2023/02/02 20:32:46.535] Traceback (most recent call last):
[2023/02/02 20:32:46.535]   File "/data/mci/4cac7e2c9fe9236da7246fb89bbb0d46/src/pymongo/_csot.py", line 105, in csot_wrapper
[2023/02/02 20:32:46.535]     return func(self, *args, **kwargs)
[2023/02/02 20:32:46.536]   File "/data/mci/4cac7e2c9fe9236da7246fb89bbb0d46/src/pymongo/database.py", line 824, in command
[2023/02/02 20:32:46.536]     return self._command(
[2023/02/02 20:32:46.536]   File "/data/mci/4cac7e2c9fe9236da7246fb89bbb0d46/src/pymongo/database.py", line …
```
=> PYTHON-3577 Fix test_session_gc on serverless

.evergreen/config.yml
Depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/266
=> PYTHON-3579 Test Failure - Amazon Linux 2018 fails downloading crypt_shared when it is not even needed

pymongo/_csot.py, pymongo/monitor.py, pymongo/server_description.py, pymongo/topology.py, test/csot/command-execution.json
[PYTHON-3616](https://jira.mongodb.org/browse/PYTHON-3616) Use minimum RTT for CSOT maxTimeMS calculation.
Require at least 2 RTT samples, otherwise use 0 as RTT. Only keep last 10 samples.
Spec commit: https://github.com/mongodb/specifications/commit/c06650d86f7e47ea30cb2d992942bcec6ef155f9
Spec PR: https://github.com/mongodb/specifications/pull/1350
=> PYTHON-3616 Use minimum RTT for CSOT maxTimeMS calculation

.evergreen/perf.yml
Passing builds from patch: https://spruce.mongodb.com/version/63f7b44a1e2d1715c85d9c9a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-3618 Perf tests are failing on the centos6-perf boxes due to mongosh download

test/csot/command-execution.json, test/unified_format.py
Temporarily skip CSOT GridFS tests on Windows.
=> PYTHON-3522 Increase test timeout for Windows

.gitignore, pymongo/operations.py, test/test_collection.py
Closes Issue [PYTHON-3657](https://jira.mongodb.org/browse/PYTHON-3657)
=> PYTHON-3657 Allow index name explicitly set to None

.evergreen/config.yml
- Reload expansions before deleting Azure resources
Verified with this patch: https://spruce.mongodb.com/version/643454523066158dd65bd5d9
This is an improvement to the `testazurekms_task_group` added as part of DRIVERS-2411. https://github.com/mongodb/mongo-c-driver/pull/1234 explains this improvement.
=> PYTHON-3658 Reload expansions before deleting Azure resources

test/test_ssl.py
https://jira.mongodb.org/browse/PYTHON-3672
=> PYTHON-3672 Increase server selection timeout in more tests

doc/examples/authentication.rst
https://jira.mongodb.org/browse/PYTHON-3678
Resolves https://github.com/mongodb/mongo-python-driver/pull/1186
=> PYTHON-3678 Username/password needs to be escaped with quote_plus to account for '/'

.github/workflows/test-python.yml, bson/decimal128.py, bson/son.py, test/test_encryption.py
https://jira.mongodb.org/browse/PYTHON-3679
Adds workarounds/fixes for some small changes in:
- https://github.com/python/typeshed/pull/9694
- https://github.com/python/typeshed/pull/9194
=> PYTHON-3679 Support mypy 1.2

pymongo/pool.py, test/test_client.py
Implements:
- https://jira.mongodb.org/browse/PYTHON-3464
- and part of https://jira.mongodb.org/browse/PYTHON-2052
Helpful links:
- https://github.com/mongodb/specifications/blob/5112bcc/source/mongodb-handshake/handshake.rst#limitations
- https://github.com/mongodb/specifications/blob/5112bcc/source/mongodb-handshake/handshake.rst#client-env
=> PYTHON-3464 Add FaaS platform to handshake metadata

bson/_cbsonmodule.c, bson/_cbsonmodule.h, pymongo/_cmessagemodule.c
In _cbsonmodule.c, [the `_type_marker` function](https://github.com/mongodb/mongo-python-driver/blob/bda9e3a0bb533b6d0c6c5141feeecb77c4d31709/bson/_cbsonmodule.c#L431-L440) uses `PyObject_HasAttrString(object, "_type_marker")` and `PyObject_GetAttrString(object, "_type_marker")`. In my workloads (highly nested documents with many large array fields), these functions become severe bottlenecks to performance, because they each create new Python string objects by calling `PyUnicode_FromString("_type_marker")` internally every time they run.
This simple change improved my performance by more than double. One caveat is that this leaks the `TYPEMARKERSTR` object in the case that the `cbson` module is unloaded.
Also, correct me if I'm wrong, but I believe [these lines are …
=> PYTHON-3717 Speed up _type_marker check in BSON

.evergreen/config.yml
Linked PR: https://github.com/mongodb-labs/drivers-evergreen-tools/pull/306
=> PYTHON-3692 [Build Failure] Container Test failed MONGODB-AWS on MongoDB 5.0

doc/contributors.rst, test/mockupdb/test_network_disconnect_primary.py
This PR addresses issue PYTHON-3725, related to test_network_disconnect_primary's failure in MockupDB.
- Initial issue:
- `primary` and `secondary` assignments exhausted `(MockupDB() for _ in range(2))` generator, causing `servers` to become an empty generator, leading to test failures.
- Changes based on PR review:
- Replaced generator with direct assignment: `primary, secondary = MockupDB(), MockupDB()`
- Eliminated `servers` variable and its usage in the test
- Modifications aimed at consistency with similar tests and future problem prevention.
=> PYTHON-3725 Fix Test Failure - MockupDB test_network_disconnect_primary

bson/_cbsonmodule.c, bson/_cbsonmodule.h, setup.py
https://jira.mongodb.org/browse/PYTHON-3728
I'm convinced the Coverity issue is a false positive and that simplifying the convert_codec_options signature should help.
=> PYTHON-3728 Simplify convert_codec_options signature

bson/datetime_ms.py, doc/examples/datetimes.rst, doc/tutorial.rst, gridfs/grid_file.py, pymongo/ocsp_cache.py, pymongo/ocsp_support.py, test/test_bson.py, test/test_client.py, test/test_objectid.py, test/test_ocsp_cache.py, test/utils_selection_tests.py
Several places in the code currently depend on the UTC timestamp being naive, meaning there is no explicit attached timezone. As a result, I've used `.replace(tzinfo=None)` where necessary to strip the associated timezone information after generating a UTC timestamp. It's likely preferable to standardize our timestamps to always be aware since we're migrating away from implicit UTC timestamps.
=> PYTHON-3702 Stop using utcnow and utcfromtimestamp

bson/codec_options.py, doc/contributors.rst, pymongo/common.py, pymongo/pyopenssl_context.py, pymongo/write_concern.py, test/test_common.py
https://jira.mongodb.org/browse/PYTHON-2287
=> PYTHON-2287 Improve error message for invalid boolean option

pymongo/change_stream.py, pymongo/client_session.py, pymongo/collection.py, pymongo/command_cursor.py, pymongo/cursor.py, pymongo/database.py, pymongo/encryption_options.py, pymongo/mongo_client.py, pymongo/monitoring.py, test/test_comment.py
The `test/test_comment.py` changes are due to `__future__` annotations explicitly not evaluating all type annotations, causing the test to fail due to comparing the string `"Optional[Any]"` to the evaluated value `Union[Any, None]`. If we want to keep the original, evaluated comparison, we could explicitly evaluate the type annotation as described here: https://docs.python.org/3/library/typing.html#typing.get_type_hints.
=> PYTHON-3737 Use __future__ annotations for forward reference type hints

.github/workflows/test-python.yml, tox.ini
This change is still using `python setup.py test` inside tox to run the unit tests: migration to pytest will be done in https://jira.mongodb.org/browse/PYTHON-3727, and migration to pyproject.toml will be done in https://jira.mongodb.org/browse/PYTHON-2965.
=> PYTHON-2963 Add tox config in preparation for migration from setup.py

.github/CODEOWNERS
https://jira.mongodb.org/browse/PYTHON-3762
=> PYTHON-3762 Remove global code owners

setup.py
Fails as expected when the c extension has an error now:
```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Ibson -I/Users/steve.silvester/workspace/mongo-python-driver/.tox/test/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c bson/_cbsonmodule.c -o build/temp.macosx-10.9-x86_64-cpython-37/bson/_cbsonmodule.o
bson/_cbsonmodule.c:282:5: error: use of undeclared identifier 'a'
a = b;
^
bson/_cbsonmodule.c:282:9: error: use of undeclared identifier 'b'
a = b;
^
2 errors generated.
/private/tmp/pip-build-env-4cfbi019/overlay/lib/python3.7/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*. …
```
=> PYTHON-3760 Add C extension building as part of tox test environment

bson/__init__.py, bson/_cbsonmodule.c, doc/contributors.rst, test/test_custom_types.py, test/test_default_exports.py
Hi,
I'm regularly dealing with 64-bit *unsigned* integers.
Those range from `[0, (2**64) - 1]`. So they are outside of the 64-bit *signed* integers from  [BSONs](https://bsonspec.org/spec.html) `"\x12" e_name int64 64-bit integer`.
Up to now pymongo rejects those immediately with an OverflowError so the application must deal with them.
For us this is pretty cumbersome, since we have a pretty complex structure and finding those large numbers would mean to 'traverse' through the whole document before giving it to pymongo.
Performance and code wise this is not very ideal so my thinking was:
To convert the document to BSON, pymongo must traverse the document anyway.
So lets handle this 'big integer' like any other unknown type and call the `fallback_encoder` (if given). 
Then let the …
=> PYTHON-3758 Support overflow integers in fallback_encoder.

.evergreen/resync-specs.sh, CONTRIBUTING.rst, doc/changelog.rst, pymongo/command_cursor.py, pymongo/database.py, test/run_command/unified/runCommand.json, test/run_command/unified/runCursorCommand.json, test/test_database.py, test/test_run_command.py, test/unified_format.py, tox.ini
Any failing tests should be due to unsupported use of cursorType as per the current API spec.
=> PYTHON-3588 Expose an API to create a cursor from a command response

.evergreen/config.yml, .evergreen/run-doctests.sh, .github/workflows/test-python.yml, RELEASE.rst, doc/index.rst, tox.ini
Using tox labels with `tox -m <label>` instantly fails if the label does not exist. This appears to be the best way to ensure that trying to run a nonexistent tox environment results in a command failure.
=> PYTHON-3793 Make tox fail with invalid environment

pymongo/srv_resolver.py
When using `mongodb+srv` DNS Seed List Connection String, I had no problems with the other drivers, but only when using the pymongo driver. 
The error is as follows 
```shell 
python3 main.py        
Traceback (most recent call last):  
  File "/Users/user/Workspace/tmp/pymongo-test/main.py", line 11, in <module>  
    client = pymongo.MongoClient(uri)  
             ^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/Users/user/Workspace/tmp/pymongo-test/venv/lib/python3.11/site-packages/pymongo/mongo_client.py", line 748, in __init__  
    res = uri_parser.parse_uri(  
          ^^^^^^^^^^^^^^^^^^^^^  
  File "/Users/user/Workspace/tmp/pymongo-test/venv/lib/python3.11/site-packages/pymongo/uri_parser.py", line 539, in parse_uri  
    nodes = dns_resolver.get_hosts()  
            …
```
=> PYTHON-3800 Add lower() to node when validate hosts of srv records

test/test_dns.py
https://jira.mongodb.org/browse/PYTHON-3800
This doesn't fully test to issue but it's a start. What we eventually want is to test the case where the hosts returned in the SRV record have uppercase letters but that will need to wait for https://jira.mongodb.org/browse/DRIVERS-2668.
=> PYTHON-3800 Add test for SRV URI with uppercase hostname

bson/_cbsonmodule.c
https://jira.mongodb.org/browse/PYTHON-3824
Manual testing shows the following results:
before:
```
python -m timeit -s 'from bson import encode;doc={"a": list((["a"], "b") for _ in range(1000))}' 'encode(doc)'
2000 loops, best of 5: 170 usec per loop
python -m timeit -s 'from bson import encode;doc={"a": list(range(1000))}' 'encode(doc)'
10000 loops, best of 5: 38.9 usec per loop
```
after:
```
python -m timeit -s 'from bson import encode;doc={"a": list((["a"], "b") for _ in range(1000))}' 'encode(doc)'
2000 loops, best of 5: 159 usec per loop
python -m timeit -s 'from bson import encode;doc={"a": list(range(1000))}' 'encode(doc)'
10000 loops, best of 5: 38.5 usec per loop
```
=> PYTHON-3824 Optimize BSON encoding of standard Python list and tuples

pymongo/ssl_support.py
https://jira.mongodb.org/browse/PYTHON-3865
=> PYTHON-3865 add types to ssl_support.py

pymongo/read_preferences.py, test/test_read_preferences.py
https://jira.mongodb.org/browse/PYTHON-3860
=> PYTHON-3860 add types to read_preferences.py

pymongo/client_options.py, pymongo/monitoring.py, pymongo/network.py, pymongo/server.py
https://jira.mongodb.org/browse/PYTHON-3809
=> PYTHON-3809 add types to monitoring.py

doc/changelog.rst
epic link: https://jira.mongodb.org/browse/PYTHON-3819
=> add bson encoding performance to 4.5 changelog

pymongo/topology_description.py
https://jira.mongodb.org/browse/PYTHON-3866
=> PYTHON-3866 add types to topology_description.py

pymongo/client_session.py, pymongo/hello.py, pymongo/mongo_client.py, pymongo/pool.py, pymongo/server_description.py, pymongo/settings.py, pymongo/topology.py, pymongo/typings.py, test/test_max_staleness.py, test/test_read_preferences.py, test/test_streaming_protocol.py
https://jira.mongodb.org/browse/PYTHON-3867
=> PYTHON-3867 add types to topology.py

bson/__init__.py, bson/binary.py, bson/code.py, bson/codec_options.py, bson/datetime_ms.py, bson/dbref.py, bson/decimal128.py, bson/json_util.py, bson/max_key.py, bson/min_key.py, bson/objectid.py, bson/raw_bson.py, bson/regex.py, bson/son.py, bson/timestamp.py, pymongo/_csot.py, pymongo/auth_aws.py, pymongo/change_stream.py, pymongo/collation.py, pymongo/collection.py, pymongo/event_loggers.py, pymongo/ocsp_cache.py, pymongo/topology.py, tools/ocsptest.py, tox.ini
Added the flag to the tox.ini file and fixed any untyped defs that came up as a result of this changed
https://jira.mongodb.org/browse/PYTHON-3907
=> PYTHON-3907 add --disallow-untyped-defs for mypy

bson/__init__.py, pymongo/collection.py, test/test_typing.py
https://jira.mongodb.org/browse/PYTHON-3821
=> PYTHON-3821 use overload pattern for _DocumentType

.evergreen/run-mongodb-oidc-test.sh, pymongo/helpers.py, test/__init__.py
https://jira.mongodb.org/browse/PYTHON-3909
=> PYTHON-3909 Fix OIDC reauth for bulk write operations

test/unified_format.py
Old ticket whereby our tests still mitigated failures by setting "upsert" and "multi" values if unset in order to pass our spec tests. Thankfully, the spec tests now specify the flag `$$unsetOrMatches` which relieves the burden of needing to add in this piece.
- Passes our tests
=> PYTHON-1744: Clean-Up, remove setdefault on multi/upsert calls

.evergreen/config.yml, test/test_on_demand_csfle.py
Relies on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/354
=> PYTHON-3942 Use MongoDB managed Azure KMS credentials

doc/examples/gevent.rst, test/test_change_stream.py, tox.ini
I verified that the test passes in 6.0.x and 7.0.x and is skipped in 6.3.x.
=> PYTHON-3985 [Build Failure] TestCollectionChangeStream.test_split_large_change

doc/tools.rst
It is no longer maintained, and the URL has been squatted.
=> PYTHON-3994 Remove link to MongoAlchemy

doc/examples/custom_type.rst, doc/faq.rst, pymongo/encryption.py, pymongo/results.py, test/test_results.py
https://jira.mongodb.org/browse/PYTHON-1424
Examples:
```python
>>> client.t.t.insert_one({})
InsertOneResult(ObjectId('65319acdd55bb3a27ab5502b'), acknowledged=True)
>>> client.t.t.insert_many([{} for _ in range(3)])
InsertManyResult([ObjectId('65319af2d55bb3a27ab5502c'), ObjectId('65319af2d55bb3a27ab5502d'), ObjectId('65319af2d55bb3a27ab5502e')], acknowledged=True)
>>> client.t.t.delete_one({})
DeleteResult({'n': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1697749775, 3), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1697749775, 3)}, acknowledged=True)
>>> client.t.t.update_one({}, {'$set': {'a': 1}})
UpdateResult({'nModified': 1, 'n': 1, 'ok': 1.0, '$clusterTime': …
```
=> PYTHON-1424 Add repr to write result classes

test/test_client.py
https://jira.mongodb.org/browse/PYTHON-3747
See also https://jira.mongodb.org/browse/PYTHON-3529 and https://jira.mongodb.org/browse/PYTHON-1532. Comparing the full document is flaky, instead let's just make sure they have the expected fields.
=> PYTHON-3747 Fix flaky test_list_databases

doc/changelog.rst, pymongo/uri_parser.py, test/connection_string/test/invalid-uris.json, test/connection_string/test/valid-options.json
https://jira.mongodb.org/browse/PYTHON-3962
Also added some changelog entries that were missing.
=> PYTHON-3962 Make delimiting slash between hosts and options optional

.evergreen/check-c-extensions.sh, .evergreen/run-perf-tests.sh, .evergreen/run-tests.sh, setup.py, tox.ini
https://jira.mongodb.org/browse/PYTHON-3968
=> PYTHON-3968 Allow pymongo to be installed in tox when C extension fails to build

.pre-commit-config.yaml, CONTRIBUTING.rst, doc/changelog.rst, doc/developer/periodic_executor.rst, doc/examples/authentication.rst, doc/examples/datetimes.rst, doc/examples/server_selection.rst, doc/examples/timeouts.rst, doc/examples/type_hints.rst, doc/faq.rst, doc/migrate-to-pymongo4.rst, tox.ini
Most of the caught errors where missing double backticks.
=> PYTHON-4012 Adopt more RST static checks

doc/changelog.rst, doc/examples/index.rst, doc/examples/network_compression.rst, doc/installation.rst, pymongo/mongo_client.py
https://jira.mongodb.org/browse/PYTHON-3930
=> PYTHON-3930 Add docs page for network compression

pymongo/mongo_client.py, test/mockupdb/test_cursor.py
TICKET: https://jira.mongodb.org/browse/PYTHON-4038
Pymongo is retrying a failed find connection ONCE that has a 0 or NoneType error code. 
This is undesired behavior because if, theoretically, we introduce an error type that does not have an error code but is an instance of an `OperationFailure`, we will mistakenly retry leading to unexpected consequences.
Added 3 tests: 
- Test nonetype case
- Test 0 case 
- Test 1 case
=> PYTHON-4038: Ensure retryable read `OperationFailure`s re-raise exception when 0 or NoneType error code is provided. 

doc/changelog.rst
I will backport to the v4.6 branch as well.
=> PYTHON-4043 Add changelog entry for 4.6.1

pymongo/mongo_client.py, test/mockupdb/test_cursor.py
(cherry picked from commit 0ff6a87438fd9a324a8bfee198f9906183cc51d5)
=> PYTHON-4038 [v4.6]: Ensure retryable read `OperationFailure`s re-raise exception when 0 or NoneType error code is provided.  (#1425)

.evergreen/perf.yml, .evergreen/run-perf-tests.sh
[PYTHON-3823](https://jira.mongodb.org/browse/PYTHON-3823) Migrate perf testing to rhel90-dbx-perf-large, Python 3.10.4, MongoDB 6.0.6.
=> PYTHON-3823 Migrate perf testing to rhel90-dbx-perf-large, Python 3.10.4, MongoDB 6.0.6

test/performance/perf_test.py
[PYTHON-3823](https://jira.mongodb.org/browse/PYTHON-3823) While working on this project I realized that almost all of the data_sizes were incorrect. Instead of hardcoding them I decided to dynamically calculate the data size where it was straightforward to do so.
For example:
- TestDeepEncoding/Decoding the data size is actually 19660000, not 19640000.
- TestFlatEncoding/Decoding the data size is actually 60460000, not 75310000.
- TestFullEncoding/Decoding the data size is actually 40260000, not 57340000.
- TestFindOneByID/TestFindManyAndEmptyCursor the data size is actually 15310000, not 16220000.
- TestSmallDocInsertOne/TestSmallDocBulkInsert the data size is actually 2500000, not 2750000.
- TestLargeDocInsertOne/TestLargeDocBulkInsert the data size is actually 25000640, not 27310890. …
=> PYTHON-3823 Audit benchmark data_size and calculate dynamically it where possible

.gitignore
One line change to `.gitignore`. xunit-results/ and test/xunit-results/ can be safely ignored. I imagine everyone has some hack to ignore them already. It's nice to be able to `git add .` :)
=> PYTHON-4055 Add xunit-results to .gitignore

tox.ini
https://jira.mongodb.org/browse/PYTHON-4070
If not configured correctly, tox fails to find setuptools, and thus cannot run core commands like `tox -m test`.  I could reproduce this a couple ways - using pipx and using brew. Adding setuptools as a dependency in tox.ini sidesteps any further setup work and confusion. No need to change onboarding docs either.
=> PYTHON-4070 Add setuptools as dep for test target

README.md, pyproject.toml
Also updates the Project [URLs](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls) that will be rendered on PyPI since we're removing a couple links from the readme.
=> PYTHON-4103 Add badges to README

test/retryable_reads/unified/exceededTimeLimit.json
…for reads
ExceededTimeLimit, Code 262 had already been added to pymongo.helpers._RETRYABLE_ERROR_CODES.
This simply adds the test. Exact same unified json as used in the C driver used for reference: 
https://github.com/mongodb/mongo-c-driver/pull/1482/files#diff-d96d8295b32780116338ab4eacb607f962ac00cbb900b17667493e8ec2072eac
=> PYTHON-4015 Add test that ExceededTimeLimit is a retryable exception for reads

pymongo/helpers.py, test/retryable_reads/unified/readConcernMajorityNotAvailableYet.json, test/test_retryable_reads_unified.py
Follows [DRIVERS-926](https://jira.mongodb.org/browse/DRIVERS-926). See JIRA(s) for details.
=> PYTHON-4016 making ReadConcernMajorityNotAvailableYet a retryable error

bson/json_util.py, doc/changelog.rst, test/test_json_util.py
https://jira.mongodb.org/browse/PYTHON-4142
=> PYTHON-4142 json_util.default should always convert Int64

bson/json_util.py
https://jira.mongodb.org/browse/PYTHON-4143
Explanation:
Previously, when our default() method would encounter an object of type int, float, str, or None it would go through every isintance if/else check, reach the bottom, raise a TypeError, then `_json_convert` would catch the TypeError and return the object. This is extremely wasteful and it's much faster to simply return the object when we know it's one of these types.
=> PYTHON-4143 Optimize JSON encoding of int, float, str, and None

bson/__init__.py, bson/json_util.py, test/test_bson.py, test/test_json_util.py
https://jira.mongodb.org/browse/PYTHON-4144
Beanchmark results here: https://spruce.mongodb.com/task/mongo_python_driver_perf_tests_perf_6.0_standalone_patch_cd3f502de6405657c1e825978ec13b295b0d76ef_65a70b9257e85a54e3540958_24_01_16_23_05_08/trend-charts?execution=0
Results in a 15% improvement to the JSON benchmarks.
Before:
```
$ python -m timeit -s 'from bson.json_util import dumps,loads;doc={"a": list(float(i) for i in range(100000))}' 'dumps(doc)'
10 loops, best of 5: 39 msec per loop
```
After:
```
$ python -m timeit -s 'from bson.json_util import dumps,loads;doc={"a": list(float(i) for i in range(100000))}' 'dumps(doc)'
10 loops, best of 5: 31.1 msec per loop
```
=> PYTHON-4144 Optimize json_util performance using single dispatch table

.evergreen/config.yml, test/__init__.py, test/performance/perf_test.py, test/test_read_preferences.py
https://jira.mongodb.org/browse/PYTHON-4155
https://spruce.mongodb.com/task/mongo_python_driver_perf_tests_perf_6.0_standalone_ssl_patch_c4e4bd638f7b82032cbd13b8e56a7593b56e964c_65aafe9ad1fe07c55152cba2_24_01_19_22_58_36/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC 
Results:
test | no-ssl MB/s | ssl MB/s | diff %
-- | -- | -- | --
GridFsMultiFileDownload | 2241.312311 | 1390.521729 | -37.95948373
GridFsMultiFileUpload | 587.071831 | 560.0242854 | -4.607195274
JsonMultiExport | 81.56780701 | 79.51976841 | -2.510841797
JsonMultiImport | 243.055593 | 235.5447564 | -3.090172317
GridFsDownload | 609.4982366 | 393.7977959 | -35.38983836
GridFsUpload | 338.6111882 | 252.5824448 | -25.40634992
LargeDocBulkInsert | 104.5846324 | 94.05588566 | -10.06720249
SmallDocBulkInsert | 38.57742683 | …
=> PYTHON-4155 Run perf tests with TLS enabled

doc/compatibility-policy.rst, doc/tools.rst
https://jira.mongodb.org/browse/PYTHON-4157
=> PYTHON-4157 Fix broken links

pymongo/collection.py
change a minuscule typo which formats a code part in the docs wrong
basically adds one space. I know it is a small change but it bothered me ;)
=> PYTHON-4158 Fix typo in create_index docstring

test/test_encryption.py
https://jira.mongodb.org/browse/PYTHON-4170
=> PYTHON-4170 Fix test_invalid_hostname_in_kms_certificate

.evergreen/run-tests.sh, test/test_encryption.py
Fixes these failures:
```
[2024/01/30 13:28:18.641] test/unified_format.py:1722: in run_scenario
[2024/01/30 13:28:18.641]     self._run_scenario(spec, uri)
[2024/01/30 13:28:18.641] test/unified_format.py:1747: in _run_scenario
[2024/01/30 13:28:18.641]     self.run_operations(spec["operations"])
[2024/01/30 13:28:18.641] test/unified_format.py:1656: in run_operations
[2024/01/30 13:28:18.641]     self.run_entity_operation(op)
[2024/01/30 13:28:18.641] test/unified_format.py:1398: in run_entity_operation
[2024/01/30 13:28:18.641]     result = cmd(**dict(arguments))
[2024/01/30 13:28:18.641] /opt/python/pypy3.10/lib/pypy3.10/functools.py:303: in __call__
[2024/01/30 13:28:18.641]     return self.func(*self.args, *args, **keywords)
[2024/01/30 13:28:18.641] test/unified_format.py:1278: in …
```
=> PYTHON-4112 Revert to testing with pymongocrypt@master

pymongo/encryption.py, test/test_encryption.py
Modify the ClientEncryption.encrypt API to accept native UUIDs directly. [jira task](https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-2267)
I validated my changes with the TestExplicitSimple cases. pytest -v -s test/test_encryption.py::TestExplicitSimple
I tried to run all the test_encryption.py tests, but some of the tests require environment credentials, and as far as I understand, I need MongoDB Enterprise for mongocryptd support.
=> PYTHON-2267: Allow UUID key_id to be passed to ClientEncryption.encrypt

bson/json_util.py, doc/contributors.rst
Optimized performance by removing object_pairs_hook call if we need the default conversion to dict behavior [jira task](https://jira.mongodb.org/projects/PYTHON/issues/PYTHON-1374)
In object_hook, a dictionary is already passed, and calling object_pairs_hook for casting pairs to dict is redundant.
I validated my changes with test_json_util cases. `pytest -v -s test/test_json_util.py`
Compare performance with TestJson*Decoding cases(changes affect performance only in these cases) `pytest -v -s test/performance/perf_test.py::TestJsonFlatDecoding test/performance/perf_test.py::TestJsonDeepDecoding test/performance/perf_test.py::TestJsonFullDecoding`
| Test Name        | master | current branch        |
|------------------|------------------|--------------------|
| JsonFlatDecoding | …
=> PYTHON-4179: Optimize JSON decoding performance by avoiding object_pairs_hook

doc/changelog.rst, pymongo/encryption.py, test/test_encryption.py
https://jira.mongodb.org/browse/PYTHON-2267
Small follow up to https://github.com/mongodb/mongo-python-driver/pull/1494
=> PYTHON-2267 Test passing UUID to encrypt_expression

test/test_json_util.py
https://jira.mongodb.org/browse/PYTHON-4179
Small follow up to https://github.com/mongodb/mongo-python-driver/pull/1493
=> PYTHON-4179 Verify document_class type in json_util.loads test

.evergreen/run-tests.sh, bson/json_util.py, test/performance/perf_test.py
[PYTHON-4204](https://jira.mongodb.org/browse/PYTHON-4204) Optimize JSON decoding using lookup table to find $ keys.
This change improves JSON decoding by 20-50%+:
https://spruce.mongodb.com/task/mongo_python_driver_perf_tests_perf_6.0_standalone_patch_698599c737925ccac5c27cc58bb48b2692c74e30_65c2ad625623431a4f5596c5_24_02_06_22_06_33/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC
I also tested set intersection but the for-loop approach performs better:
```python
def object_hook(dct: Mapping[str, Any], json_options: JSONOptions = DEFAULT_JSON_OPTIONS) -> Any:
matches = set(dct) & _PARSERS_SET
if matches:
return _PARSERS[matches.pop()](dct, json_options)
return dct
```
=> PYTHON-4204 Optimize JSON decoding using lookup table to find $ keys

test/test_monitor.py
Leveraged the [shlex.split](https://docs.python.org/3/library/shlex.html#shlex.split) command to get my shell output as a proper list of args. It gave me: ` [sys.executable, "-c", '"from pymongo import MongoClient; c = MongoClient()"']`
Tested Output on MacOS when commenting out RuntimeError catch:
```python
test/test_monitor.py::TestMonitor::test_no_thread_start_runtime_err_on_shutdown FAILED                                                                                                                                                                                                                                                                                                 [100%]
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> …
```
=> PYTHON-4147-fix: Remove quote wrapping and remove shell=true usage

pymongo/collection.py, pymongo/operations.py, test/index_management/createSearchIndex.json, test/index_management/createSearchIndexes.json, test/test_index_management.py
Python implementation for [DRIVERS-2768](https://jira.mongodb.org/browse/DRIVERS-2768).
=> PYTHON-4208 [Vector Search GA] Add support for types in search index creation

doc/changelog.rst, pymongo/collection.py, pymongo/operations.py, test/test_index_management.py
https://jira.mongodb.org/browse/PYTHON-4297
=> PYTHON-4297 Allow passing arbitrary index options to create_search_index

test/unified_format.py
Addresses Astrolabe failure: https://spruce.mongodb.com/task/drivers_atlas_testing_tests_python__driver~pymongo_master_platform~ubuntu_22.04_runtime~python39_atlas_retryWrites_resizeCluster_6603d586d05b2a00076119d2_24_03_27_08_15_02/logs?execution=0
=> PYTHON-2723 Make mongos_clients a class property

bson/_cbsonmodule.c
Fixes a mistake in PYTHON-4285. Note there's still no bug here since `state` will never be null. We are adding the check because it's harmless and Coverity flagged it (even though it's a false positive).
=> PYTHON-4285 Fix PyModule_GetState check

.evergreen/config.yml, .evergreen/run-mongodb-oidc-test.sh, .evergreen/run-tests.sh, test/auth_oidc/test_auth_oidc.py
Requires https://github.com/mongodb-labs/drivers-evergreen-tools/pull/426
=> PYTHON-4309 OIDC Atlas Testing Updates

pymongo/topology_description.py
Fix for TypeError caused by substraction between nulls when round_trip_time is None
```python
return [
>       s for s in selection.server_descriptions if (s.round_trip_time - fastest) <= threshold
]
E   TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```
Jira ticket: https://jira.mongodb.org/browse/PYTHON-4298
Linked to previous PR https://github.com/mongodb/mongo-python-driver/pull/1361
=> PYTHON-4298 Fix _apply_local_threshold TypeError

test/performance/perf_test.py
Reduce max benchmark time to 60 seconds and increase min time to 30 seconds.
Also introduces a new FASTBENCH setting to the benchmarks more quickly:
```
$ FASTBENCH=1 python test/performance/perf_test.py -v TestDeepEncoding
runTest (__main__.TestDeepEncoding.runTest) ... Completed TestDeepEncoding 179.236 MB/s, MEDIAN=0.011s, total time=0.100s, iterations=9
```
VS without:
```
$ python test/performance/perf_test.py -v TestDeepEncoding
runTest (__main__.TestDeepEncoding.runTest) ... Completed TestDeepEncoding 181.506 MB/s, MEDIAN=0.108s, total time=30.103s, iterations=277
```
https://jira.mongodb.org/browse/PYTHON-4350
=> PYTHON-4350 Faster and more consistent performance benchmark execution times

test/unified_format.py
See JIRA for details and link to patches that show the errors.
These failures will be fixed pending the tickets that are referred to in test/unified_format.py: [PYTHON-4303] and [PYTHON-4227].
=> PYTHON-4303 Temporarily skip two transaction tests

test/__init__.py, test/test_command_logging.py, test/unified_format.py
The green framework failures were actually due to `ocsp_support` logging non-JSON messages. Our test framework expects all logs to be in JSON format, so I've added a check to exclude `ocsp_support` logs from test verification.
=> PYTHON-4354 & PYTHON-4355 - Increase logging limit for tests

doc/migrate-to-pymongo4.rst
https://jira.mongodb.org/browse/PYTHON-4371
```python
>>> client.db.list_collection_names(filter={"name": {"$regex": r"^(?!system\\.)"}})
['coll', 'system.views', 'time', 'system.buckets.time', 'view']
>>> client.db.list_collection_names(filter={"name": {"$regex": "^(?!system\\.)"}})
['coll', 'time', 'view']
```
=> PYTHON-4371 Fix include_system_collections example in migration guide

.github/dependabot.yml
Dependabot will check all of our requirements*.txt files once a week and raise PRs if it sees any CVEs that need to be addressed.  The PR description will show the linked vulnerability for authenticated, and just the version bump publicly.
=> PYTHON-4363 Add dependabot config for Python

test/unified_format.py
After initialData is added in test.unified_format's run_scenario, we get the $clusterTime from the server, and add this to each of the ClientSession entities before further operations.
[DRIVERS-2816](https://jira.mongodb.org/browse/DRIVERS-2816)
[Here is the pertinent section of the specifications](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.md?plain=1#L2987-L2998)
=> PYTHON-4227 Unified tests: Advance cluster_time of ClientSessions after initialData creation

doc/changelog.rst
(cherry picked from commit 29f4d5cf8952b1abe0a73b11631ff84818b7f9ed)
=> PYTHON-4429 Add Changelog for 4.7.2

.evergreen/config.yml
Also clean up the OIDC tasks a bit - rename, and mark as `test`.
=> PYTHON-4447 Use 8.0 for local OIDC server

pymongo/change_stream.py
As per https://jira.mongodb.org/browse/JAVA-2987 and https://jira.mongodb.org/browse/NODE-2022
If `start_at_operation_time` was supplied to `watch` and the first event is an invalidate, or connection timeout, or anything that triggers an automatic retry - a `pymongo.errors.OperationFailure` is thrown with the message "Only one type of resume option is allowed, but multiple were found"
The solution from those other issues have been mimicked in this PR
Jira link: https://jira.mongodb.org/browse/PYTHON-4449
=> PYTHON-4449 Ensure resume options aren't combined during automatic retry

bson/binary.py, doc/changelog.rst, doc/contributors.rst
[PYTHON-4468](https://jira.mongodb.org/browse/PYTHON-4468)
I noticed the `bson.binary.Binary` type include it's
value even when the subtype is sensitive (8)
This PR changes the Binary type's repr to be `<Binary ### {self.__subtype}>` when the subtype is 8.
The `< >` representation follow [general guideline](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_repr) that when a repr can't be roundtripped by `eval` it should use `< >` instead of a constructor like syntax.
=> PYTHON-4468 Hide the value of sensitive subtype binary objects

pymongo/mongo_client.py
https://jira.mongodb.org/browse/PYTHON-4473
=> PYTHON-4473 Optimize find/aggregate/command by avoiding duplicate calls to _get_topology

doc/changelog.rst, pymongo/topology.py, test/server_selection_logging/operation-id.json, test/server_selection_logging/replica-set.json, test/server_selection_logging/sharded.json, test/server_selection_logging/standalone.json
(cherry picked from commit cdf04ffa183082eff35a6fbe318d0b68d56845f2)
=> PYTHON-4261 [v4.7] Reduce verbosity of "Waiting for suitable server to become available" log message

.evergreen/build-manylinux-internal.sh, .evergreen/build-manylinux.sh, .evergreen/build-windows.sh, .evergreen/combine-coverage.sh, .evergreen/config.yml, .evergreen/run-tests.sh, .evergreen/utils.sh, .github/workflows/release-python.yml, .github/workflows/test-python.yml, CONTRIBUTING.md, README.md, doc/changelog.rst, doc/faq.rst, doc/installation.rst, doc/python3.rst, pymongo/pool.py, pyproject.toml
(cherry picked from commit 42f45034f387280840fecb54b1260d80d464024a)
=> PYTHON-4372 & PYTHON-4378 [v4.8] Deprecate Python 3.7 and Update supported PyPy Versions to 3.9 and 3.10

pymongo/asynchronous/bulk.py, pymongo/asynchronous/client_session.py, pymongo/asynchronous/message.py, pymongo/asynchronous/mongo_client.py, pymongo/asynchronous/pool.py, pymongo/asynchronous/topology.py, pymongo/synchronous/client_session.py, pymongo/synchronous/mongo_client.py, pymongo/synchronous/topology.py
https://jira.mongodb.org/browse/PYTHON-4482
Still todo:
```
(pymongo-py39) ➜  mongo-python-driver git:(PYTHON-4482) python bench-command.py 1  
Python: 3.9.13, PyMongo: 4.8.0.dev0, MongoDB: 5.0.15
Running 10000 operations across 1 thread(s)
command: 1.32s
find_one: 1.93s
insert_one: 1.84s
(pymongo-py39) ➜  mongo-python-driver git:(PYTHON-4482) python bench-command.py 100
Python: 3.9.13, PyMongo: 4.8.0.dev0, MongoDB: 5.0.15
Running 10000 operations across 100 thread(s)
command: 1.22s
find_one: 1.52s
insert_one: 1.35s
```
VS master:
```
(pymongo-py39) ➜  mongo-python-driver git:(master) python bench-command.py 1
Python: 3.9.13, PyMongo: 4.8.0.dev0, MongoDB: 5.0.15
Running 10000 operations across 1 thread(s)
command: 1.36s
find_one: 1.95s
insert_one: 1.90s
(pymongo-py39) ➜ …
```
=> PYTHON-4347 Make _ServerSessionPool lock-free and still thread safe

pymongo/client_session.py, pymongo/command_cursor.py, pymongo/mongo_client.py, pymongo/topology.py
(cherry picked from commit 8c35d1e481ed9e2990ac9fbc42d2fa2a0d8e8c44)
Backporting to 4.8 so this can get out sooner. 
https://jira.mongodb.org/browse/PYTHON-4482
=> PYTHON-4482 Improve performance by making _ServerSessionPool lock-free (#1660)

pymongo/ssl_support.py
(cherry picked from commit 4ec79fbde7fc91f3a3c54b89242abf9563e3f772)
Backport of https://github.com/mongodb/mongo-python-driver/pull/1669
=> PYTHON-4492 [v4.8] Fallback to stdlib ssl when pyopenssl import fails with AttributeError

pymongo/asynchronous/mongo_client.py, pymongo/synchronous/mongo_client.py
https://jira.mongodb.org/browse/PYTHON-4347
This regression should have been caught in the original PR but some of the fork() tests were accidentally disabled in PYTHON-4264:
```python
@unittest.skip("testing")
def test_topology_reset(self):
```
We'll open another PR to re-enable those tests.
=> PYTHON-4347 Ensure client can be opened after fork()

.evergreen/run-tests.sh
(cherry picked from commit 2b03001)
=> PYTHON-4497 [v4.8] Fix handling of Python executable in run-tests

.evergreen/run-import-time-test.sh, .evergreen/run-mod-wsgi-tests.sh
(cherry picked from commit fe0faf74a6a408b492e0e7f77de2f985c5d68f63)
=> PYTHON-4504 [v4.8] Update mod_wsgi test to not call setup.py (#1684)

test/test_bson.py
https://jira.mongodb.org/browse/PYTHON-4323
Here's how this test fails on pymongo 4.6.0:
```
FAIL: test_bad_code (__main__.TestBSON.test_bad_code)
bson.errors.InvalidBSON: Detected unknown BSON type b'\x00' for fieldname '00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'. Are you using the latest driver version?
During handling of the above exception, another exception occurred:
File "/Users/shane/git/mongo-python-driver/test/test_bson.py", line 516, in test_bad_code
with self.assertRaisesRegex(InvalidBSON, "invalid") as ctx:
AssertionError: "invalid" does not match "Detected unknown BSON …
```
=> PYTHON-4323 Add regression test for out-of-bounds read when decoding invalid bson

.github/workflows/codeql.yml, .github/workflows/dist.yml, .github/workflows/release-python.yml, pyproject.toml
(cherry picked from commit https://github.com/mongodb/mongo-python-driver/commit/25cbc7e2a5f6d97fd37ce34b2a06e4071181fc4e)
=> PYTHON-4388 [v4.8] Add SSDLC workflows

pymongo/asynchronous/pool.py, pymongo/synchronous/pool.py, test/test_client.py
This PR adds to the existing pymongo client metadata truncation logic by truncating the `DriverInfo` name and version fields. It also introduces tests to validate this metadata truncation.
=> PYTHON-2052 Truncate client metadata document to 512 bytes

doc/changelog.rst, setup.py
https://jira.mongodb.org/browse/PYTHON-4507
=> PYTHON-4507 pip>=21.3 is required for editable installs

doc/changelog.rst, pymongo/asynchronous/encryption.py, pymongo/encryption_options.py, pymongo/synchronous/encryption.py, requirements/encryption.txt
Attempting to use pymongo with an outdated version of pymongocrypt now correctly raises this error:
```python
raise ConfigurationError(
"client-side field level encryption requires the pymongocrypt "
"library: install a compatible version with: "
"python -m pip install --upgrade 'pymongo[encryption]'"
)
```
https://jira.mongodb.org/browse/PYTHON-4529
=> PYTHON-4529 Require pymongocrypt>=1.10

test/asynchronous/__init__.py
https://jira.mongodb.org/browse/PYTHON-4538
Note that the SSL tests are still failing due to https://jira.mongodb.org/browse/PYTHON-4539.
=> PYTHON-4538 await _check_user_provided

.evergreen/run-tests.sh, .github/workflows/test-python.yml
https://jira.mongodb.org/browse/PYTHON-4558
=> PYTHON-4558 Fix coverage and XML results for async tests

pymongo/uri_parser.py, test/test_uri_parser.py
https://jira.mongodb.org/browse/PYTHON-4588
An invalid port could include part of the user's password so we should avoid including it in the error message.
=> PYTHON-4588 Don't include invalid port in URI parsing error message

doc/async-tutorial.rst, doc/index.rst, requirements/docs.txt
We can't run `doctest` on the async tutorial because `doctest` doesn't support running async code in the Python REPL.
=> PYTHON-4571 - Add async examples to PyMongo's tutorial

doc/contributors.rst, pymongo/_csot.py, pymongo/asynchronous/monitor.py, pymongo/read_preferences.py, pymongo/synchronous/monitor.py
Hello,
This fixes this long standing issue that's been opened since 2017
https://jira.mongodb.org/browse/PYTHON-1271
https://jira.mongodb.org/browse/PYTHON-3616
https://jira.mongodb.org/browse/PYTHON-4298
We've been getting regular failures from the mongo client in CI, since updating to a more recent python and mongo client.
Symptom is the client crashing with round_trip_time of None.
This is a very long standing issue as we've found bug tickets going back to 2017 regarding this problem.
Oddly enough, we did not see that frequently on older python version and older client, although the bug is present. I suspect there's a subtle side effect from python 3.11+ being noticeably faster, which makes it a lot more common to get sub millisecond measurements.
root cause:
After many days of …
=> PYTHON-4600 Handle round trip time being negative because time.monotonic() is not monotonic

pymongo/asynchronous/topology.py, pymongo/synchronous/topology.py
Small fix for PYTHON-4021 which resolves this test failure:
```
self = <test.test_discovery_and_monitoring.TestUnifiedReplicasetEmitTopologyChangedBeforeClose testMethod=test_Topology_lifecycle>
def test_case(self):
>       self.run_scenario(spec)
test/unified_format.py:1953: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/unified_format.py:1897: in run_scenario
self._run_scenario(spec, uri)
test/unified_format.py:1936: in _run_scenario
self.check_events(expect_events) …
```
=> PYTHON-4021 Fix previous topologyDescription published when closing a client

test/unified_format.py
PYTHON-4609
Explanation: The legacy test runner has this code:
```python
class SpecRunner(IntegrationTest):
...
@classmethod
def _setup_class(cls):
...
cls.knobs = client_knobs(heartbeat_frequency=0.1, min_heartbeat_interval=0.1)
cls.knobs.enable()
```
=> PYTHON-4609 Speed up unified tests

pymongo/ocsp_cache.py, pymongo/ocsp_support.py
=> PYTHON-4611 Prefer non deprecated cryptography apis

test/asynchronous/test_cursor.py, test/test_cursor.py
=> PYTHON-4610 More robust to_list tests

test/test_change_stream.py, test/test_custom_types.py, test/test_examples.py, test/test_sdam_monitoring_spec.py
PYTHON-4633 Speed up TestCollectionChangeStream.test_uuid_representations
Also speeds up a few other slow change stream and SDAM tests.
=> PYTHON-4633 Speed up TestCollectionChangeStream.test_uuid_representations

.evergreen/combine-coverage.sh, .evergreen/config.yml, .evergreen/hatch.sh, .evergreen/utils.sh
Since we're using hatch for testing, and hatch requires cryptography.
=> PYTHON-4614 Do not test PyPy with OpenSSL 1.0.2

bson/objectid.py
PYTHON-4640.
Results before:
```
$ python bench-objectid.py         
Python: 3.12.4, PyMongo: 4.9.0.dev0
Creating 1000000 ObjectIds with 1 thread
run_threaded: 0.85s
Creating 1000000 ObjectIds across 100 threads
run_threaded: 5.25s
```
Results after:
```
$ python bench-objectid.py
Python: 3.12.4, PyMongo: 4.9.0.dev0
Creating 1000000 ObjectIds with 1 thread
run_threaded: 0.77s
Creating 1000000 ObjectIds across 100 threads
run_threaded: 0.78s
```
=> PYTHON-4640 Improve performance of creating ObjectIds with multiple threads

.evergreen/config.yml, test/test_csot.py, test/unified_format.py
=> PYTHON-4649 Skip CSOT tests on slow Windows and macOS hosts

test/__init__.py, test/asynchronous/__init__.py, test/asynchronous/test_client_bulk_write.py, test/test_client_bulk_write.py
[PYTHON-4650](https://jira.mongodb.org/browse/PYTHON-4650)
=> PYTHON-4650 Fix MongoClient.bulk_write test failure when compression is enabled

pymongo/network_layer.py, pymongo/pyopenssl_context.py
PYTHON-4659 
Previously the async code path was resending the first 16KB bytes (the max TLS record size) of the buffer over and over.
=> PYTHON-4659 Fix async with TLS

pymongo/message.py
[PYTHON-4596](https://jira.mongodb.org/browse/PYTHON-4596)
=> PYTHON-4596 Only encode each operation document once for MongoClient.bulk_write

.evergreen/run-tests.sh
I verified that the tests are now properly running in this build: https://spruce.mongodb.com/version/66c3f93699b1c20007a60805/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-4656 Fix running of enterprise auth tests

test/asynchronous/test_client_bulk_write.py, test/command_monitoring/unacknowledged-client-bulkWrite.json, test/crud/unified/client-bulkWrite-delete-options.json, test/crud/unified/client-bulkWrite-errorResponse.json, test/crud/unified/client-bulkWrite-errors.json, test/crud/unified/client-bulkWrite-mixed-namespaces.json, test/crud/unified/client-bulkWrite-options.json, test/crud/unified/client-bulkWrite-ordered.json, test/crud/unified/client-bulkWrite-results.json, test/crud/unified/client-bulkWrite-update-options.json, test/crud/unified/client-bulkWrite-update-pipeline.json, test/retryable_writes/unified/client-bulkWrite-clientErrors.json, test/retryable_writes/unified/client-bulkWrite-serverErrors.json, test/retryable_writes/unified/handshakeError.json, test/server_selection_logging/operation-id.json, test/test_client_bulk_write.py, test/transactions/unified/client-bulkWrite.json, test/versioned-api/crud-api-version-1.json
[PYTHON-4671](https://jira.mongodb.org/browse/PYTHON-4671)
This PR skips the `client.bulk_write` spec and prose tests from running on Atlas Serverless. 
See [this PR](https://github.com/mongodb/specifications/pull/1636) for the spec test changes.
=> PYTHON-4671 Skip client.bulk_write tests on Atlas Serverless

bson/tz_util.py, doc/changelog.rst, test/test_bson.py
PYTHON-4690
Motivation:
When working with multiple timezones, this change makes it easier to see which ones are being used.
Before:
```python
>>> from bson.tz_util import FixedOffset, utc
>>> utc
<bson.tz_util.FixedOffset object at 0x104ec2840>
>>> FixedOffset(60, 'tzName')
<bson.tz_util.FixedOffset object at 0x104b0cc20>
```
After:
```python
>>> from bson.tz_util import FixedOffset, utc
>>> utc
FixedOffset(datetime.timedelta(0), 'UTC')
>>> FixedOffset(60, 'tzName')
FixedOffset(datetime.timedelta(seconds=3600), 'tzName')
```
Related to PYTHON-4663.
=> PYTHON-4690 Add repr for FixedOffset eg FixedOffset(datetime.timedelta(seconds=3600), '+60'))

bson/datetime_ms.py, test/test_bson.py
PYTHON-4691 Fix non-UTC timezones with DATETIME_CLAMP/DATETIME_AUTO
=> PYTHON-4691 Fix non-UTC timezones with DATETIME_CLAMP/DATETIME_AUTO

doc/changelog.rst, pymongo/asynchronous/encryption.py, pymongo/synchronous/encryption.py, test/client-side-encryption/spec/legacy/fle2v2-Rangev2-Compact.json
=> PYTHON-4164 Document support for KMIP delegated master_key

test/asynchronous/test_bulk.py
Honestly not sure what changed since [this PR](https://github.com/mongodb/mongo-python-driver/pull/1827) that would cause the tests to fail, because they weren't failing when I merged them...?
=> PYTHON-4730 Failing Async Bulk Tests

bson/_cbsonmodule.c
PYTHON-4663
First warning:
```
1. returned_null: PyModule_GetState returns NULL (checked 18 out of 19 times).
2. var_assigned: Assigning: state = NULL return value from PyModule_GetState.
389    struct module_state *state = GETSTATE(self);
```
Second:
```    	
CID 162119: (#2 of 2): Unintentional integer overflow (OVERFLOW_BEFORE_WIDEN)
overflow_before_widen: Potentially overflowing expression ((PyDateTime_Delta *)utcoffset)->days * 86400 with type int (32 bits, signed) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type int64_t (64 bits, signed).
To avoid overflow, cast either ((PyDateTime_Delta *)utcoffset)->days or 86400 to type int64_t.
417                min_millis_offset = (PyDateTime_DELTA_GET_DAYS(utcoffset) * 86400 +
418 …
```
=> PYTHON-4663 Fix coverity warnings in datetime decoding change

test/asynchronous/test_client.py, test/asynchronous/test_logger.py, test/test_client.py, test/test_logger.py, test/unified_format.py
PYTHON-4607 Use [LogRecord.getMessage()](https://docs.python.org/3/library/logging.html#logging.LogRecord.getMessage) not LogRecord.message
LogRecord.message is documented like this:
> The logged message, computed as msg % args. This is set when Formatter.format() is invoked.
It's not set until Formatter.format() or getMessage() is called which explains the `AttributeError: 'LogRecord' object has no attribute 'message'` errors we've been seeing.
=> PYTHON-4607 Use LogRecord.getMessage() not LogRecord.message

test/asynchronous/test_bulk.py, test/test_bulk.py
PYTHON-4560 Disable rsSyncApplyStop tests on 8.0+
=> PYTHON-4560 Disable rsSyncApplyStop tests on 8.0+

test/discovery_and_monitoring/rs/compatible.json, test/discovery_and_monitoring/rs/compatible_unknown.json, test/discovery_and_monitoring/sharded/compatible.json, test/discovery_and_monitoring/single/compatible.json, test/discovery_and_monitoring/single/too_old_then_upgraded.json, test/discovery_and_monitoring/unified/logging-loadbalanced.json
PYTHON-4735 Resync SDAM tests to fix TestUnifiedLoggingLoadbalanced
=> PYTHON-4735 Resync SDAM tests to fix TestUnifiedLoggingLoadbalanced

test/asynchronous/test_encryption.py, test/test_encryption.py
Asyncio and forking should not be mixed. I suspect the sync version was failing due to running after the async version caused a deadlock.
=> PYTHON-4738 - Make test_encryption.TestClientSimple.test_fork sync-only

pymongo/asynchronous/bulk.py, pymongo/asynchronous/client_bulk.py, pymongo/network_layer.py, pymongo/synchronous/bulk.py, pymongo/synchronous/client_bulk.py
PYTHON-4740 Convert asyncio.TimeoutError to socket.timeout for compat
Not exactly sure how to reliably test this since it's hard to cause a timeout on the send().
=> PYTHON-4740 Convert asyncio.TimeoutError to socket.timeout for compat

.evergreen/run-tests.sh
PYTHON-4769 Avoid pytest collection overhead when running perf benchmarks
=> PYTHON-4769 Avoid pytest collection overhead when running perf benchmarks

pymongo/__init__.py, pymongo/common.py, pymongo/pool_options.py, test/asynchronous/test_client.py, test/test_client.py, tools/synchro.py
- Move `has_c` to common
- If `has_c` in pool_options update driver metadata
- If `has_c` in tests update driver metadata
- Add c replacement string to synchro
=> PYTHON-1714 Add c extension use to client metadata

pymongo/asynchronous/pool.py, pymongo/asynchronous/topology.py, pymongo/lock.py, pymongo/synchronous/pool.py, pymongo/synchronous/topology.py, test/asynchronous/test_client.py, test/asynchronous/test_client_bulk_write.py, test/asynchronous/test_cursor.py, test/asynchronous/test_locks.py, test/test_client.py, test/test_client_bulk_write.py, test/test_cursor.py, test/test_server_selection_in_window.py, tools/synchro.py
PYTHON-4782 Fix deadlock and blocking behavior in _ACondition.wait
TODO:
=> PYTHON-4782 Fix deadlock and blocking behavior in _ACondition.wait

test/asynchronous/test_retryable_reads.py, test/test_retryable_reads.py, tools/synchro.py
Note: I made `test_pool_paused_error_is_retryable` require sync because it uses threads, we can consider changing it to tasks too though!
=> PYTHON-4789 Migrate test_retryable_reads.py to async

test/asynchronous/helpers.py, test/asynchronous/test_connections_survive_primary_stepdown_spec.py, test/helpers.py, test/test_connections_survive_primary_stepdown_spec.py, test/utils.py, tools/synchro.py
Note: I tried to add `async_ensure_all_connected` to `/test/asynchronous/helpers.py` but was running into some issues (circular imports I think?) so that's why I decided to just keep it in `test/utils.py` but happy to look into it again, if needed.
=> PYTHON-4805 Migrate test_connections_survive_primary_stepdown_spec.py to async

test/asynchronous/unified_format.py, test/unified_format.py, test/unified_format_shared.py
Testing with https://github.com/mongodb-labs/drivers-atlas-testing/pull/218
=> PYTHON-4862 Fix handling of interrupt_loop in unified test runner

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Programmatically creates OCSP build variants.  We cannot use `include:` with `matrix:`, so we'll have to convert all the matrices in-place before moving on to using generated files and generated tasks.
Before:
720 tasks across 42 build variants
After
200 tasks across 11 build variants
=> PYTHON-4838 Generate OCSP build variants using shrub.py

test/asynchronous/test_cursor.py, test/test_cursor.py
PYTHON-4866 Fix test_command_cursor_to_list_csot_applied
=> PYTHON-4866 Fix test_command_cursor_to_list_csot_applied

.evergreen/hatch.sh
PYTHON-4861 Fix HATCH_CONFIG on cygwin
=> PYTHON-4861 Fix HATCH_CONFIG on cygwin

.evergreen/config.yml, .evergreen/hatch.sh, .evergreen/run-tests.sh, .evergreen/scripts/generate_config.py
- Break up the test matrix to cover all server versions, python versions, platforms, topologies, and auth/ssl with as little repetition as possible
- Break up sync and async tests on MacOS and Windows
Before: 1026 tasks across 39 build variants
After: 495 tasks across 37 build variants
=> PYTHON-4868 Generate server tests using shrub.py

doc/changelog.rst, pymongo/operations.py, test/test_operations.py
For use with [django-mongodb](https://github.com/mongodb-labs/django-mongodb) e.g.
```
(.venv) alex.clark@Mac tmp.0F48BsWTyQ % python manage.py sqlmigrate auth 0001
System check identified some issues:
WARNINGS:
?: (staticfiles.W004) The directory '/private/var/folders/5t/d3llmfm54v3dg712_4pks3lm0000gn/T/tmp.0F48BsWTyQ/frontend/build' in the STATICFILES_DIRS setting does not exist.
--
-- Create model Permission
--
db.create_collection('auth_permission')
db.auth_permission.create_indexes([IndexModel({'name': 'auth_permission_content_type_id_2f476e4b', 'key': {'content_type_id': 1}})])
--
-- Create model Group
--
db.create_collection('auth_group')
db.create_collection('auth_group_permissions')
db.auth_group_permissions.create_indexes([IndexModel({'name': …
```
=> PYTHON-4834 Add __repr__ to IndexModel, SearchIndexModel

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Before: 288 tasks across 36 build variants
After: 78 tasks across 9 build variants
=> PYTHON-4879 Use shrub.py for compressor tests

pymongo/network_layer.py
PYTHON-4874 Fix async Windows KMS support
=> PYTHON-4874 Fix async Windows KMS support

.evergreen/config.yml, .evergreen/run-tests.sh, .evergreen/scripts/generate_config.py, pyproject.toml, test/asynchronous/test_auth.py, test/test_auth.py
Also added a marker for auth so we're not running the full test suite.
Before: 12 tasks across 12 build variants
After: 7 tasks across 7 build variants
=> PYTHON-4882 Use shrub.py for enterprise auth tests

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Before: 154 tasks across 26 build variants
After: 77 tasks across 7 build variants
=> PYTHON-4886 Use shrub.py for PyOpenSSL tests

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Before: 20 tasks across 4 build variants
After: 24 tasks across 4 build variants
Passing [build](https://spruce.mongodb.com/version/67129edccfe943000796dac7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> PYTHON-4888 Use shrub.py for versioned api tests

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Patch [build](https://spruce.mongodb.com/version/6716488718b00200071a4f7f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> PYTHON-4890 Use shrub.py for storage engine tests

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Also covers Atlas Data Lake tests.
Before: 139 tasks across 9 build variants
Before: All server versions and topologies across all CPython versions
After: 49 tasks across 9 build variants
=> PYTHON-4891 Use shrub.py for c extension tests

test/pytest_conf.py
Verified with `pytest  --collect-only -q | grep test_auth`.
=> PYTHON-4894 Fix handling of auth test marker

.evergreen/config.yml, .evergreen/scripts/generate_config.py
We'll be able to reduce the number of variants again once we start automating tasks, which will allow us to put auth and ssl in the task definitions.
=> PYTHON-4898 Ensure consistent versions of tests across hosts

.evergreen/config.yml, .evergreen/scripts/generate_config.py
Before: 49 tasks across 7 build variants
Covered all cpython versions across the three hosts.
After: 42 tasks across 6 build variants, min and max cpython versions.
Patch [build](https://spruce.mongodb.com/version/6716a697ddc5920007831646/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
=> PYTHON-4893 Use shrub.py for aws auth tests

bson/binary.py, test/test_bson.py
Backward-compatible change of `Binary.from_vector` to take the BinaryVector dataclass as an alternative to separate list, dtype, and padding.
=> PYTHON-2926 Updated signature of Binary.from_vector to take a BinaryVector

.evergreen/config.yml, .evergreen/scripts/generate_config.py
[Patch build](https://spruce.mongodb.com/version/6716ed02a963a10007ba85e3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> PYTHON-4896 Use shrub.py for other hosts tests

.evergreen/config.yml, .evergreen/scripts/generate_config.py
=> PYTHON-4900 Convert remaining matrix definitions to use shrub.py

.evergreen/config.yml, .evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
[Patch build](https://spruce.mongodb.com/version/671aecf52732920007436fe9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> PYTHON-4905 Use shrub.py to generate load balancer tasks

bson/json_util.py, doc/changelog.rst, test/test_json_util.py
PYTHON-4885 Fix legacy extended JSON encoding of DatetimeMS
Note I opted _not_ to introduce logic to parse previously encoded invalid "$date" data for a few reasons:
1. It's not clear if that behavior would be useful. No one has reported this as an issue.
1. We can always introduce it later if we get new info that it's required.
1. Adding it is problematic since it's invalid. We don't know if the data is genuinly invalid or a result of the encoding bug. For example, does the user intend this `'{"dt": { "$date" : "1970"}}'` to be the year 1970 or is it 1970 milliseconds after the epoch?   
Old behavior:
```python
>>> dumps({'d': DatetimeMS(1)}, json_options=LEGACY_JSON_OPTIONS)
'{"d": {"$date": "1"}}'
```
New behavior:
```python
>>> dumps({'d': DatetimeMS(1)}, …
```
=> PYTHON-4885 Fix legacy extended JSON encoding of DatetimeMS

.github/workflows/create-release-branch.yml, test/auth_oidc/test_auth_oidc.py
Tested with [blink1073/winkerberos/actions/runs/11235828228/job/31299944398](https://github.com/blink1073/winkerberos/actions/runs/11235828228/job/31299944398)
=> PYTHON-4906 Add branch creation workflow to Python Driver

.evergreen/config.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Updated variant list:
```
* Test RHEL8 py3.10
* Test RHEL8 py3.11
* Test RHEL8 py3.12
* Test RHEL8 py3.13 cov
* Test RHEL8 py3.9 cov
* Test RHEL8 pypy3.10 cov
* Test RHEL8 pypy3.9
* Test Win32 py3.13
* Test Win32 py3.9
* Test Win64 py3.13
* Test Win64 py3.9
* Test macOS Arm64 py3.13
* Test macOS Arm64 py3.9
* Test macOS py3.13
* Test macOS py3.9
Atlas Data Lake Ubuntu-22 py3.13 Auth
Atlas Data Lake Ubuntu-22 py3.13 Auth No C
Atlas Data Lake Ubuntu-22 py3.9 Auth
Atlas Data Lake Ubuntu-22 py3.9 Auth No C
Atlas connect RHEL8 py3.13
Atlas connect RHEL8 py3.9
Auth AWS Ubuntu-20 py3.13
Auth AWS Ubuntu-20 py3.9
Auth AWS Win64 py3.13
Auth AWS Win64 py3.9
Auth AWS macOS py3.13
Auth AWS macOS py3.9
Auth Enterprise RHEL8 py3.10 Auth
Auth Enterprise RHEL8 py3.11 Auth
Auth Enterprise RHEL8 py3.12 Auth …
```
=> PYTHON-4943 Clean up EVG Variant Display Names

bson/binary.py, test/test_bson.py
Follows suggestion from @ShaneHarvey that adding typing oveloading would make clear that dtype  is a required argument when the first argument, vector, is a list, not at BinaryVector instance.
=> PYTHON-4903 Adds typing overloading to bson.binary.Binary.from_vector

.evergreen/generated_configs/variants.yml, .evergreen/scripts/configure-env.sh, .evergreen/scripts/generate_config.py
- Rename py3.x ->  Python3.x
- Centralize SKIP_CSOT_TEST usage
- Refactor handling of Host in generator and prep for moving the parts of the generator to drivers-evergreen-tools.
=> PYTHON-4956 Generated config cleanup

pymongo/asynchronous/mongo_client.py, pymongo/synchronous/mongo_client.py
PYTHON-4907 Avoid noisy TypeError at interpreter exit
=> PYTHON-4907 Avoid noisy TypeError at interpreter exit

test/asynchronous/test_retryable_writes.py, test/retryable_writes/unified/aggregate-out-merge.json, test/retryable_writes/unified/bulkWrite.json, test/retryable_writes/unified/client-bulkWrite-serverErrors.json, test/retryable_writes/unified/deleteMany.json, test/retryable_writes/unified/deleteOne.json, test/retryable_writes/unified/findOneAndDelete.json, test/retryable_writes/unified/findOneAndReplace.json, test/retryable_writes/unified/findOneAndUpdate.json, test/retryable_writes/unified/insertMany.json, test/retryable_writes/unified/insertOne.json, test/retryable_writes/unified/replaceOne.json, test/retryable_writes/unified/unacknowledged-write-concern.json, test/retryable_writes/unified/updateOne.json, test/test_retryable_writes.py
PYTHON-4919 Resync tests for retryable writes
=> PYTHON-4919 Resync tests for retryable writes

test/asynchronous/unified_format.py, test/unified_format.py
PYTHON-4356 Unskip spec tests for agg $out
The spec tests themselves were already updated in PYTHON-4576.
=> PYTHON-4356 Unskip spec tests for agg $out

pymongo/asynchronous/pool.py, pymongo/synchronous/pool.py, test/test_connection_monitoring.py
PYTHON-4414 interruptInUseConnections should cancel pending connections too
Judging from the test logs, this appears to be a minor bug in the implementation of interruptInUseConnections added in PYTHON-3175. If the pool is cleared simultaneously while a thread is creating a connection, the pending connection is not cancelled or closed. Instead the connection is created normally and added to the pool as shown in the log of the failed test:
```
Events:
[2024/04/29 03:44:47.090] PoolCreatedEvent(('localhost', 27017), {})
[2024/04/29 03:44:47.090] PoolReadyEvent(('localhost', 27017))
[2024/04/29 03:44:47.090] ConnectionCheckOutStartedEvent(('localhost', 27017))
[2024/04/29 03:44:47.090] ConnectionCreatedEvent(('localhost', 27017), 1)
[2024/04/29 03:44:47.090] PoolClearedEvent(('localhost', …
```
=> PYTHON-4414 interruptInUseConnections should cancel pending connections too

test/asynchronous/test_retryable_reads.py, test/test_retryable_reads.py
PYTHON-4982 Remove redundant configureFailPoint
This shouldn't resolve all the issues but it's worth removing the redundant code.
=> PYTHON-4982 Remove redundant configureFailPoint

pymongo/network_layer.py
PYTHON-4292 Improve TLS read performance
Use a socket timeout based approach for cancelling pending operations. This results in >=2x better throughput when reading large TLS responses from multiple threads.
Before:
```
time python bench-100-threads-find-large.py
Python: 3.13.0, PyMongo: 4.11.0.dev0, MongoDB: 8.0.1, auth: True, tls: True
python bench-100-threads-find-large.py  15.05s user 53.82s system 256% cpu 26.805 total
```
After:
```
time python bench-100-threads-find-large.py
Python: 3.13.0, PyMongo: 4.11.0.dev0, MongoDB: 8.0.1, auth: True, tls: True
python bench-100-threads-find-large.py  9.31s user 23.28s system 244% cpu 13.327 total
```
=> PYTHON-4292 Improve TLS read performance

.evergreen/run-import-time-test.sh
Allow the stash to be optional.
=> PYTHON-5001 Fix import time check

.pre-commit-config.yaml, CONTRIBUTING.md, pymongo/synchronous/mongo_client.py, tools/synchro.py, tools/synchro.sh
Example output:
```
synchro..................................................................Failed
- hook id: synchro
- exit code: 1
Refusing to overwrite ./pymongo/synchronous/mongo_client.py
File "/Users/steve.silvester/workspace/mongo-python-driver/./tools/synchro.py", line 380, in <module>
main()
File "/Users/steve.silvester/workspace/mongo-python-driver/./tools/synchro.py", line 371, in main
raise ValueError("Aborting synchro due to errors")
ValueError: Aborting synchro due to errors
```
=> PYTHON-5002 Add guard to synchro hook to accidental overwrite

test/asynchronous/test_encryption.py, test/test_encryption.py
Passing build: https://spruce.mongodb.com/version/675076633360e3000745b3c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5006 Skip test_kms_retry when using PyOpenSSL

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Passing build: https://spruce.mongodb.com/version/6752f53be58c550007b9846b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5008 Do not build c extensions on other hosts

.evergreen/install-dependencies.sh, .evergreen/scripts/configure-env.sh, .evergreen/scripts/prepare-resources.sh, .evergreen/scripts/setup-system.sh, .evergreen/setup-spawn-host.sh, .evergreen/sync-spawn-host.sh
Once this is merged I can update the team wiki with suggested usage:
- Ensure `fswatch` is installed using `brew`
- Create a spawn host
- Run `bash .evergreen/setup-spawn-host.sh <url>`
- Run `bash .evergreen/sync-spawn-host.sh <url>`
- Start server on the spawn host - drivers tools is in `~/drivers-tools`
- Develop locally and watch as changes sync.
- Run tests on remote machine.  Env variables can be sourced using `source ~/mongo-python-driver/.evergreen/scripts/env.sh`
=> PYTHON-5016 Create spawn host helper scripts

.evergreen/config.yml
Passing build (except for a known failure with PyOpenSSL): https://spruce.mongodb.com/version/6775abaea10eb50007d8f5e7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5018 Use a single script for system setup

.evergreen/install-dependencies.sh, .evergreen/scripts/ensure-hatch.sh, .evergreen/scripts/run-mod-wsgi-tests.sh, .evergreen/setup-spawn-host.sh
We can't ensure hatch during system setup because often PYTHON_BINARY is set at the task level.
=> PYTHON-5019 Fix mod_wsgi tests

.evergreen/config.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, .evergreen/scripts/run-direct-tests.sh, .evergreen/setup-spawn-host.sh, doc/changelog.rst
Patch build: https://spruce.mongodb.com/version/677bd859afd77c0007862ebc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-4840 Add evergreen tests for free-threaded Python 3.13t

doc/changelog.rst
I copied the C driver [notice](https://github.com/mongodb/mongo-c-driver/releases/tag/1.29.0).  Since we don't know for sure the timing of our upcoming minor releases, I kept the notice generic.
=> PYTHON-4949 Communicate future minWireVersion bump / 4.0 EoL

pymongo/network_layer.py
PYTHON-5011 Fix behavior of TLS connection errors on PyPy
This change reverts the wait_for_read change in PYTHON-4292 but only for PyPy to deal with the issues described in that ticket.
=> PYTHON-5011 Fix behavior of TLS connection errors on PyPy

test/asynchronous/test_encryption.py, test/test_encryption.py
PYTHON-5014 Tests that use HTTPSConnection should only use stdlib ssl
Attempting to fix this test failure on pyopenssl+encryption:
```
[2024/12/09 09:18:59.661] FAILURE: NotImplementedError: Cannot make file object of OpenSSL.SSL.Connection ()
[2024/12/09 09:18:59.661] self = <test.asynchronous.test_encryption.TestKmsRetryProse testMethod=test_kms_retry>
[2024/12/09 09:18:59.661]     async def test_kms_retry(self):
[2024/12/09 09:18:59.661] >       await self._test("aws", {"region": "foo", "key": "bar", "endpoint": "127.0.0.1:9003"})
[2024/12/09 09:18:59.661] test/asynchronous/test_encryption.py:2924: 
[2024/12/09 09:18:59.661] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2024/12/09 09:18:59.661] test/asynchronous/test_encryption.py:2901: in _test …
```
=> PYTHON-5014 Tests that use HTTPSConnection should only use stdlib ssl

test/asynchronous/test_encryption.py, test/test_encryption.py
PYTHON-5038 Resolve "certificate verify failed: Missing Authority Key Identifier" errors.
=> PYTHON-5038 Resolve certificate verify failed: Missing Authority Key Identifier

test/retryable_writes/unified/aggregate-out-merge.json
PYTHON-4999 Resync retryable writes tests
Fixes one test failure on serverless.
=> PYTHON-4999 Resync retryable writes tests

pymongo/common.py, pymongo/hello.py, test/test_server_description.py
PYTHON-5059 Update default maxMessageSizeBytes and maxWriteBatchSize
Now that we only support MongoDB 4.0+, we know the server's 
maxMessageSizeBytes is always 48MB and maxWriteBatchSize is always 100,000.
=> PYTHON-5059 Update default maxMessageSizeBytes and maxWriteBatchSize

.github/workflows/release-python.yml
Tested on my fork to confirm the behavior: https://github.com/blink1073/mongo-python-driver/actions/runs/9552412608
=> PYTHON-5047 Fix dry run logic in releases again

.github/workflows/dist.yml, doc/changelog.rst
Uses approach from https://github.com/PennyLaneAI/pennylane-lightning/pull/1056/files to select a newer version of the binfmt image.
Stop using the aarch64 runners as well because they are randomly crashing during the checkout phase, when it tries to remove credentials.
=> PYTHON-5058 Restore alternate architecture builds

CONTRIBUTING.md, pymongo/asynchronous/mongo_client.py, pymongo/synchronous/mongo_client.py
Reflects the fact that it is now in kwargs.
=> PYTHON-5111 Update datetime_conversion in docstrings of MongoClients

pymongo/asynchronous/change_stream.py, pymongo/asynchronous/client_session.py, pymongo/asynchronous/cursor.py, pymongo/asynchronous/pool.py, pymongo/periodic_executor.py, pymongo/synchronous/change_stream.py, pymongo/synchronous/client_session.py, pymongo/synchronous/cursor.py, pymongo/synchronous/pool.py, test/asynchronous/test_async_cancellation.py, tools/synchro.py
=> PYTHON-4745 - Test behavior of async task cancellation

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Patch build with coverage report: https://spruce.mongodb.com/version/67ab6f0adec6760007b1e6f8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Report:
=> PYTHON-4983 - Restore no C extension coverage variants

test/asynchronous/test_bulk.py, test/test_bulk.py
I'm unable to reproduce the failure, re-enabling to monitor longer-term.
Four consecutive passing runs: https://spruce.mongodb.com/version/67ab92982d7b8f00077af4aa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.
=> PYTHON-4865 - Re-enable TestBulkWriteConcern tests

test/load_balancer/non-lb-connection-establishment.json
Sync `non-lb-connection-establishment` test to https://github.com/mongodb/specifications/commit/d05c33e0a6124ee7d1a9de665084d540b2ff06c5
This is intended to proactively avoid tests failure once drivers start testing 8.1 builds. See DRIVERS-3108. Drivers are not-yet testing 8.1 (see [slack](https://mongodb.slack.com/archives/C72LB5RPV/p1739884710850709)).
Verified with this patch build: https://spruce.mongodb.com/version/67b4d8cb3b14bd0007c52456/
=> PYTHON-5142 Sync `non-lb-connection-establishment` test

doc/changelog.rst, pymongo/message.py, test/asynchronous/test_database.py, test/test_database.py
PYTHON-5166 Fix db.command bulkWrite bug
=> PYTHON-5166 Allow Database.command to run bulkWrite commands

test/mockupdb/test_cluster_time.py
PYTHON-5164 Fix mockupdb TestClusterTime
=> PYTHON-5164 Fix mockupdb TestClusterTime

bson/binary.py, test/bson_binary_vector/float32.json, test/bson_binary_vector/int8.json, test/bson_binary_vector/packed_bit.json, test/test_bson_binary_vector.py
Qingyang added more tests of invalidity. In particular, malformed BSON that won't decode.
https://github.com/mongodb/specifications/pull/1750
=> PYTHON-5126 Resync bson vector spec tests following additions

doc/changelog.rst, pymongo/message.py, test/asynchronous/test_database.py, test/test_database.py
PYTHON-5166 Allow Database.command to run bulkWrite commands (https://github.com/mongodb/mongo-python-driver/pull/2164) [v4.11]
=> PYTHON-5166 Allow Database.command to run bulkWrite commands (#2164) [v4.11]

doc/changelog.rst, pymongo/asynchronous/topology.py, pymongo/synchronous/topology.py
PYTHON-5155 Use dochub link for fork warning
=> PYTHON-5155 Use dochub link for fork warning

doc/changelog.rst, pymongo/asynchronous/topology.py, pymongo/synchronous/topology.py
PYTHON-5155 Use dochub link for fork warning (#2173) [v4.11]
=> PYTHON-5155 Use dochub link for fork warning (#2173) [v4.11]

test/asynchronous/test_async_cancellation.py
Patch build: https://spruce.mongodb.com/version/67c60f7ab322260007412a36/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5178 Make test_async_cancellation_closes_change_stream more robust

.evergreen/config.yml, .evergreen/run-tests.sh, .evergreen/scripts/run_tests.py, .evergreen/scripts/setup_tests.py, CONTRIBUTING.md
Build with logs: https://spruce.mongodb.com/task/mongo_python_driver_test_rhel8_python3.10_test_4.0_standalone_noauth_nossl_sync_async_patch_f1fe49784b5ec7364b009fe64ab17ff7f86e7111_67c6f0a1c9786e00074cd25e_25_03_04_12_23_03/logs?execution=0&sortBy=STATUS&sortDir=ASC
=> PYTHON-5181 Make it easier to set debugging logging in an Evergreen patch

.evergreen/scripts/setup-dev-env.sh
Passing build: https://spruce.mongodb.com/version/67c705106ab08300078cb3c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
```bash
Administrator@EC2AMAZ-UCP10AK ~/mongo-python-driver
$  ls pymongo | grep pyd
_cmessage.cp39-win_amd64.pyd
```
=> PYTHON-5183 Fix C Extension building for Windows spawn hosts

test/asynchronous/test_pooling.py, test/test_pooling.py
PYTHON-5167 Properly cleanup test SocketGetter tasks
Should resolve one of the errors seen in SocketGetter.run_mongo_thread:
```
FAILED test/asynchronous/test_session.py::TestSession::test_end_sessions - pytest.PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object SocketGetter.run_mongo_thread at 0x4dc35c00a00>
File "/home/runner/work/mongo-python-driver/mongo-python-driver/pymongo/asynchronous/pool.py", line 1474, in _get_conn
if not await _async_cond_wait(self.size_cond, timeout):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GeneratorExit
During handling of the above exception, another exception occurred:
File "/home/runner/work/mongo-python-driver/mongo-python-driver/test/asynchronous/test_pooli …
```
=> PYTHON-5167 Properly cleanup test SocketGetter tasks

test/asynchronous/test_client.py, test/test_client.py
PYTHON-5173 Adjust test_continuous_network_errors to be less flaky
Split from https://github.com/mongodb/mongo-python-driver/pull/2166
=> PYTHON-5173 Adjust test_continuous_network_errors to be less flaky

test/load_balancer/non-lb-connection-establishment.json
This reverts commit 5456f1ec045beaeee3a9b008b9522266fc9f43c1.
=> PYTHON-5184 Revert skip to non-lb-connection-establishment

.evergreen/config.yml, .evergreen/scripts/run-mod-wsgi-tests.sh
`run-server` does not take a sub test name, and needs `PYTHON_BINARY` because it is using `uv`.
Passing build for sub test name failures: https://spruce.mongodb.com/version/67ca55cc5be7690007c040b4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Passing build for mod_wsgi failure: https://spruce.mongodb.com/task/mongo_python_driver_mod_wsgi_ubuntu_22_python3.13_mod_wsgi_embedded_mode_replica_set_patch_f69e1f6f0485d0b6b99b5359c0291a562bfc0d7b_67ca5eba98f41500071a8983_25_03_07_02_49_38/logs?execution=0
=> PYTHON-5193 & PYTHON-5192 Fix run-server usage

test/discovery_and_monitoring/rs/secondary_ipv6_literal.json
PYTHON-5194 Test secondary with IPv6 literal in SDAM
=> PYTHON-5194 Test secondary with IPv6 literal in SDAM

doc/changelog.rst, pymongo/asynchronous/encryption.py, pymongo/encryption_options.py, pymongo/synchronous/encryption.py, pyproject.toml, test/asynchronous/unified_format.py, test/asynchronous/utils_spec_runner.py, test/client-side-encryption/spec/legacy/fle2v2-Rangev2-Compact.json, test/client-side-encryption/spec/legacy/keyCache.json, test/client-side-encryption/spec/legacy/timeoutMS.json, test/client-side-encryption/spec/unified/keyCache.json, test/unified_format.py, test/utils_spec_runner.py, uv.lock
PYTHON-4580 Add key_expiration_ms option for DEK cache lifetime
Depends on https://github.com/mongodb/libmongocrypt/pull/984
=> PYTHON-4580 Add key_expiration_ms option for DEK cache lifetime

.evergreen/scripts/run_server.py
```bash
VERSION=8.0 just run-server
bash .evergreen/scripts/run-server.sh
Sourcing env file
INFO     Running command 'bash /Users/steve.silvester/workspace/drivers-evergreen-tools/.evergreen/run-orchestration.sh'...
Ensuring python binary...
Ensuring python binary... done.
Creating virtual environment 'venv'...
Creating virtual environment 'venv'... done.
uv is /opt/homebrew/bin/uv
INFO     Running orchestration...
INFO     Downloading mongodb 8.0...
```
=> PYTHON-5199 Fix handling of MongoDB version in run-server

.evergreen/scripts/utils.py
Passing build: https://spruce.mongodb.com/version/67d3563dd1a32f0007d196a4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5210 Prevent overriding the python used by other tools

.evergreen/config.yml, .evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/configure-env.sh, .evergreen/scripts/generate_config.py, .evergreen/scripts/setup_tests.py, .evergreen/scripts/teardown_tests.py, CONTRIBUTING.md
Depends on https://github.com/mongodb-labs/drivers-evergreen-tools/pull/636
Passing build: https://spruce.mongodb.com/version/67d9a1b396d188000737f190/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5217 Update Atlas Data Lake tests

pymongo/asynchronous/client_session.py, pymongo/synchronous/client_session.py, test/retryable_writes/unified/insertOne-serverErrors.json, test/transactions-convenient-api/unified/commit-writeconcernerror.json, test/transactions/unified/error-labels.json
We already did a chunk of this work in February, but the spec tests hadn't been fully updated yet.
=> PYTHON-5135 - Rename WriteConcernFailed code name to WriteConcernTimeout

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Passing build: https://spruce.mongodb.com/version/67e30c037f515f00072551e0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5236 Test sharded clusters with requireApiVersion=1

pymongo/asynchronous/mongo_client.py, pymongo/synchronous/mongo_client.py
Passing build: https://spruce.mongodb.com/version/67e55635d7694b0007baa01c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5421 Fix handling of client timeout property

test/retryable_reads/unified/estimatedDocumentCount.json, test/unified-test-format/valid-pass/expectedError-isClientError.json, test/unified-test-format/valid-pass/operation-empty_array.json
These two had overlapping changed files.
=> PYTHON-4942 & PYTHON-4936 Test that isClientError considers network errors and operations may be an empty array

test/performance/async_perf_test.py, test/performance/perf_test.py
Shruti had already written the client bulk_write benchmarks, so only the non-mixed collection ones needed to be added.
=> PYTHON-4833 - Add Collection bulk_write benchmarks

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, doc/changelog.rst, pymongo/pool_shared.py, pymongo/pyopenssl_context.py
Passing build, failures are unrelated: https://spruce.mongodb.com/version/67eab281bedd750007ac719e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.
=> PYTHON-5154 - Remove PyOpenSSL support from Async PyMongo

test/asynchronous/test_examples.py, test/test_examples.py
From the ticket: "The [Convenient API for Transactions](https://github.com/mongodb/specifications/blob/master/source/transactions-convenient-api/transactions-convenient-api.rst) [examples in the MongoDB manual](https://www.mongodb.com/docs/manual/core/transactions/) use the following options:
"local" read concern
"primary" read preference
"majority" write concern with wTimeoutMS=1000
These no longer seem relevant and I propose removing them."
=> PYTHON-3674 Simplify transaction options in convenient API doc example code

.evergreen/scripts/install-dependencies.sh, .evergreen/scripts/setup-dev-env.sh, .evergreen/scripts/setup_tests.py
I verified that the correct Python version is used for setup, test, and teardown in https://spruce.mongodb.com/task/mongo_python_driver_test_rhel8_python3.10_test_4.0_standalone_noauth_nossl_sync_async_patch_bf0aa56fbbfa33c3bfbdf3c03a4ab55aceb0cda4_67f0881dcc09ba0007a35717_25_04_05_01_32_20/logs?execution=0 (Python 3.10).
=> PYTHON-5268 Fix handling of PYTHON_BINARY

pymongo/asynchronous/topology.py, pymongo/synchronous/topology.py
PYTHON-5270 Server selection should log remainingTimeMS as milliseconds
=> PYTHON-5270 Server selection should log remainingTimeMS as milliseconds

bson/binary.py, test/bson_binary_vector/packed_bit.json, test/test_bson.py, test/test_bson_binary_vector.py
- See PYTHON-5126 and DRIVERS-3123 for details.
=> PYTHON-5126 & PYTHON-5280 Addresses issues raised in DRIVERS-3097 and DRIVERS-3123 

uv.lock
Patch build: https://spruce.mongodb.com/task/mongo_python_driver_test_macos_arm64_python3.13_test_6.0_replica_set_noauth_ssl_async_patch_fafa00e9e3448cf44f1504c907e6400b24612cb8_67f697241800d5000758bf5b_25_04_09_15_50_25/logs?execution=0
=> PYTHON-5295 Update lockfile for compat with older versions of uv

doc/changelog.rst, pymongo/pool_shared.py
(cherry picked from commit 5b0862e)
=> PYTHON-5297 [v4.12] AsyncMongoClient connection error causes UnboundLocalError

test/asynchronous/test_examples.py, test/test_examples.py
PYTHON-5308 Remove SON from doc examples
=> PYTHON-5308 Remove SON from doc examples

.evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Patch build: https://spruce.mongodb.com/version/67fd13625ee31c0007ce6dec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Before: 35 tasks across 3 build variants
After: 78 tasks across 3 build variants
=> PYTHON-5311 Create standard linux evergreen tasks

.evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, .evergreen/scripts/generate_config_utils.py
Patch build: https://spruce.mongodb.com/version/67fef976f1e04f0007ed9f86/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
z-series failures are unrelated.
=> PYTHON-5316 Update tests for other hosts

test/asynchronous/unified_format.py, test/unified_format.py
Passing build: https://spruce.mongodb.com/version/67ffef75cb71cc0007dc3e03/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5326 - Skip serverless tests with known issue

.evergreen/generated_configs/functions.yml, .evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, .evergreen/scripts/run_tests.py, .evergreen/scripts/setup_tests.py, .evergreen/scripts/utils.py, .github/workflows/test-python.yml, CONTRIBUTING.md, doc/conf.py, doc/examples/client_bulk.rst, justfile
Patch build: https://spruce.mongodb.com/version/680060dc0eaa6e0007ed200e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5330 Convert no c extensions and doctests to use the standard test pattern

pymongo/__init__.py, test/test_default_exports.py
PYTHON-5314 Fix default imports
Oddly, ruff complained about the existing code 
```
import pymongo.uri_parser  # noqa: F401 # isort: skip
import pymongo.change_stream  # noqa: F401 # isort: skip
...
```
precommit fails:
```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1
pymongo/__init__.py:110:28: RUF100 Unused `noqa` directive (unused: `F401`)
...
pymongo/__init__.py:116:26: RUF100 Unused `noqa` directive (unused: `F401`)
(edited)
4 replies
```
But if I remove the noqa comment, ruff will delete the imports because it thinks they're unused...
The only way I found to avoid this was to change the imports to `from pymongo import uri_parser`.
=> PYTHON-5314 Fix default imports

doc/changelog.rst, pymongo/asynchronous/pool.py, pymongo/asynchronous/topology.py, pymongo/synchronous/pool.py, pymongo/synchronous/topology.py, test/__init__.py, test/asynchronous/__init__.py, test/asynchronous/test_discovery_and_monitoring.py, test/test_discovery_and_monitoring.py, tools/synchro.py
(cherry picked from commit 09897b6)
=> PYTHON-5212 [v4.12] Do not hold Topology lock while resetting pool

test/asynchronous/test_client.py, test/test_client.py
(cherry picked from commit https://github.com/mongodb/mongo-python-driver/commit/34f7d7ee4c2cbe8ba23c91a489a938af2cb46386)
=> PYTHON-5346: [v4.12] test_init_disconnected_with_srv cannot run against sharded Topologies (#2304)

.evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
See the [ticket](https://jira.mongodb.org/browse/PYTHON-5345) for more background on the reasoning.
Patch build: https://spruce.mongodb.com/version/680b9b831d659e0007140dda/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Doctests:
Load Balancer:
No C Ext (partial list shown):
MongoDB 4.4:
=> PYTHON-5345 Streamline the standard tasks

.evergreen/scripts/install-dependencies.sh, .evergreen/scripts/utils.py, CONTRIBUTING.md
Passing build: https://spruce.mongodb.com/version/68142207555ad30007753352/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5365 Fix handing of remote tests

.evergreen/generated_configs/functions.yml, .evergreen/scripts/generate_config.py, .evergreen/scripts/perf-submission-setup.sh, .evergreen/scripts/perf-submission.sh, test/performance/async_perf_test.py, test/performance/perf_test.py
Passing perf build: https://spruce.mongodb.com/version/681915dc655db20007eda240/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5358 - Switch to supported Perf usage in EVG

test/asynchronous/unified_format.py, test/unified_format.py
Explicitly connect clients for unified CSOT tests before the test begins to minimize flakiness caused by SDAM creation and startup.
Patch build with everything run: https://spruce.mongodb.com/version/6812632b5456710007edc380/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5356 - Init unified test client SDAM for all unified tests

bson/_cbsonmodule.c
=> PYTHON-5033 Use PyModule_Add on >= 3.13

bson/binary.py, test/bson_binary_vector/packed_bit.json, test/test_bson.py, test/test_bson_binary_vector.py
Reverts mongodb/mongo-python-driver#2261
=> Revert "PYTHON-5126 & PYTHON-5280 Addresses issues raised in DRIVERS-3097 and DRIVERS-3123 "

.evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Before: 128 tasks
After: 151 tasks
=> PYTHON-5379 Run more variants on pull requests

doc/changelog.rst, pymongo/write_concern.py, test/test_write_concern.py
https://jira.mongodb.org/browse/PYTHON-5362
=> PYTHON-5362 WriteConcern repr should be eval-able

test/asynchronous/test_session.py, test/test_session.py
PYTHON-5409 Make test_implicit_sessions_checkout less flaky
=> PYTHON-5409 Make test_implicit_sessions_checkout less flaky

pymongo/_csot.py, pymongo/periodic_executor.py, test/asynchronous/test_async_contextvars_reset.py, tools/synchro.py
(cherry picked from commit 536b1cb8ab410e9f190707629ff0107ee86feee5)
=> [v4.13] PYTHON-5406 - AsyncPeriodicExecutor must reset CSOT contextvars before executing

pymongo/pyopenssl_context.py
When there is a mistake in the certificates configuration, PyMongo would give the following error:
```
pymongo.errors.ServerSelectionTimeoutError: module service_identity has no attribute SICertificateError, Timeout: 30s, Topology Description: <…>
```
Because the `except` block expected non-existing errors, the error gets transformed to "module … has no attribute …". The errors in the `service_identity` have never had the `SI` prefix:
https://github.com/pyca/service-identity/blob/18.1.0/src/service_identity/exceptions.py
It looks like the errors were imported with an alias before, but this aliasing was (only partially) removed when rewriting to lazy imports in this commit:
https://github.com/mongodb/mongo-python-driver/commit/42a08c4a34c1bd58296de1ffa2368396fdb12f8f#diff-b277a2f4cfbb5decab …
=> PYTHON-5414 Fix "module service_identity has no attribute SICertificateError" when using pyopenssl

test/asynchronous/test_session.py, test/test_session.py
Fixes the failure seen here: https://github.com/mongodb/mongo-python-driver/actions/runs/15606502724/job/43991538564?pr=2382
```
FAILED test/test_session.py::TestSession::test_implicit_sessions_checkout - AssertionError: InvalidOperation('Cannot use MongoClient after close') is not None
```
=> PYTHON-5409 Fix test_implicit_sessions_checkout again

test/asynchronous/test_ssl.py, test/test_ssl.py
PYTHON-5414 Add test for hostname verification error message regression
Note that this test won't run in CI for now due to https://jira.mongodb.org/browse/PYTHON-5415 but I tested it locally and the assertion passed.
=> PYTHON-5414 Add test for hostname verification error message regression

doc/changelog.rst, pymongo/pyopenssl_context.py, test/asynchronous/test_ssl.py, test/test_ssl.py
Backports:  https://github.com/mongodb/mongo-python-driver/commit/c2aefc2edab2c34d10e34d69793431b0d6800d24 and https://github.com/mongodb/mongo-python-driver/commit/c16ef0a13e97dd04d1f4234f21ecda0627aaee8c for PYTHON-5414.
=> [v4.13] PYTHON-5414 Fix "module service_identity has no attribute SICertificateError" when using pyopenssl

hatch_build.py, test/__init__.py, test/asynchronous/__init__.py
Didn't find any instances of `subprocess.call` and all (three) instances of `subprocess.check_call(...)` are now `subprocess.run(..., check=True)`
=> PYTHON-5423 Always use subprocess.run instead of subprocess.check_call or subprocess.call

doc/changelog.rst, pymongo/asynchronous/uri_parser.py, pymongo/synchronous/uri_parser.py, test/test_uri_parser.py
follow up PR to https://github.com/mongodb/mongo-python-driver/pull/2413
=> PYTHON-5421 continued - update changelog, update docstring, and add testing

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, .evergreen/scripts/setup_tests.py, .gitignore, test/atlas/test_connection.py
Resolves PYTHON-5373. Test MONGODB-X509 auth with Atlas on cloud-dev.
Includes a follow-up to https://github.com/mongodb/mongo-python-driver/pull/2284 to add the expansion `TEST_NAME: atlas_connect` on the `Atlas connect RHEL8` variant to restore running the `TestAtlasConnect` tests. Tests were run in this [patch build](https://spruce.mongodb.com/version/686c2e96c75aca0007cc5ef3) (logs now show `TestAtlasConnect`).
Tests store the client certificate to the path: `.evergreen/atlas_x509_dev_client_certificate.pem`. This is similarly done for the [keytab file](https://github.com/mongodb/mongo-python-driver/blob/c77c15e369ddb9d9c63abb0adb9ac7d3f8ab11ef/.evergreen/scripts/setup_tests.py#L262). A [code scan alert](https://github.com/mongodb/mongo-python-driver/security/code-scanning/214) was …
=> PYTHON-5373 test client auth on cloud-dev

bson/binary.py
`just docs` was failing and wasn't picked up during code review.
=> PYTHON-5289 Fixes indentation in docstring of Binary.from_vector

test/asynchronous/test_auth_oidc.py, test/test_auth_oidc.py
Passing build: https://spruce.mongodb.com/version/6877c6284320e70007aa831f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5444 Update OIDC tests use camelCase options

doc/conf.py, pymongo/asynchronous/client_session.py, pymongo/synchronous/client_session.py
Copies the recommended warning from the [spec change](https://github.com/mongodb/specifications/commit/13117d601fb6ea177e485880175b5be1651a7e46).
=> PYTHON-4019 Infinite loop in generic transactional provider due to dup keys

.evergreen/scripts/resync-all-specs.sh
Accidentally left out the name of the flag when calling one of the scripts! 
But now it definitely works -- ran a patch build to confirm and it generated: https://github.com/mongodb/mongo-python-driver/pull/2442
Let that be the spec resync pr that should've ran this morning :)
=> PYTHON-5253 Automated Spec Resync Quick Followup/Fix

.github/workflows/zizmor.yml, README.md, doc/changelog.rst, pymongo/topology_description.py, test/asynchronous/test_server_selection.py, test/test_server_selection.py, test/test_topology.py
Tested with the following script:
```python
from pymongo import MongoClient
from pymongo.read_preferences import ReadPreference
from concurrent.futures import ThreadPoolExecutor, wait
client = MongoClient()
session = client.start_session()
read_preference = ReadPreference.PRIMARY
def test():
for i in range(100):
client._select_server(read_preference, session, "testOperation")
def test2_target():
client._select_server(read_preference, session, "testOperation")
def test2():
futures = []
with ThreadPoolExecutor(max_workers=100) as pool:
for i in range(100):
futures.append(pool.submit(test2_target))
wait(futures)
if __name__ == '__main__':
import timeit
print(timeit.timeit("test()", setup="from __main__ import test, client, read_preference, session", number=1000)) …
```
=> PYTHON-4780 Implement fast path for server selection with Primary

doc/examples/encryption.rst
This PR is intended to make small fixes and improvements to the [In-Use Encryption](https://pymongo.readthedocs.io/en/stable/examples/encryption.html) examples:
- Remove incorrect collection names in the [Automatic Queryable Encryption](https://pymongo.readthedocs.io/en/stable/examples/encryption.html#queryable-encryption):
```
pymongo.errors.EncryptionError: Encrypted State Collection name should follow enxcol_.<collection>.esc naming pattern
```
DRIVERS-2565 describes the server change that required the metadata collection names to fit this pattern. libmongocrypt [applies the collection names](https://github.com/mongodb/libmongocrypt/blob/b36115cacad817de9dda8cef3b07b4b35e4d01c6/src/mc-schema-broker.c#L647-L659), so it is not necessary to specify. This PR removes the names from the …
=> Fix In-Use Encryption examples

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, test/asynchronous/test_collection.py, test/asynchronous/unified_format.py, test/test_collection.py, test/unified_format.py
Also fixes the server version tests to actually use the server version.
=> PYTHON-5491 Skip non-idempotent dropIndex tests

.github/workflows/codeql.yml, .github/workflows/dist.yml, .github/workflows/release-python.yml, .github/workflows/test-python.yml, .github/workflows/zizmor.yml
Reverts mongodb/mongo-python-driver#2469
This is causing failures in the sdist check builds: https://github.com/mongodb/mongo-python-driver/pull/2461#pullrequestreview-3107110239
=> Revert "Bump the actions group with 3 updates"

.evergreen/scripts/install-dependencies.sh, pymongo/asynchronous/server.py, pymongo/synchronous/server.py, test/asynchronous/test_pooling.py, test/test_pooling.py
It turns out we did have a race condition as to whether we'd get a client side or server side timeout.  This ensures we get the same information either way.
Also fixes a sporadic bug when installing `just` by ensuring that the bin dir exists before attempting to install into it.
=> PYTHON-5492 Fix handling of MaxTimeMSExpired responses

.evergreen/run-mongodb-oidc-test.sh
Follow up to #2486 
Patch build: https://spruce.mongodb.com/version/68a48469a9db27000776e76c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5502 Fix c extensions on OIDC VMs

pymongo/asynchronous/client_session.py, pymongo/synchronous/client_session.py
PYTHON-5504 Prototype exponential backoff in with_transaction.
Using the repro scrip in jira which runs 200 concurrent transactions in 200 threads all updating the same document shows a significant reduction in wasted retry attempts and latency (from p50 to p100). Before this change:
```
$ python3.13t repro-with_transaction-write-conflict-storm.py
Completed 200 transactions in 200 threads in 4.8626720905303955 seconds
Total retry attempts: 8132
avg latency: 3.04s p50: 3.36s p90: 4.59s p99: 4.83s p100: 4.84s
```
After (with 50ms initial backoff, 1000ms max backoff, and full jitter, backoff starting on the _second_ retry attempt):
```
$ python3.13t repro-with_transaction-write-conflict-storm.py
Completed 200 transactions in 200 threads in 4.251200914382935 seconds
Total retry attempts: 1089 …
```
=> PYTHON-5504 Prototype exponential backoff in with_transaction

doc/changelog.rst
(cherry picked from commit 0d2a4b462eaa60d4dc152b37554006db06bf6b21)
=> Prep for 4.14.1 release (#2495) [master]

pymongo/asynchronous/collection.py, pymongo/asynchronous/database.py, pymongo/asynchronous/helpers.py, pymongo/asynchronous/mongo_client.py, pymongo/synchronous/collection.py, pymongo/synchronous/database.py, pymongo/synchronous/helpers.py, pymongo/synchronous/mongo_client.py, test/asynchronous/test_backpressure.py, test/test_backpressure.py
PYTHON-5506 Prototype adaptive token bucket retry
Description:
Add adaptive token bucket based retry policy.
Successfully completed commands deposit 0.1 token. 
Failed retry attempts consume 1 token. 
A retry is only permitted if there is an available token.
For simplicity, this POC adds a retry bucket per MongoClient. In the future we will consider adding a retry bucket per server.
Patch with perf benchmarks: https://spruce.mongodb.com/version/68a7b69b74baee000728de31/tasks
=> PYTHON-5506 Prototype adaptive token bucket retry

test/asynchronous/test_collection.py, test/asynchronous/test_session.py, test/test_collection.py, test/test_session.py
(grouped them together because there wasn't a lot of each, but i can seperate the two into two different PRs if that's preferred) 
`self.assertTrue(x is y)` -> `self.assertIs(x, y)`
`self.assertTrue(x is not None)` -> `self.assertIsNotNone(x)`
=> PYTHON-5514 Specific assertions for "is" and "is not None"

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py, test/asynchronous/test_monitor.py, test/test_monitor.py, uv.lock
Passing build: https://spruce.mongodb.com/version/68ac6743a1284b0007585444/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5486 Test Gevent with Auth and SSL

doc/changelog.rst, pymongo/asynchronous/encryption.py, pymongo/encryption_options.py, pymongo/synchronous/encryption.py, pyproject.toml, test/__init__.py, test/asynchronous/__init__.py, test/asynchronous/test_encryption.py, test/test_encryption.py, uv.lock
Depends on https://github.com/mongodb/libmongocrypt/pull/1065
=> PYTHON-5328 CRUD Support in Driver for Prefix/Suffix/Substring Indexes

bson/binary.py, bson/raw_bson.py, bson/son.py, bson/typings.py, pymongo/asynchronous/cursor.py, pymongo/asynchronous/encryption.py, pymongo/asynchronous/helpers.py, pymongo/compression_support.py, pymongo/message.py, pymongo/network_layer.py, pymongo/synchronous/cursor.py, pymongo/synchronous/encryption.py, pymongo/synchronous/helpers.py, test/test_typing.py, test/unified_format_shared.py, uv.lock
Account for the `--strict-bytes` parameter added in [mypy 1.15](https://mypy-lang.blogspot.com/2025/02/mypy-115-released.html), which is enabled by our use of `strict=true` without explicitly opting out of the behavior.
The only runtime behavior I made was having `PyMongoKMSProtocol.read()` return bytes, which simplified the code and matched the behavior of `PyMongoProtocol.read()`.
=> PYTHON-5537 Update typing dependencies

pymongo/asynchronous/srv_resolver.py, pymongo/synchronous/srv_resolver.py, test/lambda/build_internal.sh, test/lambda/template.yaml
Updated to use Python 3.10, which solved a dns resolve error on lambda.
I did not find the root cause, but since 3.9 is EOL next month I left it at this solution.
I also updated the errors raised by srv_resolver to include the original error, which was useful in debugging the problem.
Passing build: https://spruce.mongodb.com/task/mongo_python_driver_faas_lambda_test_aws_lambda_deployed_patch_eca38b730b8227c52cd5f0c655f617e969743ee1_68c9e481e31406000770e31e_25_09_16_22_28_25/logs?execution=0
=> PYTHON-5555 Fix AWS Lambda build

test/asynchronous/test_collection.py, test/test_collection.py
Accommodate the changes from https://jira.mongodb.org/browse/DRIVERS-3261.
=> PYTHON-5491 Update test for dropIndex behavior change

pymongo/asynchronous/encryption.py, pymongo/asynchronous/srv_resolver.py, pymongo/common.py, pymongo/encryption_options.py, pymongo/synchronous/encryption.py, pymongo/synchronous/srv_resolver.py, test/version.py
Example errors:
```python
>>> from pymongo.encryption_options import AutoEncryptionOpts
>>> AutoEncryptionOpts({}, "foo.bar")
File "<stdin>", line 1, in <module>
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/encryption_options.py", line 230, in __init__
check_min_pymongocrypt()
File "/Users/steve.silvester/workspace/mongo-python-driver/pymongo/encryption_options.py", line 47, in check_min_pymongocrypt
raise ConfigurationError(
pymongo.errors.ConfigurationError: client side encryption requires pymongocrypt>=1.13.0, found version 1.11.0. Install a compatible version with: python -m pip install 'pymongo[encryption]'
```
```python
>>> from pymongo.asynchronous.srv_resolver import _SrvResolver
>>> _SrvResolver('1', 1, '1')
Traceback (most …
```
=> PYTHON-3414 Improve error message when using incompatible dependencies

.evergreen/scripts/setup-dev-env.sh, justfile, pyproject.toml, uv.lock
I verified the change by updating the mypy version, committing without pre-commit, and then running the following:
```
just lint uv-lock
uvx pre-commit run --all-files uv-lock
uv-lock..................................................................Failed
- hook id: uv-lock
- files were modified by this hook
Resolved 98 packages in 1.19s
Updated mypy v1.18.1 -> v1.18.2
``
=> PYTHON-5574 Allow uv lockfile to update from justfile lint

doc/changelog.rst
Post release. Add changelog entry to master's
=> PYTHON-5593 Adds v4.15.2 notes to changelog

.evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Passing build: https://spruce.mongodb.com/version/68e42c782b320700072d0c64/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-5588 Fix python binary used in FIPS tests

.evergreen/generated_configs/tasks.yml, .evergreen/generated_configs/variants.yml, .evergreen/scripts/generate_config.py
Creates new method create_test_standard_auth_tasks that creates tasks "test-standard-auth-*" that only include sharded-cluster. Because the list of clusters is one, we get a task that contains auth and python 3.14t.
=> PYTHON-5598 Add generate_config method to ensure auth is tested on free-threaded python 3.14t
